openedx/edx-app-ios

- edXVideoLocker/OEXDownloadManager.m
@aleffert  @nasthagiri  - Removed dead code from Network module .
Please review .
> removed dead code from download manager class

- edXVideoLocker/Main.storyboard
When the left navigation is open, My Course view should have translucent overlay.
JIRA - https://openedx.atlassian.net/browse/MOB-1384
@jotiram  please review.
> Show overlay on Mycourses view when left navigation panel is open.

- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
App was crashing in Debug mode on login screen because it was trying to send nil event for already logged in user . I have added  nil check before sending login event analytics.
JIRA:https://openedx.atlassian.net/browse/MOB-1386
@aleffert @nasthagiri  Please review .
> Add nil check before sending login analytics event

- Base.lproj/Localizable.strings
- edXVideoLocker/OEXLoginViewController.m
JIRA : https://openedx.atlassian.net/browse/MOB-1110
@aleffert @jotiram please review.
> change google and facebook error messages if user account is not linked.

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/NSBundle+OEXConveniences.h
- edXVideoLocker/NSBundle+OEXConveniences.m
- edXVideoLocker/NSDate+OEXComparisons.h
- edXVideoLocker/NSDate+OEXComparisons.m
- edXVideoLocker/NSString+OEXValidation.h
- edXVideoLocker/NSString+OEXValidation.m
- edXVideoLocker/OEXAppDelegate.h
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXCourse.h
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXDataParser.m
- edXVideoLocker/OEXDateFormatting.h
- edXVideoLocker/OEXDateFormatting.m
- edXVideoLocker/OEXDownloadViewController.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLockerTests/NSDate+OEXComparisonsTests.m
- edXVideoLockerTests/NSString+OEXValidationTests.m
- edXVideoLockerTests/OEXDateFormattingTests.m
This is mostly just factoring and adding some tests. Right now the code has a lot of circular dependencies and so I'm starting an organizational effort by breaking them apart.  There's no reason most of this stuff needs to live in a central location like the app delegate. It's also more testable when in isolated locations. There will be more where this comes from to finish breaking much of the global state of there.
> Factor various things out of the app delegate.

- edXVideoLocker/OEXAppDelegate.h
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.h
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.h
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXDataParser.h
- edXVideoLocker/OEXDataParser.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXFrontTableViewCell.h
- edXVideoLocker/OEXFrontTableViewCell.m
- edXVideoLocker/OEXGenericCourseTableViewController.h
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.h
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLockerTests/OEXDataParserTests.m
Rebuild of https://github.com/edx/edx-app-ios/pull/15 against master
See individual commits.
> Move some more global state out of the app delegate and make it local state

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXAnnouncementsView.m
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXConfig.h
- edXVideoLocker/OEXConfig.m
- edXVideoLocker/OEXCustomTabBarViewViewController.h
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXEnvironment.h
- edXVideoLocker/OEXEnvironment.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXGoogleSocial.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXNetworkInterface.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/OEXRouter.h
- edXVideoLocker/OEXRouter.m
@rohan-dhamal-clarice @jotiram @abhra-clarice 
This also illustrates how we should be dealing with singletons.
> Add router class and example of usage

- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
JIRA: https://openedx.atlassian.net/browse/MOB-1428
@aleffert   please review.
> Show edit button on video list screen in offline mode

- edXVideoLocker.xcodeproj/project.pbxproj
I have enabled generating debug for release build . Also made change in Upload Debugging Symbols to work this in Release mode .
JIRA:https://openedx.atlassian.net/browse/MOB-1481
cc @aleffert
> Enable fabric for release mode

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXNetworkManager.h
- edXVideoLocker/OEXNetworkManager.m
We are not using database in OEXNetworkManager so removed  database related code from there.
Also removed some other unused code .
cc @aleffert
> Remove unused code from OEXNetworkManager

- edXVideoLocker/OEXDownloadViewController.m
- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXNetworkInterface.h
- edXVideoLocker/OEXNetworkInterface.m
- edXVideoLocker/OEXNetworkManager.m
Remove  unused method  which is not getting called .  
cc @aleffert
> remove unused code from network manager

- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
Added "setRegisteredCourses" method to minimize  database hits, while refreshing courses.
cc @aleffert
> Improve refresh courses to minimize database hits

- build.gradle
- edXVideoLocker/Base.lproj/Localizable.strings
- edXVideoLocker/Main.storyboard
> login screen text change

- edXVideoLocker/OEXDateFormatting.m
> Show capital  date string on My course

- edXVideoLocker/OEXDownloadManager.m
- edXVideoLocker/OEXNetworkManager.m
We were getting some crashes while creating  NSURL because of nil path . 
cc @aleffert
> Add nil check for string before creating url to avoid crash

- edXVideoLocker/Base.lproj/Localizable.strings
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXDateFormatting.h
- edXVideoLocker/OEXDateFormatting.m
JIRA: https://openedx.atlassian.net/browse/MOB-1412
cc @aleffert
> Show message for courses which is going to be start in future

- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXVideoPathEntry.h
- edXVideoLocker/OEXVideoPathEntry.m
- edXVideoLocker/OEXVideoSummary.h
- edXVideoLocker/OEXVideoSummary.m
- edXVideoLockerTests/OEXInterFaceTests.m
- edXVideoLockerTests/OEXVideoPathEntryTests.m
- edXVideoLockerTests/OEXVideoSummaryTests.m
Just look for categories instead of making assumptions about depth
JIRA: https://openedx.atlassian.net/browse/MA-302
@BenjiLee please review
> Remove assumptions about course structure.

- edXVideoLocker/OEXCourseInfoTabViewController.m
Pick up a stronger blur to match android.
Cut off the edges to account for them blurring with transparent pixels
implicitly off the edge of the image.
please review @BenjiLee. Frances seemed okay with this
> Improve appearance of course info blur.

- edXVideoLockerTests/NSDate+OEXComparisonsTests.m
- edXVideoLockerTests/OEXDBTests.m
- edXVideoLockerTests/OEXFindCoursesTests.m
disable failing tests. They all operate on the current user's database or make assumptions about the current developer's config, so they're not really good tests anyway.
@BenjiLee please review
> Make all the tests pass

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker.xcworkspace/xcshareddata/edXVideoLocker.xccheckout
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXConfig.h
- edXVideoLocker/OEXConfig.m
- edXVideoLocker/OEXCustomLabel.m
- edXVideoLocker/OEXEnrollmentConfig.h
- edXVideoLocker/OEXEnrollmentConfig.m
- edXVideoLocker/OEXEnvironment.m
- edXVideoLocker/OEXFabricConfig.h
- edXVideoLocker/OEXFabricConfig.m
- edXVideoLocker/OEXFacebookConfig.h
- edXVideoLocker/OEXFacebookConfig.m
- edXVideoLocker/OEXFindCoursesViewController.m
- edXVideoLocker/OEXGoogleConfig.h
- edXVideoLocker/OEXGoogleConfig.m
- edXVideoLocker/OEXGoogleSocial.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXNetworkUtility.h
- edXVideoLocker/OEXNetworkUtility.m
- edXVideoLocker/OEXNewRelicConfig.h
- edXVideoLocker/OEXNewRelicConfig.m
- edXVideoLocker/OEXSegmentConfig.h
- edXVideoLocker/OEXSegmentConfig.m
- edXVideoLocker/OEXZeroRatingConfig.h
- edXVideoLocker/OEXZeroRatingConfig.m
- edXVideoLockerTests/OEXConfigTests.m
I have implemented method to setup composite configuration for  third party  library.
I have also added test cases for OEXConfig.
@aleffert  please review.
> Third party calls  behind flag

- default_config/edx.properties
> added local.yaml to edx.properties

- build.gradle
- edXVideoLocker.xcworkspace/xcshareddata/edXVideoLocker.xccheckout
> Update uploadconfigsymbols in build.gradle

- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
> Hide subtitile label for blank text

- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
> Make download button accessible on video listing screen

- edXVideoLocker/OEXLoginViewController.m
App was crashing because  some ui task was running on background thread .
JIRA: https://openedx.atlassian.net/browse/MOB-1483 
@aleffert  Please review.
> App crashes on reset password

- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXLoginViewController.m
@aleffert  @rahul-clarice  Please review.
> Sign in button should have default blue background

- edXVideoLocker/OEXRegistrationViewController.m
@aleffert  @rahul-clarice  Please review.
> disable all fields on create account button tapped

- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
@aleffert https://openedx.atlassian.net/browse/MA-320
> MA-320 Rewind 30 seconds is now negative

- edXVideoLocker/OEXRegistrationFieldTextAreaView.m
@aleffert  Please review.
JIRA: https://openedx.atlassian.net/browse/MOB-1540
> Textview text should be plain text

- edXVideoLocker/OEXInterface.m
> Last accessed link does not appear

- edXVideoLocker/LoginSplashViewController.m
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/OEXRegistrationViewController.m
- edXVideoLocker/OEXRegistrationViewController.xib
- edXVideoLocker/OEXRouter.h
- edXVideoLocker/OEXRouter.m
Sign up and Login screens should slide in from bottom. Also increase tapable area of cross button.
JIRA: https://openedx.atlassian.net/browse/MOB-1551
@jotiram @aleffert  please review
> Sign up and Login screens should slide in from bottom

- edXVideoLocker.xcworkspace/xcshareddata/edXVideoLocker.xccheckout
- edXVideoLocker/OEXCustomTabBarViewViewController.m
@aleffert  @rahul-clarice  please review.
> Show activity indicator while loading courses

- edXVideoLocker/Base.lproj/Localizable.strings
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXStatusMessageViewController.xib
@aleffert  @rahul-clarice  please review
>  Change error message for section in offline mode

- .tx/config
- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/Base.lproj/Localizable.strings
- edXVideoLocker/NSString+OEXFormatting.h
- edXVideoLocker/NSString+OEXFormatting.m
- edXVideoLocker/OEXCourseInfoTabViewController.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLocalizedString.h
- edXVideoLocker/OEXLocalizedString.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMySettingsViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXRearTableViewController.m
@jotiram @rahul-clarice please review
cc @hanningni
> Add transifex config. Fix problematic loc strings.

- edXVideoLocker.xcworkspace/xcshareddata/edXVideoLocker.xccheckout
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXGoogleSocial.h
- edXVideoLocker/OEXGoogleSocial.m
- edXVideoLocker/OEXLoginViewController.m
@aleffert  @rahul-clarice  please review.
> Login with Google

- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
User enrolments was not getting reload If user logout and login again. I move initialisation code to activateInterfaceForUser: method .
@aleffert  please review .
> Initialize oexinterface on user login

- edXVideoLocker/OEXRouter.m
- edXVideoLocker/OEXVideoPlayerInterface.m
@rahul-clarice  @aleffert  Please review.
> Login screen navigation change

- edXVideoLocker/Base.lproj/Localizable.strings
@aleffert  @rahul-clarice  Please review.
> Resolve syntax error from Localizable.strings file

- edXVideoLocker/Base.lproj/Localizable.strings
@aleffert  @rahul-clarice  Please review.
> change message appear for already enrolled course

- edXVideoLocker/LoginSplashViewController.m
- edXVideoLocker/Main.storyboard
- edXVideoLocker/en.lproj/Localizable.strings
> Login splash screen text change

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXCourseInfoTabViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXFindCourseInterstitialViewController.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXRearTableViewController.h
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/en.lproj/Localizable.strings
Removes a few unused things that strings referenced
JIRA: MA-311
cc @jotiram @rahul-clarice
> Add translator comments for all UI strings

- edXVideoLocker/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MOB-1539
> Create account button text change

- edXVideoLocker/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MOB-1040
> text change

- edXVideoLocker/OEXFlowErrorViewController.h
- edXVideoLocker/OEXFlowErrorViewController.m
- edXVideoLocker/OEXLoginViewController.m
'Reset Password' message should stay till the 'Password reset email sent' message appears.
@jotiram @aleffert Please review.
> Reset Password message should stay

- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCourseVideosTableViewCell.h
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
> Remove video size text from video list screen

- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXCourseInfoTabViewController.xib
- edXVideoLocker/OEXCustomTabBarViewViewController.m
JIRA: https://openedx.atlassian.net/browse/MOB-1624
JIRA: https://openedx.atlassian.net/browse/MOB-1623
JIRA: https://openedx.atlassian.net/browse/MOB-1328
@aleffert  please review.
> courseware screen changes

- edXVideoLocker.xcworkspace/xcshareddata/edXVideoLocker.xccheckout
- edXVideoLocker/OEXFindCoursesViewController.m
- edXVideoLocker/OEXFindCoursesViewController.xib
- edXVideoLocker/OEXFindCoursesWebViewHelper.h
- edXVideoLocker/OEXFindCoursesWebViewHelper.m
> Show loading indicator on find courses screen

- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCourseVideosTableViewCell.h
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
I have revert the changes made #89 . Now we have hide the size label only on video listing  screen.
@aleffert  please review.
> Show video size on screens other than video listing

- edXVideoLocker/OEXRegistrationViewController.m
Merging this directly because it was just the text change.
> Change registration error message.

- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXNetworkConstants.h
@aleffert  please review.
JIRA: https://openedx.atlassian.net/browse/MOB-1617
> switch social login to use oauth

- edXVideoLocker/OEXMyVideosViewController.m
> Show course images my video course list

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/NSJSONSerialization+OEXSafeAccess.h
- edXVideoLocker/NSJSONSerialization+OEXSafeAccess.m
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXDataParser.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXRegistrationViewController.m
JIRA: https://openedx.atlassian.net/browse/MOB-1629
@aleffert  Please review .
> Add category for safe json serialization

- edXVideoLocker/OEXImageCache.m
> Compress local image

- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXRegistrationFieldSelectController.m
- edXVideoLocker/OEXRegistrationFieldValidator.m
- edXVideoLocker/en.lproj/Localizable.strings
> Text change on sign in and sign up screen

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXAuthentication.h
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXHTTPStatusCodes.h
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXNetworkConstants.h
- edXVideoLocker/OEXRegistrationFieldError.h
- edXVideoLocker/OEXRegistrationFieldError.m
- edXVideoLocker/OEXRegistrationViewController.m
Also clean some things up nearby
> Use latest registration endpoint

- edXVideoLocker/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MOB-1618
@rahul-clarice  @aleffert
> Floating message text change

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXRegistrationDescription.h
- edXVideoLocker/OEXRegistrationDescription.m
- edXVideoLocker/OEXRegistrationFieldController.h
- edXVideoLocker/OEXRegistrationFieldSelectController.m
- edXVideoLocker/OEXRegistrationFormField.h
- edXVideoLocker/OEXRegistrationFormField.m
- edXVideoLocker/OEXRegistrationViewController.h
- edXVideoLocker/OEXRegistrationViewController.m
- edXVideoLocker/OEXRegistrationViewController.xib
- edXVideoLocker/OEXRouter.m
- edXVideoLockerTests/OEXRegistrationViewControllerTests.m
> Start adding tests for registration. Style cleanup

- edXVideoLocker/OEXCustomTabBarViewViewController.m
> UI change courseware tab

- edXVideoLocker/OEXCourseInfoTabViewController.m
- edXVideoLocker/OEXHandoutsViewController.m
- edXVideoLocker/OEXRevealOptionsViewController.m
JIRA: https://openedx.atlassian.net/browse/MA-354
> Open handouts+announcements links in external browser

- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
JIRA: https://openedx.atlassian.net/browse/MOB-1647
The issue was that objTranscript could be nil, which would cause a  crash when it tried to construct a dictionary
> Fix crash changing video speed when there are no captions

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXAnalytics.h
- edXVideoLocker/OEXAnalytics.m
- edXVideoLocker/OEXAnalyticsData.h
- edXVideoLocker/OEXAnalyticsData.m
- edXVideoLocker/OEXCourseInfoViewController.m
- edXVideoLocker/OEXRegistrationViewController.m
- edXVideoLocker/OEXSegmentAnalyticsTracker.m
In addition to updating the events as described in this bug, this also
adds registration and enrollment events.
JIRA: https://openedx.atlassian.net/browse/MA-355
> Update events for registration+enrollment

- edXVideoLocker/OEXAuthentication.m
> Fix issue where registration hangs

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXRegistrationFieldEmailView.m
- edXVideoLocker/OEXRegistrationFieldPasswordView.m
- edXVideoLocker/OEXRegistrationFieldSelectView.m
- edXVideoLocker/OEXRegistrationFormTextField.h
- edXVideoLocker/OEXRegistrationFormTextField.m
- edXVideoLockerTests/OEXRegistrationFieldEmailViewTests.m
Note that it should still be enabled for the larger more free form text views
JIRA: https://openedx.atlassian.net/browse/MA-360
> Remove autocorrect from registration text fields.

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXFlowErrorViewController.h
- edXVideoLocker/OEXFlowErrorViewController.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXStatusMessageViewController.h
- edXVideoLocker/OEXStatusMessageViewController.m
- edXVideoLocker/OEXStatusMessageViewController.xib
- edXVideoLocker/OEXVideoPlayerInterface.h
- edXVideoLocker/OEXVideoPlayerInterface.m
- edXVideoLockerTests/OEXStatusMessageViewControllerTests.m
Significantly improves the interface to be less error prone, remove
constants, and better support resizing the status bar, like when getting
directions or receiving a all.
Adds unit tests for the floating status view controller.
JIRA: https://openedx.atlassian.net/browse/MA-359
> Allow floating status view to resize to fit content

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/NSError+OEXKnownErrors.h
- edXVideoLocker/NSError+OEXKnownErrors.m
- edXVideoLocker/OEXFlowErrorViewController.h
- edXVideoLocker/OEXRegistrationViewController.m
JIRA: https://openedx.atlassian.net/browse/MOB-1653
> No error message shown when attempting to register while offline

- edXVideoLocker/OEXStatusMessageViewController.m
- edXVideoLockerTests/OEXStatusMessageViewControllerTests.m
JIRA: https://openedx.atlassian.net/browse/MOB-1654
> Fix issue where status overlay appeared under views

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXLoginSplashViewController.m
- edXVideoLocker/OEXLoginSplashViewController.xib
- edXVideoLocker/edXVideoLocker-Info.plist
This isn't a very interesting patch in itself. But right now almost all
of the app UI is in one storyboard and this is the first step in
separating it out into separate xibs files.
> Move splash screen out of main storyboard into 

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker.xcodeproj/xcshareddata/xcschemes/edXVideoLockerTests.xcscheme
- edXVideoLocker/CutomePlayer/CLPortraitOptionsView.m
- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
- edXVideoLocker/OEXCourseInfoTabViewController.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXDownloadViewController.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/OEXRegistrationViewController.m
- edXVideoLocker/OEXUserLicenseAgreementViewController.m
- edXVideoLocker/OEXVideoPlayerInterface.m
- edXVideoLockerTests/NSString+OEXFormattingTests.m
This fixes a pretty bad leak of an image. The other fixes look pretty
unimportant.
> Enable the Static Analyzer on build and fix all warnings

- edXVideoLocker/CutomePlayer/CLVideoPlayer.m
- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXExternalAuthProviderButton.m
- edXVideoLocker/OEXStatusMessageViewController.h
- edXVideoLocker/OEXStatusMessageViewController.m
- edXVideoLocker/OEXTextStyle.h
- edXVideoLocker/OEXTextStyle.m
- edXVideoLocker/OEXVideoSummary.h
- edXVideoLocker/OEXVideoSummary.m
- edXVideoLocker/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MA-347
> Add only on web flag.

- edXVideoLocker/OEXExternalRegistrationOptionsView.h
- edXVideoLocker/OEXExternalRegistrationOptionsView.m
- edXVideoLocker/OEXRegistrationViewController.m
JIRA: https://openedx.atlassian.net/browse/MOB-1684
> Show a spinner while waiting after tapping FB or Google register

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXApplication.h
- edXVideoLocker/OEXApplication.m
- edXVideoLocker/OEXAuthentication.h
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXExternalAuthProvider.h
- edXVideoLocker/OEXFacebookAuthProvider.m
- edXVideoLocker/OEXGoogleAuthContainerViewController.h
- edXVideoLocker/OEXGoogleAuthContainerViewController.m
- edXVideoLocker/OEXGoogleAuthProvider.m
- edXVideoLocker/OEXGoogleSocial.h
- edXVideoLocker/OEXGoogleSocial.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXOpenInBrowserViewController.h
- edXVideoLocker/OEXRegistrationViewController.m
- edXVideoLocker/OEXRouter.h
- edXVideoLocker/OEXRouter.m
- edXVideoLocker/main.m
- edXVideoLockerTests/OEXApplicationTests.m
JIRA: https://openedx.atlassian.net/browse/MA-618
> Do Google+ authorization from web view in app

- Source/OEXAppDelegate.m
- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXParseConfig.h
- Source/OEXParseConfig.m
- Source/OEXPushNotificationManager.m
- Test/OEXConfigTests.m
> Update Parse config to match final design

- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXCourseInfoTabViewController.m
- Source/OEXDataParser.h
- Source/OEXDataParser.m
- Source/OEXFrontCourseViewController.m
- Source/OEXLatestUpdates.h
- Source/OEXLatestUpdates.m
- Source/OEXParsePushProvider.h
- Source/OEXParsePushProvider.m
- Test/OEXCourse+OEXTestDataFactory.m
- Test/OEXParsePushProviderTests.m
Also factor course parsing code into OEXCourse.
> Add channel id to course and use it with parse.

- Source/NSArray+OEXFunctional.h
- Source/NSArray+OEXFunctional.m
- Source/OEXAppDelegate.m
- Source/OEXCourseInfoTabViewController.h
- Source/OEXCourseInfoTabViewController.m
- Source/OEXCourseInfoTabViewController.xib
- Source/OEXCourseInfoViewController.xib
- Source/OEXCustomTabBarViewViewController.h
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXEnvironment.h
- Source/OEXEnvironment.m
- Source/OEXFrontCourseViewController.m
- Source/OEXInterface.h
- Source/OEXInterface.m
- Source/OEXParsePushProvider.m
- Source/OEXPushNotificationManager.h
- Source/OEXPushNotificationManager.m
- Source/OEXPushProvider.h
- Source/OEXPushSettingsManager.h
- Source/OEXPushSettingsManager.m
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
- Test/OEXCourse+OEXTestDataFactory.m
- Test/OEXMockUserDefaults.h
- Test/OEXMockUserDefaults.m
- Test/OEXParsePushProviderTests.m
- Test/OEXPushNotificationManagerTests.m
- edX.xcodeproj/project.pbxproj
- Includes stub UI that is only visible if PUSH_NOTIFICATIONS flag is
enabled.
- Starts adopting an environment passing pattern for dependencies. The
architectural goal is for the OEXRouter to be responsible for injecting
view controller dependencies. This way each controller is isolated.
JIRA: https://openedx.atlassian.net/browse/MA-607
> Logic for disabling course notifications

- Source/OEXCourseInfoTabViewController.m
- Source/OEXCourseInfoTabViewController.xib
- Source/OEXCourseInfoViewController.xib
- Source/OEXStyles.h
- Source/OEXStyles.m
- Source/OEXSwitchStyle.h
- Source/OEXSwitchStyle.m
- Source/en.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
> Update push UI to match spec

- Source/NSBundle+OEXConveniences.h
- Source/NSBundle+OEXConveniences.m
- Source/OEXParsePushProvider.m
@hanningni please review.
cc @nasthagiri
> Add country to parse device info

- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXCourseDashboardViewController.h
- Source/OEXCourseDashboardViewController.m
- Source/OEXRouter.m
- Source/UIControl+OEXBlockActions.h
- Source/UIControl+OEXBlockActions.m
- Test/OEXCourseDashboardViewControllerTests.m
- Test/UIControl+OEXBlockActionsTests.m
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-705
> iOS: Stub Dashboard UI to access new course structure views

- Source/Array+Functional.swift
- Source/CourseOutline.swift
- Source/CourseStructureQuerier.swift
- Test/Array+FunctionalTests.swift
- Test/XCTestCase+Equality.swift
- edX.xcodeproj/project.pbxproj
Includes a model and a class (CourseStructureQuerier) for accessing
parts of it asynchronously. The latter needs to be hooked up to
an actual persistence implementation at which point it will get a bunch of tests.
JIRA: https://openedx.atlassian.net/browse/MA-687
> First pass at a course outline.

- Source/UIBarButtonItem+OEXBlockActions.h
- Source/UIBarButtonItem+OEXBlockActions.m
- Source/UIControl+OEXBlockActions.m
- Test/UIBarButtonItem+OEXBlockActionsTests.m
- edX.xcodeproj/project.pbxproj
This is going to be necessary since using Selectors in Swift is a pain.
> Add block based extensions for UIBarButtonItem.

- Source/CourseBlockViewController.swift
- Source/CourseOutlineHeaderCell.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineTableViewCell.swift
- Source/CourseOutlineViewController.swift
- Source/LoadState.swift
- Source/OEXCourseDashboardViewController.m
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/edX-Bridging-Header.h
- Test/CourseOutline+TestDataFactory.swift
- edX.xcodeproj/project.pbxproj
Totally unstyled. Still needs loading/empty states.
JIRA: https://openedx.atlassian.net/browse/MA-723
> First pass at course outline view

- Source/Main.storyboard
- Source/OEXConfig.m
- Source/OEXRearTableViewController.m
- Source/SWRevealViewController.h
- Source/SWRevealViewController.m
Resolved the errors and updated what was necessary in code.
> Replaced (modified) SWRevealViewController.h/m with original

- Libraries/SnapKit/.gitignore
- Libraries/SnapKit/.travis.yml
- Libraries/SnapKit/CHANGELOG.md
- Libraries/SnapKit/CodeSnippets/SnapKit Constraint Make.codesnippet
- Libraries/SnapKit/CodeSnippets/SnapKit Constraint Remake.codesnippet
- Libraries/SnapKit/LICENSE
- Libraries/SnapKit/README.md
- Libraries/SnapKit/SnapKit.podspec
- Libraries/SnapKit/SnapKit.xcodeproj/project.pbxproj
- Libraries/SnapKit/SnapKit.xcodeproj/xcshareddata/xcschemes/SnapKit OSX.xcscheme
- Libraries/SnapKit/SnapKit.xcodeproj/xcshareddata/xcschemes/SnapKit iOS.xcscheme
- Libraries/SnapKit/SnapKit.xcworkspace/contents.xcworkspacedata
- Libraries/SnapKit/Source/Constraint.swift
- Libraries/SnapKit/Source/ConstraintAttributes.swift
- Libraries/SnapKit/Source/ConstraintDescription.swift
- Libraries/SnapKit/Source/ConstraintItem.swift
- Libraries/SnapKit/Source/ConstraintMaker.swift
- Libraries/SnapKit/Source/ConstraintRelation.swift
- Libraries/SnapKit/Source/Debugging.swift
- Libraries/SnapKit/Source/EdgeInsets.swift
- Libraries/SnapKit/Source/Info.plist
- Libraries/SnapKit/Source/LayoutConstraint.swift
- Libraries/SnapKit/Source/SnapKit.h
- Libraries/SnapKit/Source/SnapKit.swift
- Libraries/SnapKit/Source/View+SnapKit.swift
- Libraries/SnapKit/Tests/Info.plist
- Libraries/SnapKit/Tests/Tests.swift
- edX.xcodeproj/project.pbxproj
@hanningni please review. cc @ehmadzubair
> Bring in SnapKit which is a Swift friendly autolayout library

- Source/CourseContentPageViewController.swift
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
Just stubs different types of content as different colors for now.
JIRA: https://openedx.atlassian.net/browse/MA-723
> Add scrolling container for course content

- Source/OEXRouter+Swift.swift
- Source/VideoBlockViewController.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-692
> Stub out a video player screen

- Source/CourseDashboardViewController.swift
- Source/OEXConfig.m
- Source/OEXRouter.m
- Source/edX-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
OEXCourseDashboardViewController.h/m to CourseDashboardViewController.swift
> Objective-C to Swift Translation

- Source/Icon.swift
- Source/IconMessageView.swift
- edX.xcodeproj/project.pbxproj
> Better abstract away font awesome

- Source/OEXAppDelegate.h
- Source/OEXAppDelegate.m
- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXDownloadViewController.m
- Source/OEXFrontCourseViewController.m
- Source/OEXGenericCourseTableViewController.m
- Source/OEXInterface.m
- Source/OEXLoginViewController.m
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXRevealOptionsViewController.m
- Source/OfflineModeController.swift
- Source/Reachability.h
- Source/Reachability.m
- Test/MockReachability.swift
- Test/edXTests-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
New interface is easier to mock since it is broken out to a protocol and
an implementation. Also looks a little nicer to swift.
> Factor Reachability to simplify interface

- Source/CourseOutlineItemView.swift
> Constants placement in code changed

- Source/CourseDashboardViewController.swift
in CourseDashboardViewController
> Link full screen announcements

- Source/OEXConfig.m
> Add proper config key for new course navigation

- Test/CourseContentPageViewControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/MockNetworkManager.swift
- Test/NetworkManagerTests.swift
- Test/OfflineModeControllerTests.swift
- Test/XCTestCase+Timeouts.swift
- edX.xcodeproj/project.pbxproj
@ehmadzubair please review. Hopefully this will prevent screenshot generation failures from slow machines.
> Standardize on wait time for test expectations

- Source/CourseDashboardViewController.swift
- Source/DiscussionTopicsViewController.swift
> Fix cell deselection so it doesn't animate

- Source/CourseContentPageViewController.swift
- Source/CourseDataManager.swift
- Source/CourseOutlineViewController.swift
> Make video mode default per spec

- Source/OEXFrontCourseViewController.m
- Source/OEXFrontCourseViewController.storyboard
On my courses screen when user tap on left navigation drawer on right side half of the my courses screen thats appearing is enabled. It should get disabled.
> iOS - Issue with My Courses screen when user tap on left navigation drawer

- Source/AuthenticatedWebViewController.swift
- Source/ContentInsetsController.swift
- Source/CourseOutlineViewController.swift
- Source/GradedSectionMessageView.swift
- Source/HTMLBlockViewController.swift
- Source/ViewTopMessageController.swift
- Source/en.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
Tests and screenshots to follow
> Add 'graded' header for content in graded sections

- Source/Box.swift
- Source/OEXRemovable.h
- Source/Removable.swift
- Source/Result.swift
- Source/Stream.swift
- Source/edX-Bridging-Header.h
- Test/MockNetworkManager.swift
- Test/StreamTests.swift
- edX.xcodeproj/project.pbxproj
Adds three new types:
Stream: A way to listen to a sequence of values
Sink: A writeable stream
CancellingSink: A writeable stream that triggers a cancellation action if no one is watching it.
JIRA: https://openedx.atlassian.net/browse/MA-795
> Add stream support for typed notifications.

- Source/OEXMySettingsViewController.xib
> Download button now shows right regardless of language direction.

- Source/CourseOutlineViewController.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/DownloadProgressViewTests.swift
All tests are passing on local environment
> Added Last Accessed Tests

- Source/OEXCustomNavigationView.m
- Source/OEXMyVideosSubSectionViewController.m
> iOS: Incorrect title bar inside my videos section

- Source/PersistentResponseCache.swift
Haven't needed this yet, but seems like it'll be useful to have around.
Could probably use file modification date in a pinch, but something
explicit seems safer.
> Add creation date to response cache.

- Source/ContentInsetsController.swift
- Source/CourseOutlineViewController.swift
- Source/DownloadProgressViewController.swift
- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXCourseVideoDownloadTableViewController.storyboard
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXDownloadViewController.h
- Source/OEXDownloadViewController.m
- Source/OEXDownloadViewController.storyboard
- Source/OEXFrontCourseViewController.m
- Source/OEXGenericCourseTableViewController.m
- Source/OEXHandoutsViewController.m
- Source/OEXHandoutsViewController.xib
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXMyVideosViewController.storyboard
- Source/OEXRevealOptionsViewController.m
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
Fix assorted localization issues in OEXDownloadsViewController. Switch
to standard navigation bar.
JIRA: https://openedx.atlassian.net/browse/MA-968
> Connect view button to download progress.

- Source/OEXLoginViewController.m
> Login Screen Status bar now matches specification

- Source/ContentInsetsController.swift
- Source/KeyboardInsetsSource.swift
- Test/ContentInsetsControllerTests.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-954 When inputting an answer into a textbox, the keyboard autoscrolls over the textbox
> Fix issue calculating content insets with keyboards. Add tests.

- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutlineItemView.swift
- Source/CourseSectionTableViewCell.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXVideoSummary.m
- Source/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MA-938
> Add default text to untitled blocks

- Source/OEXFrontTableViewCell.m
- Source/OEXMyVideosViewController.m
- Source/OEXMyVideosViewController.storyboard
> iOS - Assessment - My Videos - All Videos - Video size positioning issue

- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosSubSectionViewController.storyboard
> iOS - Assessment - My Video - if the name of the video is long it merges with the circle

- Source/OEXDownloadViewController.m
Fixed.
https://openedx.atlassian.net/browse/MA-991
> iOS - Assessment - 'My video' title is appearing with back arrow on downloading screen

- Source/OEXStyles.m
MA-990 : iOS - Assessment - My Settings - Navigation drawer icon color issue
https://openedx.atlassian.net/browse/MA-990
MA-985 : iOS - Assessment - My Videos - Back arrow color in my video section is different
https://openedx.atlassian.net/browse/MA-985
Fixes both the issues
> MA-990 + MA-985

- Source/CourseOutlineModeController.swift
- Source/Icon.swift
- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MA-946
> Update change mode UI to clarify what is currently selected.

- Source/OEXCourseInfoViewController.m
- Source/OEXFrontCourseViewController.m
- Source/OEXRearTableViewController.m
- Source/OEXRouter.h
- Source/OEXRouter.m
Also fixes:
- Issue for instances without find courses support, that
would attempt to show web content.
- Crash when enrolling in course.
JIRA: https://openedx.atlassian.net/browse/MA-1020
> App crashes on course screen.

- Source/OEXFrontCourseViewController.storyboard
Fixed, however the right way to do this would be to make a separate ProgressController which is owned by the controller (it is added to). Also, it has to be shifted to AutoLayout when doing that
@aleffert Do you agree?
Pl review
> Bug Fix: iOS - Assessment - Area issue in downloading wheel

- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXCoursewareAccess.h
- Source/OEXCoursewareAccess.m
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXFrontCourseViewController.m
- edX.xcodeproj/project.pbxproj
This is the PR for MA-852. The "Jan 1, 2030" start date error is fixed using the new courseware_access field in mobile API.
Reviewers: @nasthagiri, @aleffert
> Fix start message error 

- Source/OEXFrontCourseViewController.m
- Source/OEXFrontCourseViewController.storyboard
- Source/OEXStyles+Swift.swift
- Source/ProgressController.swift
- Source/edX-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
> Add ProgressController

- Source/CourseOutlineItemView.swift
@aleffert  This was causing a crash on courseware, so merging it right now.
> Bug Fix : MA-1094

- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
> Fix issue with things fading at inappropriate times

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
https://openedx.atlassian.net/browse/MA-1091
> iOS - Discussions - Issues in 'Post and Responses' screen

- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
On fixing Issue #1 it changed the text on the comment screen also.On comments screen, it should only show "#Comments" instead of "# comments to this response"
> Minor change for bug fix MA-1091

- Source/IconMessageView.swift
- Source/VideoBlockViewController.swift
> Replace "This video's transcript is not..." placeholder in portrait video player

- QLearnSDK/DiscussionObjectModel.swift
- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
Question shows as a question type now.
> Show different UI for different post types

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
Getting and Setting read state.
The PATCH however isn't successful because the `read` field isn't editable...
```
{
"field_errors" : {
"read" : {
"developer_message" : "This field is not editable."
}
}
}
```
> iOS - Discussions - No difference between Read/Unread posts

- Source/PostTitleByTableViewCell.swift
Some points need to be cleared on  [JIRA] (https://openedx.atlassian.net/browse/MA-1123)
> Posts screen now matches spec *more*

- Source/CourseOutlineViewController.swift
- Source/Icon.swift
- Source/PostsViewController.swift
The renderers have been added as suggested. They can't do all of the things on their own because that'd be a lot of rework.
Secondly, what am i doing wrong with the rotation, any ideas?
> Added icon renderers

- Source/DiscussionTopicsViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
MA-1147: iOS - Discussions- App opens multiple search result screens and crashes.
> Refactoring Posts to own the search. Also fixes MA-1147

- Source/AuthenticatedWebViewController.swift
- edX.xcodeproj/project.pbxproj
Note: Does not actually enable said support while I investigate a web
content issue related to viewports.
See: https://openedx.atlassian.net/browse/MA-960
JIRA: https://openedx.atlassian.net/browse/MA-790
> Support for WKWebView in HTML blocks.

- Source/DiscussionAPI.swift
- Source/NetworkManager.swift
- Source/NetworkPaginator.swift
- Source/PaginatedFeed.swift
- Source/PostsViewController.swift
- edX.xcodeproj/project.pbxproj
Created a generic `NetworkPaginator` which takes generic `PaginatedNetworkRequests` and asks for subsequent pages.
- Integrated it with `PostsViewController` to go over the implementation. Once it is done, i will integrate it in the remaining screens.
> Network Paginator

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
The post detail is only shown when the responses have loaded
> iOS - Discussions - App takes some time in loading the responses

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
- Source/NetworkPaginator.swift
- Source/PaginatedFeed.swift
Also fixes a couple of bugs in `NetworkPaginator`
> Pagination implemented on responses screen

- Source/PostsViewController.swift
- Source/PullRefreshController.swift
- Source/SpinnerView.swift
- edX.xcodeproj/project.pbxproj
The drag to activate interaction needs work.
> Add pull to refresh helper. Implement on posts controller.

- Source/OEXCourseVideoDownloadTableViewController.storyboard
- Source/OEXDownloadViewController.m
- Source/OEXDownloadViewController.storyboard
> remove download video view MA-1054

- Source/PostsViewController.swift
This might have snuck in due to a merge conflict resolution
@mikekatz pl review
> Fixed minor issue with the sort button

- Source/MenuOptionsViewController.swift
> Added line separators

- Source/PostsViewController.swift
Not refactoring `PostsViewController` because the API hasn't yet been finalised.
> Posts screen shows the correct title now

- Source/DiscussionAPI.swift
- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
> Filter by MOST VOTES now matches spec

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
Will have to merge it right away...
@mikekatz FYI
> Bug Fix : Discussion Post didn't load because of the endorsed flag

- Source/CourseContentPageViewController.swift
- Source/CourseDashboardViewController.swift
- Source/CourseOutlineViewController.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/OEXOpenInBrowserViewController.m
- Source/OEXRouter+Swift.swift
- Source/OEXRouter.m
- Source/OpenOnWebController.swift
- Source/edX-Bridging-Header.h
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/OEXMockAnalyticsTracker.m
- Test/OpenOnWebControllerTests.swift
- Test/edXTests-Bridging-Header.h
Event spec is here https://openedx.atlassian.net/wiki/display/MA/Assessments+Analytics
Also migrated existing navigation events for new UI
TODO: Update to latest Segment SDK and add dimensions
JIRA: https://openedx.atlassian.net/browse/MA-1049
JIRA: https://openedx.atlassian.net/browse/MA-873
> Add analytics for assessments + new navigation

- Source/CourseOutlineQuerier.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/PullRefreshController.swift
- Source/Stream.swift
UX might still have opinions about this, but it seemed like a reasonable stake in the ground.
> Improve pull refresh animation+interaction. Connect to course outline.

- Source/DiscussionResponsesViewController.swift
Going to merge this because this is causing a crash in the master branch
> Bug fix : Invalid Localizable.strings key

- Source/DiscussionResponsesViewController.swift
- Source/MenuOptionsViewController.swift
- Source/NetworkPaginator.swift
- Source/PostsViewController.swift
MA-1127 + Code clean up for pagination trigger
> iOS: Match topic drop down to spec

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
Did the same for the follow button...
> Vote icon color should change if voted

- Source/DiscussionResponsesViewController.swift
Android - iOS - Discussions - Discrepancy in '# of responses' on discussion post screens
> bug fix : MA-1355

- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
> iOS - Discussions - Text 'This post is visible to everyone/cohort' is missing in discussion post screen

- .travis.yml
- Test/SnapshotTestCase.swift
- build.gradle
- edX.xcodeproj/project.pbxproj
Had to disable the tests on iOS 8 for now. Hoping that when xctool gets
a bug fix I'm depending on, we can switch back to it. I think that will
also let us do fewer rebuilds.
> Attempt to fix build

- Source/DiscussionAPI.swift
- Source/PostTableViewCell.swift
- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
- edX.xcodeproj/project.pbxproj
> iOS - Discussions - Filtering 'Most Votes' app shows responses in front of posts

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionAPI.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
- Test/DiscussionNewCommentViewControllerTests.swift
MA-1081 - iOS - Discussions - Issues in 'Add a comment' screen	
MA-1255 - iOS - Discussions - Post screen do not show pin icon if the post is pinned
MA-1355 - Android - iOS - Discussions - Discrepancy in '# of responses' on discussion post screens
> Fixes MA-1081 + MA-1255 + MA-1355

- Source/AuthenticatedWebViewController.swift
JIRA: https://openedx.atlassian.net/browse/MA-960
> Enable WKWebView permanently, now that we're on iOS 8 + back end is updated

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewCommentViewController.xib
- Source/DiscussionResponsesViewController.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Test/DiscussionNewCommentViewControllerTests.swift
+ One minor auto-layout change on DiscussionCommentsViewController
> Replacing AuthorLabelType with a string

- Source/Main.storyboard
- Source/OEXRouter.h
- Source/OEXRouter.m
- Test/OEXRouterTests.m
@mikekatz please review (SORRY)
> Fix regression where side navigation no longer shows

- Source/CourseContentPageViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutlineItemView.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CourseSectionTableViewCell.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXStyles.m
- Source/TableCellStyle.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-1349
> Highlight last block navigated to in page view

- Source/CourseDataManager.swift
- Source/CourseOutline.swift
- Source/CourseOutlineQuerier.swift
- Source/CourseStructureAPI.swift
- Source/JSON+RawValueExtractable.swift
- Source/Logger.swift
- Source/NetworkManager.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXEnvironment.m
- Source/UserProfile.swift
- Test/CourseDataManagerTests.swift
- Test/CourseOutlineQuerierTests.swift
- Test/MockCourseDataManager.swift
- edX.xcodeproj/project.pbxproj
Note that the server will still need to updated so this will probably
end up getting another pass.
JIRA: https://openedx.atlassian.net/browse/MA-1399
> Update to latest course outline endpoint.

- Source/CourseContentPageViewController.swift
JIRA: https://openedx.atlassian.net/browse/MA-1129
> Cannot use video progress bar because of conflicting gesture.

- Source/DiscussionAPI.swift
Non courseware topics need to be shown prior to the courseware topics
> Topics order now matches Web

- Source/PostsViewController.swift
If a root node is selected, it's first node should be the selected topic
> Change in choose a topic functionality

- Source/DiscussionTopicsViewController.swift
Going to merge because this is a style change
> Minor change in color

- Source/CourseStructureAPI.swift
> Update student_view_data argument to new format

- Source/NetworkPaginator.swift
- Source/SpinnerView.swift
Same as the Pull to refresh controller
> Replaced the spinner on the NetworkPaginator

- Source/CourseVideoTableViewCell.swift
This was meant to be removed with the previous cell style background change.
> Remove video cell background

- Source/DiscussionResponsesViewController.swift
- Source/OEXTextStyle.h
- Source/OEXTextStyle.m
- Source/UserProfileViewController.swift
- Test/OEXTextStyleTests.swift
In an Objective-C free world we'd just make this a struct.
> Add copy constructor to mutable text style.

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.xib
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/UIView+LayoutDirection.swift
The content that was getting truncated needlessly needed an appropriate `contentHorizontalAlignment`
> Discussion RTL support should be complete now

- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/JSONFormBuilder.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Source/UserProfileEditViewController.swift
- script/Localizations.swift
@mikekatz please review. I thought this was clearer.
> Include first argument name in parameterized localization strings

- script/Localizations.swift
> Expose localized strings to ObjC

- Source/CourseCardViewModel.swift
- Source/CourseDashboardCourseInfoView.swift
- Source/CourseDashboardViewController.swift
- Source/NSAttributedString+Combination.swift
- Source/OEXFrontCourseViewController.m
- Source/OEXFrontCourseViewController.storyboard
- Source/OEXMyVideosViewController.m
- Source/OEXMyVideosViewController.storyboard
- Source/en.lproj/Localizable.strings
Fixes MA-1260 + MA-1384
Vertical line in course run of course card positioning is incorrect. In addition to this additional green tile is appearing in 'My Videos' course card.
Also moves `OEXFrontCourseViewController` to Auto-resizing cells
Fixes the following
1 - On my courses screen there is a grey bar under course cards. It shouldn't be there.
2 - On my courses screen and course dashboard screen color of the course run in course cards should be according to the style guide.
3 - Space issue between course card and tabs (Course ware,discussions etc)
4 - Course card in my videos section shouldn't be stretched from right and left.
> iOS - Vertical line in course run of course card positioning issue

- Source/CourseOutlineTableSource.swift
JIRA: https://openedx.atlassian.net/browse/MA-1349
> Scroll to last visited block when popping to outline view

- Source/CourseDashboardCell.swift
- Source/CourseDashboardCourseInfoView.swift
- Source/CourseDashboardViewController.swift
- Source/OEXMyVideosViewController.storyboard
OEXFrontCourseViewController -> DiscussionTopicsViewController
> UI Polish pass

- Source/CourseSectionTableViewCell.swift
JIRA: https://openedx.atlassian.net/browse/MA-1420
> Fix issue losing videos listener in section cell.

- Source/OEXInterface.m
We weren't filtering based on the input state.
JIRA: https://openedx.atlassian.net/browse/MA-1421
> Fix issue displaying too many videos

- Source/OEXCourseInfoTabViewController.m
@aleffert going to merge it because it was causing the master branch to break
> Fix : Localizable Strings weren't parameterized

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
- Source/NetworkPaginator.swift
- Source/PostsViewController.swift
Some changes to the `NetworkPaginator` so that we can relay the error to the VC
> Discussions error handling + search thread pagination

- Source/GradedSectionMessageView.swift
JIRA: https://openedx.atlassian.net/browse/MA-1439
> Add separator for graded header

- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewCommentViewController.xib
@aleffert 
There's this very absurd behaviour of the `SpinnerButton` here (as [reported] (https://openedx.atlassian.net/browse/MA-1391) by Mirza)
Turns out, that this erratic behaviour is because of the `UITapGestureRecogniser` on self.view which resigns the first responder.
Can you please look into this?
> Fixes the SpinnerButton TouchUpOutside issue

- Source/DiscussionResponsesViewController.swift
@aleffert going to go ahead and merge, since this is trivial
> AuthorLabel's author doesn't repeat anymore

- .travis.yml
Per travis support. They're working on a way to make this not be a
problem when they upgrade tools
> Fix travis by updating simulator uuid for prelaunching.

- Source/AuthenticatedWebViewController.swift
- Source/CourseAnnouncementsViewController.swift
- Source/CourseContentPageViewController.swift
- Source/CourseDashboardViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/CourseOutlineViewController.swift
- Source/CourseUnknownBlockViewController.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DiscussionTopicsViewController.swift
- Source/HTMLBlockViewController.swift
- Source/IconMessageView.swift
- Source/LoadStateViewController.swift
- Source/OEXCourse.m
- Source/OEXCoursewareAccess.m
- Source/OEXRouter+Swift.swift
- Source/OEXRouter.m
- Source/PostsViewController.swift
- Source/VideoBlockViewController.swift
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/OEXCourse+OEXTestDataFactory.h
- Test/OEXCourse+OEXTestDataFactory.m
JIRA: https://openedx.atlassian.net/browse/MA-1237
There are two commits here. The first is mechanical prep for the second - removing the styles argument to LoadStateViewController. The second has the actual interesting change.
> Hide dashboard when course hasn't started

- Source/CourseContentPageViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseLastAccessedController.swift
- Source/CourseOutline.swift
- Source/CourseOutlineHeaderCell.swift
- Source/CourseOutlineItemView.swift
- Source/CourseOutlineViewController.swift
- Source/CourseSectionTableViewCell.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXVideoSummary.h
- Source/VideoBlockViewController.swift
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
JIRA: https://openedx.atlassian.net/browse/MA-1233
> Consistently display "Untitled" for blocks without names

- Source/CropViewController.swift
- Source/OEXAnalytics+Profiles.swift
- Source/OEXAnalytics.h
- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/OEXRouter+Swift.swift
- Source/ProfilePictureTaker.swift
- Source/UserProfileEditViewController.swift
- edX.xcodeproj/project.pbxproj
rock me analytics. Add two new trackers.
> tracking! MA-1450

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
> Polish pass for Discussion Posts + Responses

- Source/Main.storyboard
- Source/OEXFindCoursesViewController.m
- Source/OEXFrontCourseViewController.m
- Source/OEXMySettingsViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/RevealViewController.swift
- Test/OEXRouterTests.m
JIRA: https://openedx.atlassian.net/browse/MA-1575
> Fix RTL for navigation drawer on iOS 9

- Source/AuthenticatedWebViewController.swift
- Source/GradedSectionMessageView.swift
- Source/OEXHTTPStatusCode+Groups.swift
- Source/en.lproj/Localizable.strings
- Pin graded header
- Fix issue where very first load of authenticated web content wouldn't
display.
JIRA: https://openedx.atlassian.net/browse/MA-1598
> Assorted fixes for html content

- Source/CourseCardViewModel.swift
- Source/Dictionary+Functional.swift
- Source/OEXCourse+TestData.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXDateFormatting.h
- Source/OEXDateFormatting.m
- Source/en.lproj/Localizable.strings
- Test/CourseCardViewModelTests.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/OEXDateFormattingTests.m
- Test/OEXParsePushProviderTests.m
- Test/OEXPushNotificationProcessorTests.m
- Test/OEXRouterTests.m
- edX.xcodeproj/project.pbxproj
- Add additional fields to course test data - tweak for objc interaction
JIRA: https://openedx.atlassian.net/browse/MA-1602
> Use start date info for course card display

- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
iOS Discussions - Define the desired behaviour when no Threads are found
-> All 5 different cases handled as per discussed in story. Please review and let me know if I missed any.
> Saeed ma 1483

- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXMyVideosSubSectionViewController.m
Think this got lost in a refactor.
> Fix crash in My Videos -> Course -> Rotate

- Pods/Analytics/Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m
This makes me pretty unhappy since this code is brought in via pods, but
they seemed to have EOL'd the 2.0.x train and 3.0 (currently master on
github) isn't released.
Alternate suggestions welcome
> Fix segment's count to recognize dimensions properly

- Source/CutomePlayer/CLVideoPlayerControls.m
JIRA: https://openedx.atlassian.net/browse/MA-1651
> Fix gesture conflict preventing slider end action from being sent sometimes

- Source/OEXMySettingsViewController.xib
- Test/OEXMySettingsViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
When I was factoring all the OEXRevealOptionsViewController classes I
fixed MySettingsViewController, but I missed fixing the storyboard too.
JIRA: https://openedx.atlassian.net/browse/MA-1654
@mikekatz please review
> Fix crash opening settings.

- Source/SegmentAnalyticsTracker.swift
> Fix issue with orientation analytics

- Source/OEXRouter+Swift.swift
JIRA: https://openedx.atlassian.net/browse/MA-1694
> Use the "unknown" screen for only on web videos

- Source/CourseDashboardViewController.swift
- Source/OEXFrontCourseViewController.m
- Source/ProgressController.swift
Also fixes a cycle in the ownership graph
JIRA: https://openedx.atlassian.net/browse/MA-1693
> Show download wheel on course dashboard

- Source/DebugLogViewController.swift
- Source/DebugMenuLogger.swift
- Source/DebugMenuViewController.swift
- Source/Logger.swift
- Source/Main.storyboard
- Source/OEXAppDelegate.m
- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXRearTableViewController.swift
- Source/OEXRouter+Swift.swift
- edX.xcodeproj/project.pbxproj
Add a menu item to open up an internal console log.
> add internal console logging

- Source/OEXConfig.m
Makes it easy to have local settings without having to deal with config
files or temporary config changes escaping into builds.
> Support setting config flags from the environment.

- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/ProgressController.swift
- Source/UIButton+TintColor.swift
- edX.xcodeproj/project.pbxproj
https://openedx.atlassian.net/browse/MA-1214
> Download button Arrow tint color changed to neutralBase on Course dashboard

- Source/CutomePlayer/CLVideoPlayerControls.m
- Source/CutomePlayer/OEXVideoPlayerSettings.swift
- Source/OEXConstants.h
- Source/OEXInterface.h
- Source/OEXInterface.m
- Source/OEXVideoPlayerInterface.m
Persisting video playback speed.
https://openedx.atlassian.net/browse/MA-1528
> Video Playback speed Persistence

- Source/OEXMyVideosViewController.m
- Source/en.lproj/Localizable.strings
https://openedx.atlassian.net/browse/MA-1527
> Capitalized My Videos - Recent Videos

- Source/OEXDownloadTableCell.m
https://openedx.atlassian.net/browse/MA-1676
> download 'X' color changed to neutralBase

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
https://openedx.atlassian.net/browse/MA-1350
> PATCH to mark thread as read

- Source/DiscussionAPI.swift
PATCH content-type changed to "application/merge-patch+json"
https://openedx.atlassian.net/browse/MA-1657
> Patch request content-type changed

- Source/CutomePlayer/CLVideoPlayerControls.m
https://openedx.atlassian.net/browse/MA-1702
> Video Play/Pause button state issue

- Source/OEXAnalytics.m
- Source/OEXAppDelegate.m
- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXInterface+Swift.swift
- Source/OEXInterface.m
- Source/OEXRearTableViewController.swift
https://openedx.atlassian.net/browse/MA-1690
> Automatically logout user on server change

- Source/VideoBlockViewController.swift
https://openedx.atlassian.net/browse/MA-1645
> Video continually  play in background

- Source/OEXConstants.h
- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXCustomEditingView.m
- Source/OEXCustomNavigationView.m
- Source/OEXFlowErrorViewController.m
- Source/OEXFlowErrorViewController.xib
- Source/OEXFrontCourseViewController.m
- Source/OEXLoginViewController.storyboard
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosSubSectionViewController.storyboard
- Source/OEXMyVideosViewController.m
- Source/OEXMyVideosViewController.storyboard
https://openedx.atlassian.net/browse/MA-1713
> Remove assumption of 320 pt wide screens

- Source/OEXRouter.m
We were never propagating the dependencies down.
JIRA: https://openedx.atlassian.net/browse/MA-1794
> Fix issue with my videos course list not showing images

- Source/LastAccessed.h
- Source/OEXInterface+Swift.swift
fix production bug where some vals might be nil MA-1823
> guard against core data nils.

- Source/OEXFileUtility.m
- Test/OEXFileUtilityTests.m
Handle extra case where we had a file extension
JIRA: https://openedx.atlassian.net/browse/MA-1819
> Fix issue migrating video files

- Source/NSBundle+OEXConveniences.h
- Source/NSBundle+OEXConveniences.m
- Source/NetworkManager.swift
- Source/OEXAppDelegate.m
- Source/UserAgentOverrideOverrideOperation.swift
- Test/OEXMockUserDefaults.m
- Test/UserAgentGenerationOperation.swift
- Test/XCTestCase+Async.swift
- edX.xcodeproj/project.pbxproj
Should be (existing agent) (appname)/(app-build)
For example: Mozilla/1.2.3 WebKit/45.6 edX/2.0.1
This only affects requests made in web views.
> Customize user agent in WKWebView

- Source/CertificateViewController.swift
- Source/en.lproj/Localizable.strings
> certificate fixes

- Source/CourseOutlineViewController.swift
https://openedx.atlassian.net/browse/MA-1806
> Discrepancies in courseware messages

- Source/VideoBlockViewController.swift
https://openedx.atlassian.net/browse/MA-1817
> Video section disappears on swiping the screens

- Test/NetworkManagerTests.swift
- Test/TestEnvironmentBuilder.swift
> Remove accidentally commited test code

- Source/OEXMyVideosSubSectionViewController.m
https://openedx.atlassian.net/browse/MA-1795
> App don't not show section name if it is 'Untitled'

- Source/DiscussionAPI.swift
The underlying server bug has been resolved so we don't need this
> Remove no longer necessary python string coercions.

- Source/OEXDownloadViewController.m
> fix video url crash

- Source/LoadStateViewController.swift
> fix the black loading background

- Source/OEXMyVideosSubSectionViewController.m
https://openedx.atlassian.net/browse/MA-1795
> add untitled if chapter name is empty

- Source/PostsViewController.swift
iOS - Discussions - Search results screen do not show the 'searched text string' in search bar
https://openedx.atlassian.net/browse/MA-1706
> Discussions show searched text

- Source/UserAgentOverrideOverrideOperation.swift
We were instantiating a WKWebView on a background thread and even though
we weren't doing anything with it, it borked everything.
Weirdly this was impacting both WKWebView and UIWebView.
> Fix issue with webviews.

- Source/Array+Functional.swift
- Source/CourseCatalogAPI.swift
- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogDetailViewController.swift
- Source/CourseDashboardViewController.swift
- Source/EnrollmentShared.swift
- Source/LoadStateViewController.swift
- Source/NSHTTPURLResponse+OEXHelpers.swift
- Source/OEXConstants.h
- Source/OEXCourseInfoViewController.m
- Source/OEXEnrollmentMessage.h
- Source/OEXEnrollmentMessage.m
- Source/OEXFrontCourseViewController.m
- Source/OEXHTTPStatusCode+Groups.swift
- Source/OEXInterface.h
- Source/OEXInterface.m
- Source/OEXStatusMessageViewController.h
- Source/OEXStatusMessageViewController.m
- Source/SpinnerButton.swift
- Source/UserCourseEnrollment.swift
- Source/edX-Bridging-Header.h
- Test/Array+FunctionalTests.swift
- Test/CourseCatalogDetailViewControllerTests.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/OEXInterface+Mock.h
- Test/OEXInterface+Mock.m
- Test/OEXRouterTests.swift
- edX.xcodeproj/project.pbxproj
TODO: Show the course after enrollment success instead of the course
list
JIRA: https://openedx.atlassian.net/browse/MA-1699
> Connect native course enrollment UI

- Source/OEXStatusMessageViewController.m
- Source/OEXStatusMessageViewController.xib
- Source/VideoBlockViewController.swift
https://openedx.atlassian.net/browse/MA-1816
> Show overlay message in case of video  in offline mode

- Source/UIViewController+Overlay.swift
- Source/VideoBlockViewController.swift
setting message label lines to zero.
> changes offline overlay message in video block

- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-1870
> *hopefully* remove notification warning message on build

- Source/CourseAnnouncementsViewController.swift
- Source/CourseDashboardViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/DataManager.swift
- Source/EnrollmentManager.swift
- Source/NetworkManager.swift
- Source/OEXRouter.m
- Source/Stream.swift
- Test/CourseAnnouncementsViewControllerTests.swift
- Test/XCTestCase+Async.swift
Also improve behavior of cached streams when dealing with no internet
connection. Before it would briefly show a no wifi message even if
something was going to load.
Now it will only show that if there's nothing cached.
> Significantly improve how announcements loads

- Source/UserProfile.swift
fix crash when removing languages
> set languages to [] instead of null for none. MA-1861

- Source/DiscussionResponsesViewController.swift
- Source/PostTableViewCell.swift
https://openedx.atlassian.net/browse/MA-1890
> Discussions - Posts are not marked as read when viewed

- Source/OEXEnvironment.m
- Source/OEXPushNotificationManager.h
- Source/OEXPushNotificationManager.m
We were ending up with a nil settings manager due to an ordering thing.
JIRA: https://openedx.atlassian.net/browse/MA-1885
> Fix issue with notification disabling

- Source/CourseCatalogAPI.swift
JIRA: https://openedx.atlassian.net/browse/MA-1716
> Filter course list to only include mobile

- Source/CourseDashboardViewController.swift
- Source/OEXConfig.swift
- Source/ShareHelper.swift
- Source/TwitterConfig.swift
- edX.xcodeproj/project.pbxproj
also need to add TWITTER.HASHTAG to the config
> add the ability to replace platform name with twitter hashtag when sharing to twitter

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionAPI.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/NetworkPaginator.swift
- Source/OEXRouter+Swift.swift
- Source/Paginator.swift
- Test/DiscussionNewCommentViewControllerTests.swift
- Test/PaginatorTests.swift
- Test/TablePaginationControllerTests.swift
https://openedx.atlassian.net/browse/MA-1747
> Discussions- User is unable to add comments

- Source/DiscussionResponsesViewController.swift
- Source/NSError+JSON.swift
- Source/NetworkManager.swift
- Source/OEXRouter+Swift.swift
- Test/EnrollmentManagerTests.swift
- Test/MockRouter.swift
- Test/NetworkManagerTests.swift
- edX.xcodeproj/project.pbxproj
https://openedx.atlassian.net/browse/MA-1946
> added TablePaginationController + UnwrappedNetworkPaginator to DiscusssionVC 

- Source/CourseCatalogAPI.swift
- Source/PaginationInfo.swift
- Test/PaginationInfoTests.swift
JIRA: https://openedx.atlassian.net/browse/MA-1698
> Use standard page size for course catalog

- Test/CourseCatalogDetailViewControllerTests.swift
- Test/EnrollmentManagerTests.swift
- Test/OEXRouterTests.swift
- Test/XCTestCase+Async.swift
I'm not totally sure why this is necessary since it works locally.
> Fix flakey enrollment manager test

- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponsesViewController.swift
https://openedx.atlassian.net/browse/MA-1747
> User is unable to add comments

- Source/CourseCatalogDetailViewController.swift
- Source/EnrolledCoursesViewController.swift
- Only show overlay message if tapping "Enroll now" not "View Course".
- Hide back text for course catalog
JIRA: https://openedx.atlassian.net/browse/MA-1699
> Minor bugs with native course detail screen

- .travis.yml
add coverage tool MA-1938
https://codecov.io/github/edx/edx-app-ios/
> try to upload reports

- Source/LogoutService.swift
- Source/NetworkManager.swift
- Test/NetworkManagerTests.swift
- edX.xcodeproj/project.pbxproj
And special handling instead for refresh to filled out with the next phase
> add logout for all 401s

- Source/DiscussionResponsesViewController.swift
https://openedx.atlassian.net/browse/MA-1962
> Endorsed Responses/Answers functionality is not working

- Source/en.lproj/Localizable.strings
JIRA: https://openedx.atlassian.net/browse/MA-1940
> Remote text referencing seeing

- Source/ProfileBanner.swift
JIRA: https://openedx.atlassian.net/browse/MA-2049
> Fix text color in profile header

- Source/NSBundle+OEXConveniences.h
- Source/OEXRearTableViewController.swift
- Source/en.lproj/Localizable.strings
- Test/OEXRearTableViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-1865
> Add useful information to feedback emails.

- Source/CertificateViewController.swift
- Source/ContainerNavigationController.swift
- Source/CourseContentPageViewController.swift
- Source/CourseDashboardViewController.swift
- Source/OEXRouter.m
- Source/RevealViewController.swift
- Source/SingleChildContainingViewController.swift
- Source/VideoBlockViewController.swift
- edX.xcodeproj/project.pbxproj
PDF certs look really bad in portrait so add landscape support to that
screen.
JIRA: https://openedx.atlassian.net/browse/MA-1611
> Support viewing certs in landscape

- Source/FindCoursesWebViewHelper.swift
> just open those links in outside safari

- Source/DiscussionResponsesDataController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DiscussionTestsDataFactory.swift
- Test/DiscussionNewCommentViewControllerTests.swift
- Test/DiscussionResponsesDataControllerTests.swift
- edX.xcodeproj/project.pbxproj
https://openedx.atlassian.net/browse/MA-2101
Updating team in project settings
> adding comment to endorsed response

- Source/OEXRearTableViewController.swift
@aleffert 
This was bothering me :(
> Fixed typo in customer feedback

- Source/DebugMenuViewController.swift
- Source/OEXConfig.h
- Source/OEXLoginViewController.m
- Source/OEXLoginViewController.storyboard
- Source/OEXRearTableViewController.swift
- Source/en.lproj/Localizable.strings
https://openedx.atlassian.net/browse/MA-2031
> Show version on login screen when not on prod

- Source/OEXAppDelegate.m
- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXFileUtility.h
- Source/OEXFileUtility.m
- Source/OEXInterface+Swift.swift
- Source/OEXInterface.h
- Source/OEXInterface.m
- Source/OEXRearTableViewController.swift
- Source/OEXRouter+Swift.swift
- Source/ServerChangedChecker.swift
- Test/OEXFileUtility+TestAdditions.h
- Test/OEXFileUtility+TestAdditions.m
- Test/OEXFileUtilityTests.m
- Test/OEXMockUserDefaults.h
- Test/OEXMockUserDefaults.m
- Test/ServerChangedCheckerTests.swift
- Test/TestEnvironmentBuilder.swift
- Test/edXTests-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
This is prep for logging out when running end to end tests + a little
cleanup.
> Simplify log out logic in app delegate.

- Source/DiscussionNewCommentViewController.swift
- Source/OEXStyles+Swift.swift
https://openedx.atlassian.net/browse/MA-2086
> Remove green border for Endorsed Responses/Answers

- Source/DiscussionCommentsViewController.swift
https://openedx.atlassian.net/browse/MA-2145
> changing color of report icon if comment reported

- Source/PostTableViewCell.swift
https://openedx.atlassian.net/browse/MA-2145
> App is showing 'By Anonymous' for every post a user creates

- Source/DiscussionTopicsViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
https://openedx.atlassian.net/browse/MA-1867
> searched text string not updated in search bar

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXRouter+Swift.swift
https://openedx.atlassian.net/browse/MA-1975?
> App do not update comments count on comment and discussion post screens

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/PostsViewController.swift
Android is sending response_id instead of comment_id so change comment_id with response_id
https://openedx.atlassian.net/browse/MA-2160
> Fix analytics issues. 

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
https://openedx.atlassian.net/browse/MA-2162
>  Forums sorting issues

- Source/SessionUsernameProvider.swift
- Test/SessionUsernameProviderTests.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-2209
> Fix issue where offline cache was borked

- Source/OEXRegistrationAgreementController.m
- Source/OEXRegistrationFieldCheckBoxController.m
- Source/OEXRegistrationFieldCheckBoxView.h
- Source/OEXRegistrationFieldCheckBoxView.m
- Source/OEXRegistrationFieldController.h
- Source/OEXRegistrationFieldControllerFactory.m
- Source/OEXRegistrationFieldEmailController.m
- Source/OEXRegistrationFieldPasswordController.m
- Source/OEXRegistrationFieldSelectController.m
- Source/OEXRegistrationFieldTextAreaController.m
- Source/OEXRegistrationFieldTextAreaView.h
- Source/OEXRegistrationFieldTextAreaView.m
- Source/OEXRegistrationFieldTextController.m
- Source/OEXRegistrationViewController.m
- Source/OEXRegistrationViewController.xib
- Source/RegistrationFieldSelectView.swift
- Test/EndToEnd/Code/FeatureTestCase.swift
- Test/EndToEnd/Code/LoginFeatureTestCase.swift
- Test/EndToEnd/Code/LoginScreenInteractor.swift
- Test/EndToEnd/Code/RegisterFeatureTestCase.swift
- Test/EndToEnd/Code/RegistrationScreenInteractor.swift
- Test/EndToEnd/Code/SplashScreenInteractor.swift
- Test/EndToEnd/Code/TestCredentials.swift
- Test/EndToEnd/Code/XCUIElement+Helpers.swift
- edX.xcodeproj/project.pbxproj
JIRA: https://openedx.atlassian.net/browse/MA-2109
> Add registration end to end test

- Source/OEXConfig+AppFeatures.swift
JIRA: https://openedx.atlassian.net/browse/MA-1669
> Add flag for badging.

- .travis.yml
- Libraries/Alamofire/Alamofire.swift
- Libraries/SnapKit/Source/View+SnapKit.swift
- Libraries/SwiftyJSON/Source/SwiftyJSON.swift
- Libraries/TZStackView/TZStackView.swift
- Source/ContentInsetsController.swift
- Source/Core/Code/Array+Functional.swift
- Source/Core/Code/Logger.swift
- Source/Core/Code/NetworkManager.swift
- Source/Core/Test/Code/Result+Assertions.swift
- Source/CropViewController.swift
- Source/DebugLogViewController.swift
- Source/JSONFormBuilder.swift
- Source/NSAttributedString+Combination.swift
- Source/NSNotificationCenter+SafeSwift.swift
- Source/OEXCheckBox.swift
- Source/OEXRearTableViewController.swift
- Source/PaginatedFeed.swift
- Source/Paginator.swift
- Source/RawStringExtractable.swift
- Source/UIGestureRecognizer+BlockActions.swift
- Test/CourseCatalogDetailViewControllerTests.swift
- Test/CourseDataManagerTests.swift
- Test/EndToEnd/Code/FeatureTestCase.swift
- Test/SnapshotTestCase.swift
- Test/edXTests-Bridging-Header.h
- script/Localizations.swift
Fixes all new compiler warnings and errors and one super weird crash that's clearly a
compiler bug.
> Support for xcode73

- README.rst
> Mention server requirements in README

- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
https://openedx.atlassian.net/browse/MA-2248
> parenthesized author label

- Source/PostsViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2277
> Adding loading spinner on sorting and filtering

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DiscussionTopicsViewController.swift
- Source/MenuOptionsViewController.swift
- Source/OEXLoginSplashViewController.m
- Source/OEXLoginViewController.m
- Source/OEXPlaceholderTextView.m
- Source/OEXRegistrationViewController.m
- Source/PostsViewController.swift
Enabling landscape mode for Discussions.
Jira: https://openedx.atlassian.net/browse/MA-2316
Disabling landscape for splash, login and registration
Jira: https://openedx.atlassian.net/browse/MA-2324
> Enabling landscape mode for Discussions.

- Source/DiscussionResponsesViewController.swift
- Test/DiscussionResponsesViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
Jira: https://openedx.atlassian.net/browse/MA-2214
> Count is not increasing on adding response

- Source/PostTableViewCell.swift
Jira: https://openedx.atlassian.net/browse/MA-2002
> Discrepancies - Web - Mobile

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionHelper.swift
- Source/DiscussionNewCommentViewController.xib
- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/NSAttributedString+Combination.swift
Jira: https://openedx.atlassian.net/browse/MA-2267
> Discussions - Tappable whole author label

- default_config/config.yaml
> Removed course_enrollment from default config

- LoginApi.swift
- Source/Core/Code/NetworkManager.swift
- Source/Core/Code/Result.swift
- Source/Core/Test/Code/NetworkManagerTests.swift
- Source/NetworkManager+Authenticators.swift
- Source/NetworkManager+StandardInterceptors.swift
- Source/OEXAccessToken.h
- Source/OEXAccessToken.m
- Source/OEXEnvironment.m
- Test/NetworkManager+AuthenticatorTests.swift
- Test/NetworkManager+InterceptionTests.swift
- edX.xcodeproj/project.pbxproj
Addresses https://openedx.atlassian.net/browse/MA-1772
@mikekatz @aleffert Pleez Review. Tests will come later, I've had enough iOS for the time being. I am going to reward my brain by reviewing some android.
> MA-1772 Refresh access token on 401

- Source/MenuOptionsViewController.swift
- Source/PostsViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2332
> Separator lines are breaking in landscape mode.

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2440
> Removing thread details GET call in favor of PATCH

- Test/NetworkManager+AuthenticatorTests.swift
Fixes test that was not updated in https://github.com/edx/edx-app-ios/pull/742
> Fixed broken test

- Source/PostsViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2487
> Discussion Load Posts

- Source/CourseOutline.swift
- Source/OEXConfig+AppFeatures.swift
Using DISCUSSIONS_ENABLED for inline discussions as well.
Jira: https://openedx.atlassian.net/browse/MA-2521
> Inline discussions Flag

- Source/DiscussionNewPostViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2457
> Hide keyboard on Topics Apearance

- Source/OEXExternalAuthOptionsView.m
- Source/OEXLoginViewController.storyboard
Jira: https://openedx.atlassian.net/browse/MA-2549
> Sign In Screen UI Fixes

- Source/DiscussionHelper.swift
- Source/LoadStateViewController.swift
- Source/en.lproj/Localizable.strings
Jira: https://openedx.atlassian.net/browse/MA-2415
> Adding Unknown error

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2278
> Discussions: Show added Response/Comment

- Source/DiscussionNewPostViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2178
> DiscussionPosts removing silent refresh.

- Source/OEXDBManager.m
- Source/OEXFileUtility.h
- Source/OEXFileUtility.m
- Source/OEXRearTableViewController.swift
- Source/OEXStorageInterface.h
- Test/OEXFileUtilityTests.m
- Test/SessionUsernameProviderTests.swift
Jira: https://openedx.atlassian.net/browse/MA-2594
> Cleanup all user data on logout

- Source/Main.storyboard
- Source/OEXRearTableViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2289
> Issues in left navigation drawer

- Source/PaginationController.swift
- Test/PaginationControllerTests.swift
Jira: https://openedx.atlassian.net/browse/MA-2090
> Modify Pagination Loader

- Source/registration.json
@saeedbashir @danialzahid94 
https://openedx.atlassian.net/browse/MA-2399
> Remove mailing address field from registration

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/OEXTextStyle.h
- Source/OEXTextStyle.m
- Source/UIColor+OEXHex.h
- Source/UIColor+OEXHex.m
- Test/OEXTextStyleTests.swift
Jira: https://openedx.atlassian.net/browse/MA-2560
> Markdown link recognition for Discussion Responses

- Source/AppUpgradeConfig.swift
- Source/Core/Code/OEXConfig.h
- Source/Core/Code/OEXConfig.m
- Source/IconMessageView.swift
- Source/SnackbarViews.swift
- Test/AppUpgradeConfigTests.swift
- edX.xcodeproj/project.pbxproj
Update config field name of IOS_APP_STORE_URL
Jira: https://openedx.atlassian.net/browse/MA-2687
> Update config field name

- Source/StartupViewController.swift
Jira: https://openedx.atlassian.net/browse/MA-2703
> Disable landscape orientation for startup screen

- LogoutApi.swift
- Source/OEXRouter+Swift.swift
- edX.xcodeproj/project.pbxproj
Jira:  https://openedx.atlassian.net/browse/MA-2512
> Invalidate token on logout

- PULL_REQUEST_TEMPLATE
https://help.github.com/articles/helping-people-contribute-to-your-project/
@saeedbashir @danialzahid94 FYI
> Added file to pre-populated PR template

- Source/OEXLoginViewController.m
- Source/OEXLoginViewController.storyboard
- Source/OEXRouter.m
Jira: https://openedx.atlassian.net/browse/MA-2343
> Accessibility Removing moc Navbar

- Source/OEXCourseInfoViewController+Swift.swift
- Source/OEXCourseInfoViewController.h
- Source/OEXCourseInfoViewController.m
- Source/edX-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
[MA-2760](https://openedx.atlassian.net/browse/MA-2760)
WebView Find Courses was not refreshing expired tokens on enroll.
@BenjiLee  Please ask devops to expire token and check either its working or not.
> Using new NetworkManager for Course Enrollment

- Source/ButtonStyle.swift
- Source/OEXFlowErrorViewController.m
- Source/OEXLoginViewController.m
- Source/OEXLoginViewController.storyboard
- Source/OEXStyles+Swift.swift
- Source/en.lproj/Localizable.strings
[MA-2341](https://openedx.atlassian.net/browse/MA-2341)
[MA-2342](https://openedx.atlassian.net/browse/MA-2342)
[MA-2344](https://openedx.atlassian.net/browse/MA-2344)
[MA-2736](https://openedx.atlassian.net/browse/MA-2736)
[MA-2310](https://openedx.atlassian.net/browse/MA-2310)
Addressing accessibility issues of sign in screen. This PR includes fixes for accessibility traits, valid accessibility labels, and accessibility logical focus.
> Sign in Screen Accessibility 

- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
[MA-2352](https://openedx.atlassian.net/browse/MA-2352)
> AccessibilityLabel for Menu

- Source/CourseCardView.swift
- Source/CoursesTableViewController.swift
- Source/Main.storyboard
- Source/OEXRearTableViewController.swift
- Source/RevealViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2361](https://openedx.atlassian.net/browse/MA-2361)
[MA-2348](https://openedx.atlassian.net/browse/MA-2348)
[MA-2346](https://openedx.atlassian.net/browse/MA-2346)
> Menu Accessibility Logical Flow

- Source/en.lproj/Localizable.strings
[MA-2310](https://openedx.atlassian.net/browse/MA-2310)
> Text captilization

- Source/Core/Code/OEXConfig.h
- Source/Core/Code/OEXConfig.m
- Source/OEXConfig+AppFeatures.swift
- Source/OEXLoginViewController.h
- Source/OEXLoginViewController.m
- Source/OEXRouter+Swift.swift
- Source/OEXRouter.h
- Source/OEXRouter.m
- Test/OEXRouterTests.swift
[MA-2907](https://openedx.atlassian.net/browse/MA-2907)
If course discovery is disabled then it will disable registration process as well.
> Skip to SignIn if Registration Disabled.

- Source/OEXLoginViewController.m
- Source/StartupViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2782](https://openedx.atlassian.net/browse/MA-2782)
[MA-2785](https://openedx.atlassian.net/browse/MA-2785)
I have also updated localize string for Youtube message. (MA-2814)
> Startup Screens Accessibility

- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
[MA-2726](https://openedx.atlassian.net/browse/MA-2726)
@BenjiLee I have also fixed truncation of terms and honor code at register screen for longer platform name.
> Register Screen Honor Code Traits.

- Source/JSONFormBuilder.swift
- Source/JSONFormBuilderTextEditor.swift
- Source/OEXRegistrationViewController.m
- Source/UserProfileEditViewController.swift
- Source/en.lproj/Localizable.strings
- Source/en.lproj/profiles.json
[MA-2886](https://openedx.atlassian.net/browse/MA-2886)
Make some strings open edx friendly
> Make some strings open edx friendly

- PULL_REQUEST_TEMPLATE
FYI @saeedbashir @danialzahid94 
Related to https://github.com/edx/edx-app-android/pull/855
> Update PR template

- Source/OEXLoginViewController.storyboard
Forgot to update one of the assets from. In particular, forgot to update the reference to the login screen image. 
https://github.com/edx/edx-app-ios/pull/811
- FYI @saeedbashir @danialzahid94
> Update login screen image

- Source/Core/Code/OEXConfig.h
- Source/Core/Code/OEXConfig.m
- Source/CourseCatalogAPI.swift
- Source/CourseCatalogViewController.swift
- Source/CoursesAPI.swift
- Source/EnrollmentManager.swift
- Source/OEXEnvironment.m
- Test/EnrollmentManagerTests.swift
- Test/MockEnrollmentManager.swift
- Test/TestRouterEnvironment.swift
[OSPR-1511](https://openedx.atlassian.net/browse/OSPR-1511)
Added ORGANIZATION_CODE flag in custom config files and logic to filter displayed courses and enrollments respectively.
[This is the pull request for the Android version](https://github.com/edx/edx-app-android/pull/829)
- The app is not dependant on this flag.
- 3th time the charm?
If you've been tagged for review, please check your corresponding box once you've given the 👍
> Filter enrollments/courses by organization code

- .travis.yml
- Source/edX-Info.plist
[MA-2730](https://openedx.atlassian.net/browse/MA-2730)
Added Icon File to edx-Info.plist so the app icon can be shown on the XCode target.
- Code review: @saeedbashir
> Add app icon to XCode target

- Source/EnrolledCoursesViewController.swift
- Source/SnackbarViews.swift
[MA-2849](https://openedx.atlassian.net/browse/MA-2849)
- Code review: @danialzahid94 , @BenjiLee
> Show Version App Upgrade SnackBar once

- Source/OEXMyVideosSubSectionViewController.m
[MA-2965](https://openedx.atlassian.net/browse/MA-2965)
> All Videos showing empty list

- Source/edX-Info.plist
- edX.xcodeproj/project.pbxproj
[OSPR-1547 ](https://openedx.atlassian.net/browse/OSPR-1547 )
Added the references to Icon-40.png, Icon-76.png, Icon-76@2x.png as they are in Info.plist but were not inside the Xcode project (but they were inside the repo), so just add the target to the project.
> Add references to Icon-40.png Icon-76.png Icon-76@2x.png

- Source/DiscussionHelper.swift
- Source/DiscussionNewCommentViewController.xib
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionNewPostViewController.xib
- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/Main.storyboard
- Source/OEXDownloadViewController.storyboard
- Source/OEXLoginViewController.m
- Source/OEXLoginViewController.storyboard
- Source/OEXMySettingsViewController.xib
- Source/OEXMyVideosSubSectionViewController.storyboard
- Source/OEXMyVideosViewController.storyboard
- Source/OEXPlaceholderTextView.m
- Source/OEXRegistrationViewController.xib
- Source/OEXUserLicenseAgreementViewController.xib
- Source/en.lproj/Localizable.strings
[MA-2774](https://openedx.atlassian.net/browse/MA-2774)
[MA-2949](https://openedx.atlassian.net/browse/MA-2949)
> Update All Storyboards and Nibs to iPhone 6s

- Source/OEXLoginViewController.h
- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
[OSPR-1569](https://openedx.atlassian.net/browse/OSPR-1569)
Changing the use of OEXStyles to RouterEnvironment to style the buttons in Login and Registration controller similar to this [PR](https://github.com/edx/edx-app-ios/pull/847)
> Use RouterEnvironment instead of the singleton OEXStyles

- Source/OEXMyVideosSubSectionViewController.m
[MA-2996](https://openedx.atlassian.net/browse/MA-2996)
> Selecting All Videos in My Videos

- Source/OEXFonts.swift
- Source/OEXFontsDataFactory.swift
- Source/OEXStyles.m
- Source/Resources/Fonts/fonts.json
- Source/edX-Info.plist
- Test/OEXFontsTests.swift
- edX.xcodeproj/project.pbxproj
- edX.xcworkspace/xcshareddata/edX.xcscmblueprint
[OSPR-1555 ](https://openedx.atlassian.net/browse/OSPR-1555 )
Like colors are setup using colors.json this PR makes possible to setup fonts using fonts.json
> Use json to setup fonts

- Source/DiscussionNewPostViewController.swift
- Source/MenuOptionsViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2962](https://openedx.atlassian.net/browse/MA-2962)
> VO Description For Create New Post Screen

- Source/OEXCourseVideosTableViewCell.m
- Source/OEXDownloadTableCell.m
- Source/OEXDownloadViewController.h
- Source/OEXDownloadViewController.m
- Source/OEXDownloadViewController.storyboard
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXRouter.m
> Revert "Reduce user confusion when looking at video downloads"

- Source/Core/Test/Code/RegistrationAPITests.swift
Update test printout to check for optional.
Run tests.
If you've been tagged for review, please "Start a review" with the Github GUI.
> Test should not print optional string

- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2799](https://openedx.atlassian.net/browse/MA-2799)
> Discussion Posts List Screen Accessibility

- Source/VideoBlockViewController.swift
- edX.xcodeproj/xcshareddata/xcschemes/edX.xcscheme
[OSPR-1600](https://openedx.atlassian.net/browse/OSPR-1600)
This PR fixes a problem with the constraints not getting updated when changing orientation while seeing a video. See attach image.
> Fix video block constraints

- Source/CourseDashboardViewController.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/OEXCourse+TestData.swift
[OSPR-1609](https://openedx.atlassian.net/browse/OSPR-1609)
This PR shows or hide the handouts tab depending if its available or not.
> Show or hide handouts tab depending if its available or not

- PULL_REQUEST_TEMPLATE
@saeedbashir  @danialzahid94  FYI
> Update Pull Request template to reflect new review feature on github

- .gitignore
@saeedbashir @danialzahid94 FYI
> Added *.xcscmblueprint to gitignore

- Source/CutomePlayer/CLVideoPlayerControls.m
[MA-3060](https://openedx.atlassian.net/browse/MA-3060)
Before/After: (icon on bottom right)
> MA-3060 Removed Open in Browser button in the video player

- Source/FirebaseAnalyticsTracker.swift
[MA-3072](https://openedx.atlassian.net/browse/MA-3072)
> Skipping 'label' and 'category' for Firebase Analytics

- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/OEXRegistrationViewController.m
[MA-3075](https://openedx.atlassian.net/browse/MA-3075)
https://openedx.atlassian.net/wiki/display/MA/Updates+to+Mobile+App+events
> Add Register Event

- Source/OEXAnalytics.m
Fixed fullscreen event value for name
> Fixed fullscreen event value for name

- Source/OEXInterface.h
- Source/OEXInterface.m
[MA-3099](https://openedx.atlassian.net/browse/MA-3099)
Storing app version to user defaults so we can use it for Timely App Reviews or for Whats New.
> Store the App Versions in User Preferences

- Source/CropViewController.swift
- Source/UIImage+OEXHelpers.swift
- Test/UIImage_OEXHelpersTests.swift
- edX.xcodeproj/project.pbxproj
[MA-2986](https://openedx.atlassian.net/browse/MA-2986)
> Picture Resizing

- Source/CourseUnknownBlockViewController.swift
- Source/FirebaseAnalyticsTracker.swift
- Source/OEXEnvironment.m
- Source/SegmentAnalyticsTracker.swift
[MA-3102](https://openedx.atlassian.net/browse/MA-3102)
> Firebase Analytics should not depend on Segment

- Source/OEXRearTableViewController.swift
- Source/en.lproj/Localizable.strings
[MA-3131](https://openedx.atlassian.net/browse/MA-3131)
> Profile Accessibility in Left Drawer

- Libraries/Alamofire/Alamofire.swift
- Source/OEXAuthentication.m
- Source/OEXLoginViewController.m
- Source/en.lproj/Localizable.strings
[MA-2937](https://openedx.atlassian.net/browse/MA-2937)
> Send User-Agent in LoginApi

- Source/CourseOutlineTableSource.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXRouter+Swift.swift
- Source/OEXVideoSummary.h
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[MA-3157](https://openedx.atlassian.net/browse/MA-3157)
> Improved video logic for courses with non-mobile videos

- Source/CourseContentPageViewController.swift
- Source/CutomePlayer/CLVideoPlayer.m
- Source/CutomePlayer/CLVideoPlayerControls.h
- Source/CutomePlayer/CLVideoPlayerControls.m
- Source/OEXConstants.h
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXVideoPlayerInterface.m
- Source/VideoBlockViewController.swift
[MA-2991](https://openedx.atlassian.net/browse/MA-2991)
This PR adds the functionality to automatically run the video in full screen when the device is in landscape mode. It also adds a left and right button, and swipe gestures in full screen mode for users to be able to navigate to the next or previous units.
> Enable auto fullscreen for videos

- Source/OEXAnalytics+AppReview.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/OEXInterface+AppReview.swift
- Source/RatingViewController.swift
- Source/edX-Info.plist
- Test/OEXInterface+AppReviewTests.swift
- Test/RatingViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
[MA-3160](https://openedx.atlassian.net/browse/MA-3160)
[MA-3178](https://openedx.atlassian.net/browse/MA-3178)
This PR integrates analytics for app reviews.
> App Review Analytics

- Source/CourseOutlineItemView.swift
- Source/Icon.swift
[MA-2543](https://openedx.atlassian.net/browse/MA-2543)
> Wrong Graded Icon Showing in Mobile Courseware

- Source/EnrolledCoursesViewController.swift
[MA-2413](https://openedx.atlassian.net/browse/MA-2413)
This PR hides redundant errors on My Courses Screen.
> Redundant Offline Errors.

- Source/OEXRouter+Swift.swift
- Source/RatingContainerView.swift
- Source/RatingView.swift
- Source/RatingViewController.swift
- Source/VideoBlockViewController.swift
- Source/en.lproj/Localizable.strings
[LEARNER-124](https://openedx.atlassian.net/browse/LEARNER-124)
This PR implements accessibility for the App Reviews feature.
> Accessibility for App Reviews

- Source/DiscussionAPI.swift
- Source/DiscussionResponsesDataController.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
[MA-2762](https://openedx.atlassian.net/browse/MA-2762)
We were getting user profile information in GET API calls for discussions. So we are using that available user profile information for PATCH and POST API calls.
> Using Available User Profile Information in Discussions

- Source/CourseContentPageViewController.swift
- Source/RatingContainerView.swift
- Source/RatingViewController.swift
- Source/VideoBlockViewController.swift
[LEARNER-124](https://openedx.atlassian.net/browse/LEARNER-124)
Go to a video unit of any course. Complete a video and wait for Timely App Reviews popup. When popup appears then turned on Voice Over. Only popup elements should be accessible in Voice over.
> Timely App Reviews Accessibility Approvements.

- Source/CutomePlayer/CLVideoPlayer.h
- Source/CutomePlayer/CLVideoPlayer.m
- Source/OEXVideoPlayerInterface.m
[LEARNER-424](https://openedx.atlassian.net/browse/LEARNER-424)
Go to any video block that have transcript. After loading transcript, navigate back and come to again video block. Repeat this process multiple times. Transcript should load every time.
> Video transcripts in do not appear sometimes

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
[MA-2762](https://openedx.atlassian.net/browse/MA-2762)
> Use LoggedIn User Details for New Response/Comment

- Source/CourseSectionTableViewCell.swift
[LEARNER-423](https://openedx.atlassian.net/browse/LEARNER-423)
> Retaining Video Downloading Spinner State Across Screens

- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogDetailViewController.swift
[LEARNER-1181](https://openedx.atlassian.net/browse/LEARNER-1181)
Course enrolment is not working after updating swift 3.0
- In menu open "Find Courses"
- Go into any course
- Tap on "Enroll Now"
- Course should be enroll successfully.
> LEARNER-1181, course enrolment is not working after updating swift 3.0

- Source/OEXAnalytics+Swift.swift
- Source/WhatsNewDataModel.swift
- Source/WhatsNewViewController.swift
[LEARNER-1165](https://openedx.atlassian.net/browse/LEARNER-1165)
> WhatsNew Feature Analytics

- Source/OEXConfig+AppFeatures.swift
- Source/OEXRearTableViewController.swift
[LEARNER-1291](https://openedx.atlassian.net/browse/LEARNER-1291)
> My Videos Behind Feature Flag & Course Videos Flag

- Source/en.lproj/Localizable.strings
[LEARNER-1448](https://openedx.atlassian.net/browse/LEARNER-1448)
> CamelCase Important Dates

- Source/EnrolledCoursesViewController.swift
[LEARNER-781](https://openedx.atlassian.net/browse/LEARNER-781)
> Patch For Connection Intermittent Warning

- Source/CropViewController.swift
- Source/UserProfileViewController.swift
[LEARNER-1447](https://openedx.atlassian.net/browse/LEARNER-1447)
> Full Screen Error Message for User Profile

- Source/OEXInterface+AppReview.swift
- Source/OEXInterface+WhatsNew.swift
- Source/RatingViewController.swift
- Source/VersionParser.swift
- Source/WhatsNewViewController.swift
- Source/en.lproj/Localizable.strings
- Test/OEXInterface+AppReviewTests.swift
- Test/VersionParserTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-1777](https://openedx.atlassian.net/browse/LEARNER-1777)
> Version Parser for BuildVesionString

- .tx/config
- Source/JSONFormBuilder.swift
- Source/en.lproj/InfoPlist.strings
- Source/en.lproj/Localizable.strings
- Source/en.lproj/profiles.json
- edX.xcodeproj/project.pbxproj
[LEARNER-1587](https://openedx.atlassian.net/browse/LEARNER-1587)
> User Profile Localization

- Source/EnrolledCoursesViewController.swift
[LEARNER-781](https://openedx.atlassian.net/browse/LEARNER-781)
> Intermittent Connection Warning Patch 

- .gitignore
- README.rst
- script/whitelabel.py
Adds a script called `whitelabel.py` which applies a list of customizations to the app source.
We keep our customizations in a secure repo, because they contain the API key for the LMS.
**JIRA tickets**: [OSPR-1831](https://openedx.atlassian.net/browse/OSPR-1831)
**Discussions**: This change provides one step in the approach laid out in the [edX Mobile Whitelabel Strategy](https://openedx.atlassian.net/wiki/display/MA/Whitelabel+Strategy) document.
**Partner information**: 3rd party hosted Open edX instance
**Merge deadline**: None
1. See this branch's `README.rst` for instructions on how to use the new `whitelabel.py` script.  These instructions also need testing, so they're not repeated here.
1. Build and run the updated app to ensure that the customizations you configured made it into …
> Adds script to apply whitelabel settings and resources

- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CourseSectionTableViewCell.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-2157](https://openedx.atlassian.net/browse/LEARNER-2157)
> Course videos analytics

- DateFormatting.swift
- Source/CourseOutlineItemView.swift
[LEARNER-300](https://openedx.atlassian.net/browse/LEARNER-300)
Fix for the date formatting issue, The date was showing as today due date even for future dates.
> LEARNER-300, fix for date comparison and remove conflicts

- Source/EnrolledCoursesViewController.swift
[LEARNER-2212](https://openedx.atlassian.net/browse/LEARNER-2212)
> Combine 'My Courses' and 'Find Courses' experiences

- DateFormatting.swift
- Source/CourseOutlineItemView.swift
[LEARNER-300](https://openedx.atlassian.net/browse/LEARNER-300)
Timezone abbreviation is not showing when we change it from device setting.
> Timezone abbreviation issue

- Source/EnrollmentConfig.swift
- Source/Main.storyboard
- Source/OEXCourseInfoViewController.m
- Source/OEXFindCoursesViewController.m
- Source/OEXRearTableViewController.swift
- Source/OEXRouter+Swift.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-2362](https://openedx.atlassian.net/browse/LEARNER-2362)
> 'Discover' in left navigation drawer

- .travis.yml
- Source/en.lproj/profiles.json
[LEARNER-2368](https://openedx.atlassian.net/browse/LEARNER-2368)
> WIP: Push files to transifex only from master

- .travis.yml
- Source/en.lproj/profiles.json
> Revert "WIP: Push files to transifex only from master"

- .travis.yml
[LEARNER-2368](https://openedx.atlassian.net/browse/LEARNER-2368)
Travis was pushing localized files to transifex on every commit to any feature branch when pull request exists for that feature branch. But, now on travis will only push files to transifex when any feature branch merged into master or if any commit directly made to master.
I have also disabled "Build pull request updates" to achieve the desired behavior.
> Push files to transifex only from master

- Source/DownloadsAccessoryView.swift
- Source/Icon.swift
[LEARNER-2523](https://openedx.atlassian.net/browse/LEARNER-2523)
Update download icon
> Update download icon

- Source/CourseDashboardViewController.swift
- Source/CutomePlayer/CLVideoPlayerControls.m
- Source/PostsViewController.swift
- Source/UserProfileEditViewController.swift
[LEARNER-2356](https://openedx.atlassian.net/browse/LEARNER-2356)
1) App crashes when user tap on 'Change' button on edit profile screen.
2) App crashes on tapping 'Share a course' icon on course dashboard.
3) App crashes when user tap on any of sorting and filtering dropdowns in discussions.
4) App crashes when user tap on 'Closed Captions' and 'Video Speed' from setting icon in video player controls.
> Tablet support crashes fix

- Source/OEXVideoPlayerInterface.m
- Source/UIViewController+CommonAdditions.swift
- Source/VideoBlockViewController.swift
[LEARNER-2358](https://openedx.atlassian.net/browse/LEARNER-2358)
> VideoPlayer Support added for iPad

- Source/EnrolledCoursesViewController.swift
[LEARNER-781](https://openedx.atlassian.net/browse/LEARNER-781)
> Patch for Intermittent connection warning on app launch

- Source/WhatsNewViewController.swift
[LEARNER-2491](https://openedx.atlassian.net/browse/LEARNER-2491)
- What's New - 'Done' button should not appears on every screen
> Done Button should appear on last screen of whatsnew

- Source/VersionParser.swift
- Source/WhatsNewDataModel.swift
- Source/WhatsNewObject.swift
- Source/WhatsNewViewController.swift
- Source/en.lproj/whats_new.json
- Source/es-419.lproj/whats_new.json
- Test/VersionParserTests.swift
- Test/WhatsNew.json
- Test/WhatsNewDataModelTests.swift
- Test/WhatsNewObjectTests.swift
- Test/WhatsNewViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-2527](https://openedx.atlassian.net/browse/LEARNER-2527)
> WhatsNew file with support of multiple version strings

- Source/WhatsNewViewController.swift
[LEARNER-2491](https://openedx.atlassian.net/browse/LEARNER-2491)
Fix the done button issue in WhatsNew
> Fix the done button issue in WhatsNew

- Source/OEXAppDelegate.m
[LEARNER-2626](https://openedx.atlassian.net/browse/LEARNER-2626)
> Check either Branch is enabled or not before usage

- Source/Swipeable Cell/SwipeableCell.swift
[LEARNER-2692](https://openedx.atlassian.net/browse/LEARNER-2692)
Fix the touch and swipe to delete issue on iOS11
> Fix the touch issue on iOS-11

- Source/OEXDBManager.m
- Source/OEXDownloadManager.m
[LEARNER-504](https://openedx.atlassian.net/browse/LEARNER-504)
> Add crashlytics logs to find the cause of core data crash LEARNER-504

- Source/OEXAppDelegate.m
[LEARNER-2847](https://openedx.atlassian.net/browse/LEARNER-2847)
> User is unable to login through Facebook/Google

- Source/CourseDashboardViewController.swift
[LEARNER-2873](https://openedx.atlassian.net/browse/LEARNER-2873)
> Course Dashboard - Scrolling gets disabled sometimes

- Source/OEXDownloadViewController.m
- Source/OEXDownloadViewController.storyboard
[LEARNER-2737](https://openedx.atlassian.net/browse/LEARNER-2737)
Downloads - Showing unexpected information if there is no size and duration of any video.
> Downloads - Showing unexpected information if there is no size and duration of any video.

- Source/AnswerAnalyticsTracker.swift
- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogDetailViewController.swift
- Source/OEXCourseInfoViewController+Swift.swift
[LEARNER-2628](https://openedx.atlassian.net/browse/LEARNER-2628)
Fix the find course enroll course analytics in webview case.
> Fix the find course enroll course analytics in webview case

- Source/AuthenticatedWebViewController.swift
- Source/CourseDatesViewController.swift
[LEARNER-2924](https://openedx.atlassian.net/browse/LEARNER-2924)
iOS - Update Course Dates endpoint
> iOS - Update Course Dates endpoint

- Source/OEXDBManager.m
- Source/OEXDownloadManager.m
- Source/OEXDownloadViewController.m
- Source/OEXInterface.m
- Source/OEXNetworkInterface.m
- Source/OEXNetworkManager.m
[LEARNER-504](https://openedx.atlassian.net/browse/LEARNER-504)
I'm not sure, this PR will fix the desired crases or not because underlying crashes are not replicate able at our end. But I'm hopeful it will, and definitely, this will increase the stability of the code. Moreover, this PR remove strong reference to `self` in blocks which would avoid retains cycles. This PR also addresses the issue that sometimes app got stuck in loading on relaunch.
A full regression should be executed on this PR so that we should have surety that these changes are not breaking the app. Because manly the changes are made in the code that is interacting with the database.
> Changes for OEXDBManager Stability to Avoid Crashes

- Source/OEXRegistrationFieldWrapperView.m
- Source/OEXRegistrationViewController.m
- Source/UIAlertController+OEXBlockActions.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-2899](https://openedx.atlassian.net/browse/LEARNER-2899)
> Accessibility flow improvements for missing input

- Source/OEXRegistrationFieldSelectController.m
- Source/OEXRegistrationFieldTextController.m
- Source/OEXRegistrationFormField.h
- Source/OEXRegistrationFormField.m
- Source/OEXRegistrationFormTextField.h
- Source/OEXRegistrationFormTextField.m
- Source/RegistrationFieldSelectView.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-2906](https://openedx.atlassian.net/browse/LEARNER-2906)
> Accessibility Trait for Dropdown

- Source/OEXRegistrationFieldTextAreaView.m
[LEARNER-2905](https://openedx.atlassian.net/browse/LEARNER-2905)
Provide valid labels for all form elements Mobile registration form
> Fix the text area accessibility for register page

- Source/CourseOutlineTableSource.swift
[LEARNER-3386](https://openedx.atlassian.net/browse/LEARNER-3386)
> Uniform course card image on course outline

- edX.entitlements
- edX.xcodeproj/project.pbxproj
[LEARNER-3479](https://openedx.atlassian.net/browse/LEARNER-3479)
>  Associated Domains added for Journeys App Banners

- .codecov.yml
- Source/CourseAnnouncementsViewController.swift
- Source/CourseDashboardTabBarViewController.swift
- Source/CourseDatesViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/EnrolledCoursesViewController.swift
- Source/EnrolledTabBarViewController.swift
[LEARNER-3383](https://openedx.atlassian.net/browse/LEARNER-3383)
> Landscape support for course dashboard with new tabs layout

- Source/WhatsNewDataModel.swift
- Source/WhatsNewObject.swift
- Source/WhatsNewViewController.swift
- Test/WhatsNew.json
- Test/WhatsNewDataModelTests.swift
[LEARNER-3567](https://openedx.atlassian.net/browse/LEARNER-3567)
1. Done button should be visible only on last page. 
2. Done button should be hidden on first whats new item when loads first time. 
3. If whats new item has more then one item, It should not be cyclic.
> iOS - What's New is Cyclic in case of more than one screen.

- Source/CourseOutlineTableSource.swift
- Source/EnrolledTabBarViewController.swift
[LEARNER-3863](https://openedx.atlassian.net/browse/LEARNER-3863)
> Course card and last access is not appearing properly on course content screen with new tab bar design.

- Source/OEXStyles+Swift.swift
[LEARNER-3872](https://openedx.atlassian.net/browse/LEARNER-3872)
> Download Spiral TintColor with new app color scheme

- Source/DiscussionResponsesViewController.swift
[LEARNER-2609](https://openedx.atlassian.net/browse/LEARNER-2609)
iOS - DiscussionResponsesViewController.swift line 776 [Crashlytics]
> iOS - DiscussionResponsesViewController.swift line 776 [Crashlytics]

- Source/CourseOutlineTableSource.swift
[LEARNER-4145](https://openedx.atlassian.net/browse/LEARNER-4145)
> Pull to Refresh not working issue fixed

- Source/OEXCourseInfoViewController.m
- Source/OEXRouter+Swift.swift
- Source/UIViewController+CommonAdditions.swift
[LEARNER-4221](https://openedx.atlassian.net/browse/LEARNER-4221)
> iOS: Discover courses is not working from Startup Screen

- Source/CourseContentPageViewController.swift
- Test/CourseContentPageViewControllerTests.swift
[LEARNER-3208](https://openedx.atlassian.net/browse/LEARNER-3208)
Fix the UI Crash with possible solution
> LEARNER-3208, Fix the UI Crash with possible solution

- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
- Source/OEXRouter.m
[LEARNER-4258](https://openedx.atlassian.net/browse/LEARNER-4258)
> Statusbar visibility on Login and Registration screen

- Source/edX-Info.plist
> Release v2.13.3 branch code

- Source/CertificateViewController.swift
- Source/DebugLogViewController.swift
- Source/UserProfileViewController.swift
[LEARNER-4406](https://openedx.atlassian.net/browse/LEARNER-4406)
> Configure UIActivityViewController for iPad in whole App

- Source/AnswerAnalyticsTracker.swift
- Source/CourseDashboardViewController.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXAnalyticsData.h
- Source/OEXAnalyticsData.m
- Source/OEXAnayltics+Certificates.swift
- Source/OEXLoginViewController.m
[LEARNER-4190](https://openedx.atlassian.net/browse/LEARNER-4190)
> Fabric(Answers) Events for: Login & Share

- Source/ShareHelper.swift
[LEARNER-4383](https://openedx.atlassian.net/browse/LEARNER-4383)
> Course share URL is empty for all apps other than facebook and twitter

- Source/CourseCatalogViewController.swift
- Source/CoursesTableViewController.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[OSPR-2285](https://openedx.atlassian.net/browse/OSPR-2285)
This PR show the message ```No available courses``` on the ```Find courses``` section when there are no available courses.
cc @marcotuts
> No available courses on find courses

- Source/OEXConfig+AppFeatures.swift
- Source/OEXVideoEncoding.h
- Source/OEXVideoEncoding.m
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[LEARNER-4758](https://openedx.atlassian.net/browse/LEARNER-4758)
> Use HLS encoding in mobile apps and prioritize it

- Source/AnswerAnalyticsTracker.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-4790](https://openedx.atlassian.net/browse/LEARNER-4790)
>  Flat hierarchy for custom attributes in Answers analytics

- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[LEARNER-5087](https://openedx.atlassian.net/browse/LEARNER-5087)
> Video size is always 0.0 if a downloadable encoding available with HLS

- Source/CourseCatalogDetailViewController.swift
- Source/OEXCourseInfoViewController+Swift.swift
- Source/UIAlertController+OEXBlockActions.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Test/CourseCatalogDetailViewControllerTests.swift
[LEARNER-4930](https://openedx.atlassian.net/browse/LEARNER-4930)
Update enroll button message for professional education courses.
> LEARNER-4930, update enroll button message for professional education courses.

- Source/WhatsNewContentController.swift
- Source/WhatsNewViewController.swift
[LEARNER-5192](https://openedx.atlassian.net/browse/LEARNER-5192)
To test these changes you have to temporarily add landscape support to `EnrolledTabbarController.swift`
> Landscape for WhatsNew screens

- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-4930](https://openedx.atlassian.net/browse/LEARNER-4930)
update enrolment failure message text
> LEARNER-4930, update enrolment failure message text

- Source/CourseCardView.swift
- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogDetailViewController.swift
- Source/CourseCatalogViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/CoursesTableViewController.swift
- Source/EnrolledTabBarViewController.swift
[LEARNER-5153](https://openedx.atlassian.net/browse/LEARNER-5153)
> Landscape support for Course Dashboard & Logged In Discovery

- .travis.yml
- Test/StreamTests.swift
[LEARNER-4341](https://openedx.atlassian.net/browse/LEARNER-4341)
Due to this change, Travis will checkout current master and put all of the changes done in a PR on top of it through a commit and run tests on it. This will be valid for all PRs i.e. internal and externals (OSPRs).
**Note: Following change in Travis's setting has also been done:**
Before | After
--- | ---
> Update Travis config to run builds on all Pull Requests

- Source/edX-Info.plist
[LEARNER-5040](https://openedx.atlassian.net/browse/LEARNER-5040)
I'm not certain either this will fix the crash or not because the crash is not reproducible so I have added these keys on assumption that user may perform any of the tasks by using force touch feature of new iPhones.
> Adding Privacy Keys

- README.rst
Path is Source/Resources ...
[LEARNER-](https://openedx.atlassian.net/browse/LEARNER-)
Change path (Readme) from Sources (Typo) to Source
> Solved Typo

- Source/FindCoursesWebViewHelper.swift
- Source/OEXAnalytics+Swift.swift
- Source/StartupViewController.swift
[LEARNER-4691](https://openedx.atlassian.net/browse/LEARNER-4691)
> Discovery: Course Search Analytics

- Source/CourseContentPageViewController.swift
- Test/CourseContentPageViewControllerTests.swift
[LEARNER-3210](https://openedx.atlassian.net/browse/LEARNER-3210)
Fix for the crash https://fabric.io/edx-inc/ios/apps/org.edx.mobile/issues/56681ff9f5d3a7f76b359603?time=last-seven-days.
The issue is not re-producible so the fix is base on observations and the recommended solutions for this type of crashes.
> iOS - Fix of UIKit crash 

- Source/CutomePlayer/VideoPlayer.swift
[LEARNER-5764](https://openedx.atlassian.net/browse/LEARNER-5764)
Fixed crash during video seeking when player is not in ready state.
> Fixed crash during video seeking when player is not in ready state.

- Source/Registration Field Views/RegistrationFormFieldView.swift
[LEARNER-5727](https://openedx.atlassian.net/browse/LEARNER-5727)
> Tell us why you're interested in edX field input fix

- Source/PostTableViewCell.swift
[LEARNER-5482](https://openedx.atlassian.net/browse/LEARNER-5482)
> Discussion icon on posts screen get cut off

- Source/FirebaseConfig.swift
- Source/OEXAppDelegate.m
- Source/OEXConfig+AppFeatures.swift
- Source/OEXEnvironment.m
- Test/FirebaseConfigTests.swift
- Test/GoogleService-Info.plist
- edX.xcodeproj/project.pbxproj
[LEARNER-6104](https://openedx.atlassian.net/browse/LEARNER-6104)
> New Firebase Configuration for Analytics and Cloud Messaging

- Source/CourseContentPageViewController.swift
[LEARNER-5801](https://openedx.atlassian.net/browse/LEARNER-5801)
I'm not sure this PR will fix the crash or not because the crash is not reproducible, but it will fix an issue that blocked user to interact with course content.
> Course ware content scrolling improvements

- Source/FindCoursesWebViewHelper.swift
[LEARNER-6487](https://openedx.atlassian.net/browse/LEARNER-6487)
> Course discovery is not working properly

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/Deep Linking/QuickLink.swift
- Source/OEXAppDelegate.m
- Test/DeepLinkTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-6444](https://openedx.atlassian.net/browse/LEARNER-6444)
iOS : Implement deep linking for course dashboard
- Add "https://edx.app.link/coursedashboard" in notes, opening this url by clicking will open the app and navigate to course dashboard screen.
> iOS : Implement deep linking for course dashboard

- Source/WebView/ProgramsViewController.swift
[LEARNER-6558](https://openedx.atlassian.net/browse/LEARNER-6558)
> Add silent load to Programs screen

- Source/VideoBlockViewController.swift
- Source/VideoCompletionApi.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-5782](https://openedx.atlassian.net/browse/LEARNER-5782)
> Apps do not read progress for all the mobile accessible courses videos

- build.gradle
- buildSrc/build.gradle
- gradle/wrapper/gradle-wrapper.properties
[LEARNER-6063](https://openedx.atlassian.net/browse/LEARNER-6063)
> Gradle update

- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter.m
- Source/UIAlertController+OEXBlockActions.swift
- Source/UIApplication+UIViewController.swift
- Source/UIViewController+CommonAdditions.swift
- Test/DeepLinkTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-6448](https://openedx.atlassian.net/browse/LEARNER-6448)
implement deep linking for account screen
- Add "https://edx.app.link/account" in notes, opening this url by clicking will open the app and navigate to account screen.
> iOS - implement deep linking for account screen

- Source/AccountViewController.swift
- Source/UserProfileViewController.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6767](https://openedx.atlassian.net/browse/LEARNER-6767)
[LEARNER-6762](https://openedx.atlassian.net/browse/LEARNER-6762)
> Accessibility Improvements for Profile and Close buttons

- Source/UserProfileView.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6765](https://openedx.atlassian.net/browse/LEARNER-6765)
> Accessibilitylabel for bio text on user profile screen

- Source/SubjectsDiscovery/Subjects JSON/en.lproj/subjects.json
- Source/SubjectsDiscovery/Subjects JSON/es-419.lproj/subjects.json
[LEARNER-6737](https://openedx.atlassian.net/browse/LEARNER-6737)
> Fix 'Filter by Subject' issue in 'Course Discovery'

- Source/IconButton.swift
- Source/JSONFormBuilder.swift
- Source/ProfileBanner.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6585](https://openedx.atlassian.net/browse/LEARNER-6585)
[LEARNER-6766](https://openedx.atlassian.net/browse/LEARNER-6766)
> Accessibility improvements of Edit Profile screen

- .travis.yml
- Libraries/Alamofire/Alamofire.swift
- Pods/Pods.xcodeproj/project.pbxproj
- Source/Core/Code/Box.swift
- Source/Core/Code/Logger.swift
- Source/Core/Code/NetworkManager.swift
- Source/Core/Code/PersistentResponseCache.swift
- Source/KeyboardInsetsSource.swift
- Source/OEXAppDelegate.m
- Test/CourseOutlineTestDataFactory.swift
- Test/MockAnalyticsTracker.swift
- edX.xcodeproj/xcshareddata/xcschemes/EndToEndTests.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edX-RTL.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edX.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edXCore.framework.xcscheme
[LEARNER-6387](https://openedx.atlassian.net/browse/LEARNER-6387)
> Xcode 10.1 Support

- Source/OEXUserLicenseAgreementViewController.m
- Source/Resources/Stylesheets/handouts-announcements.css
- Source/en.lproj/MobileAppEula.htm
- Source/en.lproj/PrivacyPolicy.htm
- Source/en.lproj/TermsOfServices.htm
- Source/es-419.lproj/MobileAppEula.htm
- Source/es-419.lproj/PrivacyPolicy.htm
- Source/es-419.lproj/TermsOfServices.htm
- edX.xcodeproj/project.pbxproj
[LEARNER-6731](https://openedx.atlassian.net/browse/LEARNER-6731)
Mobile is using three local HTML files (MobileAppEula.htm, PrivacyPolicy.htm & TermsOfServices.htm), this PR is adding dynamic type support for these files.
- Open Login screen or Create Your Account screen
- Open Licence agreement or Term of services or Privacy Policy, the font should update as per accessibly setting.
> Follow Dynamic Type Text Size Settings for Local HTML Files

- Source/AuthenticatedWebViewController.swift
- Source/WebView/ProgramsViewController.swift
[LEARNER-6551](https://openedx.atlassian.net/browse/LEARNER-6551)
In this PR, Programs can be refresh any time by pull to refresh feature.
- Tap on Program tab
- If the programs are loaded, pull the view downward the loader will appear and the view will start refresh.
> Add pull to refresh on programs

- Source/FirebaseConfig.swift
- Source/OEXAppDelegate.m
- Test/FirebaseConfigTests.swift
[LEARNER-6725](https://openedx.atlassian.net/browse/LEARNER-6725)
Configure the firebase parameters through app config file.
> Configure firebase through config file

- Source/en.lproj/languages.json
- Source/es-419.lproj/languages.json
[LEARNER-6894](https://openedx.atlassian.net/browse/LEARNER-6894)
Format language.josn Properly for Language Interlingue.
> LEARNER-6894, Correct the format of an object in language.json

- Source/edX-Info.plist
> Bumping version to 2.17.1

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscoveryViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXCourseInfoViewController.h
- Source/OEXCourseInfoViewController.m
- Source/OEXRouter+Swift.swift
- Source/StartupViewController.swift
[LEARNER-6449](https://openedx.atlassian.net/browse/LEARNER-6449)
In this PR, i implemented the deep linking for course discovery scree, now by clicking on the quick link of course discovery the app will open up the discovery screen.
Add following links in notes, tap on the url will open the app and navigate to course discovery screen.
Course Discovery Screen: https://edx.app.link/discovery
Course Discovery For Specific Course: https://edx.app.link/discovery_detail
> LEARNER-6449, deep linking for course discovery

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscoveryViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXFindCoursesViewController.h
- Source/OEXRouter+Swift.swift
- Source/ProgramsDiscoveryViewController.swift
[LEARNER-6450](https://openedx.atlassian.net/browse/LEARNER-6450)
In this PR, i implemented the deep linking for program discovery screen, now by clicking on the quick link of program discovery the app will open up the program discovery screen.
Add following links in notes, tap on the url will open the app and navigate to course discovery screen.
Program Discovery Screen: https://edx.app.link/program_discovery
Program Discovery For Specific Course: https://edx.app.link/program_discovery_detail
> iOS - Implement deep linking for program discovery

- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6976](https://openedx.atlassian.net/browse/LEARNER-6976)
Update startup screen message
> Update startup screen message

- openedx.yml
> Revert "Added openedx yml file"

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter+Swift.swift
[LEARNER-6446](https://openedx.atlassian.net/browse/LEARNER-6446)
In this PR, i implemented the deep linking for profile screen, now by clicking on the quick link the app will open up the profile screen.
Add following links in notes, tap on the url will open the app and navigate to profile screen.
Profile Screen Deep Link URL : https://edx.app.link/profile
Wiki Link
https://openedx.atlassian.net/wiki/spaces/LEARNER/pages/855113971/Deep+Linking
> iOS - Deep linking for profile screen

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter+Swift.swift
- Source/WebView/ProgramsViewController.swift
[LEARNER-6447](https://openedx.atlassian.net/browse/LEARNER-6447)
In this PR, i implemented the deep linking for program detail screen, now by clicking on the quick link  the app will open up the program detail screen.
Add following links in notes, tap on the url will open the app and navigate to program detail screen.
Program Detail Screen: https://edx.app.link/program_detail
> iOS - implement deep linking for Program Detail Page

- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscoveryViewController.swift
- Source/OEXRouter+Swift.swift
improve the deep linking experience, opening link on existing view stack
[LEARNER-7153](https://openedx.atlassian.net/browse/LEARNER-7153)
Improve the deep linking experience, opening link on existing view stack.
> iOS - improve the deep linking experience

- Source/CourseCardView.swift
- Source/CourseOutlineHeaderView.swift
- Source/CourseOutlineItemView.swift
- Source/CourseVideosHeaderView.swift
[LEARNER-6796](https://openedx.atlassian.net/browse/LEARNER6796-)
> Add Dynamic Type Support For Course Content Screen & Course List Screen

- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
[LEARNER-7171](https://openedx.atlassian.net/browse/LEARNER-7172)
In this PR, i implemented the deep linking for discussion topic screen, now by clicking on the quick link the app will open up the discussion topic screen.
Notes
Add following links in notes, tap on the url will open the app and navigate to discussion topic screen.
Program Detail Screen: https://edx.app.link/discussion_topic
> iOS - Implement deep linking for discussion topic screen

- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
[LEARNER-7173](https://openedx.atlassian.net/browse/LEARNER-7173)
In this PR, i implemented the deep linking for discussion post screen, now by clicking on the quick link the app will open up the discussion post screen.
Notes
Add following links in notes, tap on the url will open the app and navigate to discussion post screen.
Program Detail Screen: https://edx.app.link/discussion_post
> iOS - implement deep linking for discussion posts screen

- Source/OEXInterface+Swift.swift
- Source/OEXInterface.m
[LEARNER-7214](https://openedx.atlassian.net/browse/LEARNER-7214)
> Stop using legacy course API video_outline

- README.rst
- Title added to the front page of our repo
- Adds a nice little Travis build status on the front page showing the Travis build's status on the repo's `master` branch.
> Add repo title and build passing badge

- Source/AgreementTextView.swift
- Source/OEXRegistrationViewController.m
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-7291](https://openedx.atlassian.net/browse/LEARNER-7291)
In this PR the legal text has updated on registration and sign-in screen.
> iOS - Update Text on Registration Form Checkbox

- Source/OEXEnvironment.m
[LEARNER-7319](https://openedx.atlassian.net/browse/LEARNER-7319)
- Enable segment and firebase analytics from config file.
- Firebase should log one event against any action.
> iOS - Firebase events get replicated with segment.

- Source/SubjectsDiscovery/Subjects JSON/tr.lproj/subjects.json
- Source/en.lproj/profiles.json
- Source/es-419.lproj/profiles.json
- Source/tr.lproj/InfoPlist.strings
- Source/tr.lproj/Localizable.strings
- Source/tr.lproj/MobileAppEula.htm
- Source/tr.lproj/PrivacyPolicy.htm
- Source/tr.lproj/TermsOfServices.htm
- Source/tr.lproj/languages.json
- Source/tr.lproj/profiles.json
- Source/tr.lproj/whats_new.json
- edX.xcodeproj/project.pbxproj
[LEARNER-7349](https://openedx.atlassian.net/browse/LEARNER-7349)
This PR adds the Turkish language support in iOS App. I have downloaded the Turkish translated resources from [transifex](https://www.transifex.com/open-edx/edx-mobile-apps/content/). If the Turkish translation of a resource or for a string is missing, then the English version of that resource/string will be used.
In this PR maximum allowed birth year is also updated to 2019 in the user settings for languages English, Spanish and Turkish.
1. Turkish translation of some resources/strings is missing like Subjects filter in course discovery.
2. Web views content will be in English because webviews are no entertaining the selected language of the iOS device yet.
Change the iOS device language to Turkish. To change the language …
> * Turkish language support added

- Source/OEXExternalRegistrationOptionsView.m
- Source/SubjectsDiscovery/Subjects JSON/de.lproj/subjects.json
- Source/de.lproj/InfoPlist.strings
- Source/de.lproj/Localizable.strings
- Source/de.lproj/MobileAppEula.htm
- Source/de.lproj/PrivacyPolicy.htm
- Source/de.lproj/TermsOfServices.htm
- Source/de.lproj/languages.json
- Source/de.lproj/profiles.json
- Source/de.lproj/whats_new.json
- Source/pt-BR.lproj/languages.json
- edX.xcodeproj/project.pbxproj
[LEARNER-7355](https://openedx.atlassian.net/browse/LEARNER-7355)
This PR adds the German language support in iOS App. I have downloaded the German translated resources from [transifex](https://www.transifex.com/open-edx/edx-mobile-apps/content/). If the German translation of a resource or of a string is missing, then the English version of that resource/string will be used.
In this PR maximum allowed birth year is also updated to 2019 in the user settings.
1. German translation of some resources/strings is missing.
2. Web views content will be in English because web views are not entertaining the selected language of the iOS device yet.
Change the iOS device language to German. To change the language follow the following path:
Settings -> General -> Language & Region -> iPhone Language
> Add German Language Support

- Source/SubjectsDiscovery/Subjects JSON/vi.lproj/subjects.json
- Source/vi.lproj/InfoPlist.strings
- Source/vi.lproj/Localizable.strings
- Source/vi.lproj/MobileAppEula.htm
- Source/vi.lproj/PrivacyPolicy.htm
- Source/vi.lproj/TermsOfServices.htm
- Source/vi.lproj/languages.json
- Source/vi.lproj/profiles.json
- Source/vi.lproj/whats_new.json
- edX.xcodeproj/project.pbxproj
[LEARNER-7354](https://openedx.atlassian.net/browse/LEARNER-7354)
This PR adds the Vietnamese language support in iOS App. I have downloaded the Vietnamese translated resources from [transifex](https://www.transifex.com/open-edx/edx-mobile-apps/content/). If the Vietnamese translation of a resource or of a string is missing, then the English version of that resource/string will be used.
1. Vietnamese translation of some resources/strings is missing.
2. Web views content will be in English because web views are not entertaining the selected language of the iOS device yet.
Change the iOS device language to German. To change the language follow the following path:
Settings -> General -> Language & Region -> iPhone Language
> Add Vietnamese language support

- Source/UserProfileEditViewController.swift
[LEARNER-7435](https://openedx.atlassian.net/browse/LEARNER-7435)
Show alert view message for edit profile screen errors
- Login with staff users.
- Go to the edit profile screen.
- Select the Location option. 
- Change the location and return to back screen.
> iOS - Show alert view message for edit profile screen errors

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXAnalyticsData.h
- Source/OEXInterface.h
- Source/OEXInterface.m
[LEARNER-7444](https://openedx.atlassian.net/browse/LEARNER-7444)
In this PR, youtube player analytics has added. I added three tracking analytics( Play, Pause, Orientation change). 
- Run the youtube video and do play/pause/orientation change actions. 
- Check the analytics on the segment, firebase.
> LEARNER-7444, Add youtube player analytics

- Source/RegistrationFieldSelectView.swift
[LEARNER-7593](https://openedx.atlassian.net/browse/LEARNER-7593)
[LEARNER-7593](https://openedx.atlassian.net/browse/LEARNER-7593)
> Hiding PickerView on Selecting Value on Registration Screen

- Source/OEXLoginViewController.m
- Source/OEXLoginViewController.storyboard
- Source/StartupViewController.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-5162](https://openedx.atlassian.net/browse/LEARNER-5162)
iOS - VoiceOver - says 'edX Vega or something like that' on tapping edX app icon from home screen
1. Activate VoiceOver on device
2. Tap on edX app icon to load it, VoiceOver will say 'edX Vega or something like that'
- Turn On Voice Over in Accessibility
- Load application
- Tap on edX logo
- It will say out name 'edx'
> iOS - VoiceOver - says 'edX Vega or something like that' on tapping edX app icon from home screen

- Source/YoutubeVideoConfig.swift
- Test/YoutubeVideoConfigTest.swift
[LEARNER-7551](https://openedx.atlassian.net/browse/LEARNER-7551)
Update youtube config key
> iOS - Update youtube config key

- Source/SpinnerView.swift
[LEARNER-5160](https://openedx.atlassian.net/browse/LEARNER-5160)
All spinning wheels stopped spinning when we foreground app.
- Login in the app.
- Go in any course detail
- Switch videos tab
- Start downloading all videos
- Press the home button, the app will go in the background.
- Open the app again, the spinners should spin.
> iOS - Spinner issue resolved 

- build.gradle
- buildSrc/build.gradle
- buildSrc/settings.gradle
- gradle/wrapper/gradle-wrapper.properties
[LEARNER-7678](https://openedx.atlassian.net/browse/LEARNER-7678)
Upgrade Gradle plugin version from 4.10.2 to 6.2.2
> Upgrade gradle plugin from 4.10.2 to 6.2.2

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
- Source/VideoBlockViewController.swift
[LEARNER-7683](https://openedx.atlassian.net/browse/LEARNER-7683)
This PR offers the following video player improvements:
1. Fixes the issue: video player controls always visible.
2. Remove irrelevant `wifi-only` message for video streaming on mobile data.
3. UI and control improvements on video completion.
4. Replay functionality for the completed video.
- Login into the app.
- Go inside any course.
- Open the video tab and start any video
- Interact with video to experience all the above-mentioned improvements.
> Experience improvements of Video Player

- build.gradle
[LEARNER-7754](https://openedx.atlassian.net/browse/LEARNER-7754)
Config PR: https://github.com/edx/edx-mobile-config/pull/106
> Update Gradle script for Firebase key PROJECT_ID

- Source/OEXRouter.m
[LEARNER-7750](https://openedx.atlassian.net/browse/LEARNER-7750)
Whenever session is expired or on fresh install, Whatsnew screen appears before Login screen.
> Dismiss Whatsnew screen before presenting login screen

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
[LEARNER-7698](https://openedx.atlassian.net/browse/LEARNER-7698)
Double tap gesture on video player will allow the user to skip backward or skip forward. Double on left side of play button will result in skip backward to -10 seconds. Double tap in right side of play button will result in skip forward to +15 seconds.
> Video Player Double tapping for Video rewind and forward

- Source/CourseCardView.swift
- Source/CourseCertificateView.swift
- Source/CourseDashboardLoadStateViewController.swift
- Source/CourseDashboardViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutlineHeaderCell.swift
- Source/CourseOutlineHeaderView.swift
- Source/CourseOutlineItemView.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CourseSectionTableViewCell.swift
- Source/CourseVideoTableViewCell.swift
- Source/CourseVideosHeaderView.swift
- Source/DownloadsAccessoryView.swift
- Source/IconMessageView.swift
- Source/LoadStateViewController.swift
- Source/ProgressController.swift
- Source/PullRefreshController.swift
- Source/SpinnerView.swift
- Source/Swipeable Cell/SwipeCellActionView.swift
- Source/Swipeable Cell/SwipeableCell.swift
- Source/UIViewController+Overlay.swift
[LEARNER-7786](https://openedx.atlassian.net/browse/LEARNER-7786)
The automation team is working on [Automate Course Dashboard Screen](https://openedx.atlassian.net/browse/LEARNER-7762)  and for that, they need `accessibilityIdentifiers` to be set for all the elements. This PR sets unique `acceessibilityIdentifiers` to all the elements of the course dashboard and relevant screens.
This PR doesn't have any impact on the normal functionality of the app. This will only help the automation team to perform their job.
> Accessibility Identifiers for course dashboard and relevant screens

- Source/OEXLoginViewController.m
[LEARNER-7764](https://openedx.atlassian.net/browse/LEARNER-7764)
Re login from Google does not login on first attempt after logging out
> Re login from Google does not login on first attempt after logging out

- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
[LEARNER-7592](https://openedx.atlassian.net/browse/LEARNER-7592)
> Third part Login and Registration flow improvements

- Source/CutomePlayer/VideoPlayerControls.swift
[LEARNER-7807](https://openedx.atlassian.net/browse/LEARNER-7807)
> Unable to Change Captions and Video Speed

- build.gradle
- edX.xcodeproj/project.pbxproj
[LEARNER-7806](https://openedx.atlassian.net/browse/LEARNER-7806)
Remove fabric debugging symbols that were sending via script on the server, as we are not using fabric so we removed it from code.
- Make sure the app is working fine and not breaking on any screen.
> iOS - Remove Fabric Debugging symbols 

- Source/AdditionalTabBarViewController.swift
- Source/AdditionalTableViewCell.swift
- Source/CertificateViewController.swift
- Source/ChoiceLabel.swift
- Source/CourseAnnouncementsViewController.swift
- Source/CourseDatesViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/CoursesContainerViewController.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DiscussionTopicCell.swift
- Source/DiscussionTopicsViewController.swift
- Source/EnrolledCoursesFooterView.swift
- Source/EnrolledCoursesViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/JSONFormBuilder.swift
- Source/JSONFormBuilderChooser.swift
- Source/JSONFormBuilderTextEditor.swift
- Source/MenuOptionsViewController.swift
- Source/OEXDownloadTableCell.m
- Source/OEXDownloadViewController.m
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Source/ProfileBanner.swift
- Source/TabContainerView.swift
- Source/UserProfileEditViewController.swift
- Source/UserProfileView.swift
- Source/UserProfileViewController.swift
[LEARNER-7836](https://openedx.atlassian.net/browse/LEARNER-7836)
This PR will help out Automation team to find elements.
> Unique Accessibility Identifiers for Enrolled Courses and All the Relevant Screens 

- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Source/OEXStyles.h
[LEARNER-7808](https://openedx.atlassian.net/browse/LEARNER-7808)
> Fix navigation bar item tint color after playing youtube video

- Source/DiscoveryWebViewHelper.swift
[LEARNER-7853](https://openedx.atlassian.net/browse/LEARNER-7853)
Supportive changes for migration of course discovery from Drupal to Prospective. Couse and Program discovery listen to the search query and refreshes itself on clearing the search criteria.
Config PR: https://github.com/edx/edx-mobile-config/pull/110
> Migrate Course Discovery from Drupal to Prospectus

- Source/RegistrationSelectOptionView.swift
- Source/RegistrationSelectOptionViewController.swift
[LEARNER-7891](https://openedx.atlassian.net/browse/LEARNER-7891)
The search functionality is not working properly in the country and other relevant pickers on the registration screen. Make it case insensitive.
> Registration Screen - Make Search View in Picker Case insensitive 

- Source/CourseContentPageViewController.swift
- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
- Source/VideoBlockViewController.swift
[LEARNER-7905](https://openedx.atlassian.net/browse/LEARNER-7905)
In this PR I improved the difficulty in moving the slider of the progress bar of the video. 
- Open any video.
- Try to slide the video progress slider, it should be more smooth as the previous version.
> iOS - improvement of the player progress bar slider

- Source/RegistrationSelectOptionView.swift
- Source/RegistrationSelectOptionViewController.swift
[LEARNER-7960](https://openedx.atlassian.net/browse/LEARNER-7960)
Set AccessibilityIdentifiers for Options controller on the registration screen. This PR will help the automation team to execute their tasks.
> Set AccessibilityIdentifiers for Options controller 

- Source/ChromeCastManager.swift
- Source/CutomePlayer/ChromeCastMiniPlayer.swift
- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAnalyticsData.h
[LEARNER-7982](https://openedx.atlassian.net/browse/LEARNER-7982)
Added Chromecast analytics events for 
- Chromecast connected
- Chromecast disconnected
- Video casted on chromecast
> Chromecast analytics

- Source/OEXAnalytics.m
- Source/SegmentAnalyticsTracker.swift
- Source/UIDeviceExtension.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-7986](https://openedx.atlassian.net/browse/LEARNER-7986)
Send the device model in all the events (Segment & Firebase) under the key `device_model`
Like send the following parameter for the device iPhone 8
if `model` is available,
return `iPhone 8`
else return `iPhone10,4`
> Add device model as a custom dimension

- Source/AuthenticatedWebViewController.swift
These changes allow to show alert dialogs in a webview, this is part of the ora support for mobile included in this pr https://github.com/edx/edx-ora2/pull/1445#pullrequestreview-464088117
https://stackoverflow.com/a/40316507
> Support alert dialogs

- Source/CourseDates.swift
- Source/CourseDatesViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/HTMLBlockViewController.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-8000](https://openedx.atlassian.net/browse/LEARNER-8000)
Implementation analytics events for PLS
> Implement analytics events for PLS work

- DateFormatting.swift
- Libraries/SwiftDate/ISOParser.swift
- Test/DateFormattingTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-7993](https://openedx.atlassian.net/browse/LEARNER-7993)
We are supporting some variants of the ISO 8601 date format but some of the variants are not yet supported and the date didn't parse for unsupported variants.
> Support All Variants of ISO 8601 Date Format

- Source/CourseDates.swift
- Source/CourseDatesViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/HTMLBlockViewController.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-8085](https://openedx.atlassian.net/browse/LEARNER-8085)
> Fix PLS Events

- Source/DiscoveryWebViewHelper.swift
[LEARNER-7927](https://openedx.atlassian.net/browse/LEARNER-7927)
> Remove Discovery E2E test helper JS Code

- Source/AuthenticatedWebViewController.swift
- Source/UIViewController+CommonAdditions.swift
[LEARNER-LEARNER-8156](https://openedx.atlassian.net/browse/LEARNER-LEARNER-8156)
> iOS - Fix WKWebview JavaScript Crash

- Source/AuthenticatedWebViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutline.swift
- Source/CourseOutlineItemView.swift
- Source/CourseOutlineTableSource.swift
- Source/Icon.swift
- Source/OEXRouter+Swift.swift
[LEARNER-8101](https://openedx.atlassian.net/browse/LEARNER-8101)
> Change ORA components' icon

- Source/CourseDatesViewController.swift
[LEARNER-8103](https://openedx.atlassian.net/browse/LEARNER-8103)
After submitting ORA assignments, the status of assignments is not updated on the dates tab until navigating back from the course list page again.
Pull to refresh is not enabled on the dates tab to reflect assignments status.
> ORA submissions not reflecting on Dates tab

- Source/CourseDatesViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/HTMLBlockViewController.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
[LEARNER-8164](https://openedx.atlassian.net/browse/LEARNER-8164)
Use `rtester` to test following courses and match with web.
> Suggested dates displaying in app to learners in instructor-paced courses - PLS

- Source/ar.lproj/profiles.json
- Source/de.lproj/profiles.json
- Source/en.lproj/profiles.json
- Source/es-419.lproj/profiles.json
- Source/fr.lproj/profiles.json
- Source/he.lproj/profiles.json
- Source/ja.lproj/profiles.json
- Source/pt-BR.lproj/profiles.json
- Source/tr.lproj/profiles.json
- Source/vi.lproj/profiles.json
- Source/zh-Hans.lproj/profiles.json
[LEARNER-8212](https://openedx.atlassian.net/browse/LEARNER-8212)
Change `Primary language` to `Spoken language` in the user profile view for clarity.
Go to the user profile edit section.
> Change primary language to spoken language in profile

- Source/AuthenticatedWebViewController.swift
- Source/DiscoveryWebViewHelper.swift
This is actually https://github.com/edx/edx-app-ios/pull/1469 -- I messed up and rebased/force-pushed the branch and it will not let me re-open the PR!
All comments have been addressed, I just need approval again... 😭
> Let the WebViewDelegate to handle a navigation action before trying other ways of handling.

- Source/CourseDatesViewController.swift
- Source/CourseOutline.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-8230](https://openedx.atlassian.net/browse/LEARNER-8230)
This PR adds analytics for the click action of the course date in the Dates tab.
> Analytics to track click events on PLS dates screen

- Source/CourseOutline.swift
- Source/CourseOutlineTableSource.swift
- Source/OEXRouter+Swift.swift
[LEARNER-8238](https://openedx.atlassian.net/browse/LEARNER-8238)
Adding support of `drag-and-drop-v2` as an explicit block type.
> Explicit Drag And Drop xBlock Support

- Source/UIDeviceExtension.swift
[LEARNER-8258](https://openedx.atlassian.net/browse/LEARNER-8258)
Update the library for the latest devices.
> Add latest iPhone/iPad (12 series) to device model

- Source/AccountViewController.swift
- Source/OEXAnalytics+Swift.swift
- Source/WebView/ProgramsViewController.swift
[LEARNER-8260](https://openedx.atlassian.net/browse/LEARNER-8260)
[LEARNER-8259](https://openedx.atlassian.net/browse/LEARNER-8259)
In this PR I added the screen analytics for the Account settings screen and My programs screen
> iOS - Send screen analytics for account settings screen and my programs screen

- Source/CourseOutlineTableSource.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-8268](https://openedx.atlassian.net/browse/LEARNER-8268)
Resume course tapped analytics.
> Resume Course Analytics

- Source/CourseVideoTableViewCell.swift
[LEARNER-8167](https://openedx.atlassian.net/browse/LEARNER-8167)
Fix watched video cell leading icon color
> Fix watched video cell leading icon color 

- Source/CourseVideoTableViewCell.swift
[LEARNER-8335](https://openedx.atlassian.net/browse/LEARNER-8335)
Like Native Videos Youtube Vides is also showing Download icon Next to the Video after playing the video once and then taping on back button
> Youtube Video is showing Download icon

- Source/CourseDateBannerView.swift
- Source/CourseDateViewCell.swift
- Source/SnackbarViews.swift
- Source/UIViewController+Overlay.swift
[LEARNER-8289](https://openedx.atlassian.net/browse/LEARNER-8289)
Added calendar icon to the dates banner on the course dashboard and dates tab screens. And the improvements made to the shift dates success snack bar.
> [feat] Shift dates design enhancements

- Source/HTMLBlockViewController.swift
- Source/SpinnerView.swift
[LEARNER-8362](https://openedx.atlassian.net/browse/LEARNER-8362)
Give learners an option to open the rendered HTML block containing an iframe in the mobile browser for a better learning experience. A banner to open the block in the mobile browser will appear at the bottom of the page.
> [feat] Open rendered HTML block that contains an iframe in the mobile browser

- Source/CourseOutline.swift
- Source/CourseOutlineTableSource.swift
- Source/OEXRouter+Swift.swift
[LEARNER-8265](https://openedx.atlassian.net/browse/LEARNER-8265)
Add word cloud to acceptable list of xblocks
>  Add word cloud to acceptable list of xblocks

- Source/CourseOutline.swift
- Source/CourseOutlineViewController.swift
- Source/CourseStructureAPI.swift
- Source/CourseUnknownBlockViewController.swift
- Source/LoadStateViewController.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXRouter+Swift.swift
- Source/Reachability.m
[LEARNER-8312](https://openedx.atlassian.net/browse/LEARNER-8312)
- Empty sub-section due to special exam
- Empty sub-section.
- Screen Event
- Click Event
> [fix] do not hide special exams

- Source/CalendarManager.swift
- Source/CourseOutlineViewController.swift
[LEARNER-8312](https://openedx.atlassian.net/browse/LEARNER-8312)
> [fix] add check for block type to handle empty subsection 

- Source/CalendarManager.swift
- Source/CalendarSyncConfig.swift
- Source/CourseDashboardViewController.swift
- Source/CourseDatesHeaderView.swift
- Source/CourseDatesViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutlineViewController.swift
- Source/CourseUnknownBlockViewController.swift
- Source/CoursesContainerViewController.swift
- Source/FirebaseRemoteConfiguration.swift
- Source/MenuOptionsViewController.swift
- Source/OEXAppDelegate.m
- edX.xcodeproj/project.pbxproj
[LEARNER-8390](https://openedx.atlassian.net/browse/LEARNER-8390)
Move calendar sync/integration feature behind firebase remote config
> [feat] move calendar integration behind firebase remote config

- Source/CalendarManager.swift
[LEARNER-8302](https://openedx.atlassian.net/browse/LEARNER-8302)
> [feat] add second alert to calendar event 1 day before

- Source/AuthenticatedWebViewController.swift
[LEARNER-8428](https://openedx.atlassian.net/browse/LEARNER-8428)
> [Fix] Fix Memory Leak of AuthenticatedWebViewController

- Source/HTMLBlockViewController.swift
- Source/OEXAnalytics+Swift.swift
[LEARNER-8463](https://openedx.atlassian.net/browse/LEARNER-8463)
This PR adds analytics for Open in browser banner functionality.
> [chore] Open in Browser Banner Analytics

- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseOutlineItemView.swift
- Source/CourseVideoTableViewCell.swift
[LEARNER-8465](https://openedx.atlassian.net/browse/LEARNER-8465)
Fix fuzzy assessment icon
> [fix] assessment icon

- Source/CourseUnknownBlockViewController.swift
[LEARNER-8474](https://openedx.atlassian.net/browse/LEARNER-8474)
> [fix] Fix Blank LTI Consumer Component Screen

- Source/CourseDatesHeaderView.swift
- Source/Icon.swift
- Source/OEXConfig+AppFeatures.swift
- Source/OEXRouter+Swift.swift
- Source/ValuePropDetailViewController.swift
- Source/ValuePropMessageView.swift
- Source/ValuePropMessagesView.swift
- Source/ValuePropTableView.swift
- Source/ValuePropUpgradeButtonView.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-8424](https://openedx.atlassian.net/browse/LEARNER-8424)
Value prop modal UI is laid out as per the design
Config change `IN_APP_PURCHASES_ENABLED` is added as a key to show/hide payment button
> [chore] redesigned value prop modal

- Source/CourseUnknownBlockViewController.swift
- Source/OEXConfig+AppFeatures.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropUpgradeButtonView.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8419](https://openedx.atlassian.net/browse/LEARNER-8419)
Course upgrade button on the locked component screen to purchase a course.
Add `IAP_ENABLED: true` in the config life to see the course upgrade button on the locked component screen.
> [chore] Course purchase option on locked component screen

- Source/CalendarSyncConfig.swift
- Source/CourseDatesViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8514](https://openedx.atlassian.net/browse/LEARNER-8514)
Enable Calendar Sync for Instructor Paced Courses
> [feat] Enable Calendar Sync for Instructor Paced Courses

- Source/CalendarManager.swift
- Source/ContainerNavigationController.swift
- Source/CourseDashboardViewController.swift
- Source/CourseDatesViewController.swift
- Source/CourseOutlineViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/OEXAppDelegate.m
- Source/OEXRouter+Swift.swift
- Source/edX-Bridging-Header.h
[LEARNER-8515](https://openedx.atlassian.net/browse/LEARNER-8515)
COURSE_NAME
(Blank line here)
ASSIGNMENT_1_NAME
ASSIGNMENT_1_LINK
(Blank line here)
ASSIGNMENT_2_NAME
ASSIGNMENT_2_LINK
(Blank line here)
ASSIGNMENT_3_NAME
ASSIGNMENT_3_LINK
> [feat] deep link to the component that is due in my calendar event

- Source/AuthenticatedWebViewController.swift
- Source/BannerViewController.swift
[LEARNER-8643](https://openedx.atlassian.net/browse/LEARNER-8643)
Handle 2U banner webview error 4xx and 5xx inside BannerViewController and show close button to user on reload.
> fix: loader keeps running on the 2U banner

- Source/CourseOutlineTableSource.swift
[LEARNER-8737](https://openedx.atlassian.net/browse/LEARNER-8737)
Hide the value prop button from the course dashboard screen for release 3.1.0
> [chore] Hide Value Prop button from the Course Dashboard Screen

- Libraries/Shimmer/ShimmerView.swift
- Source/CourseUpgradeButtonView.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8741](https://openedx.atlassian.net/browse/LEARNER-8741)
On the Value Prop pages, while course pricing information is (still) being fetched from the App/Play Store, a loading “shimnmer” (aka “skeleton”) should be shown.
> [feat] add shimmer effect to view while price is loading

- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/ValuePropDetailViewController.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8761](https://openedx.atlassian.net/browse/LEARNER-8761)
This PR includes all the new error messages of the IAP flow other than the retry option of `execute api` and retry option to fetch the price of the course in case of failure.
> feat: more detailed IAP error messages according to error in flow

- Source/CourseUpgradeButtonView.swift
[LEARNER-8853](https://openedx.atlassian.net/browse/LEARNER-8853)
Update shimmer color to `light-500/#E1DDDB`
> [fix] update shimmer color to light-500

- PULL_REQUEST_TEMPLATE
Update from openedx to 2u-internal
[LEARNER-](https://openedx.atlassian.net/browse/LEARNER-)
> chore: update PULL_REQUEST_TEMPLATE

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter+Swift.swift
- Source/WebView/DiscoveryHelper.swift
[LEARNER-8870](https://2u-internal.atlassian.net/browse/LEARNER-8870)
The [Config Flags Wiki](https://2u-internal.atlassian.net/wiki/spaces/LEARNER/pages/7150066/App+Configuration+Flags) has been updated with new changes and the old discover config moved to deprecated section of the wiki to track the changes.
> [chore] Deep Linking, Push Notification Navigation As per New Discover Experience

- Source/DiscoveryWebViewHelper.swift
[LEARNER-8880](https://2u-internal.atlassian.net/browse/LEARNER-8880)
This PR adds pull-to-refresh on new Discovery web view experience
> [feat] add pull to refresh on discovery 

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionHelper.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/Icon.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
[LEARNER-8863](https://2u-internal.atlassian.net/browse/LEARNER-8863)
This PR updates Icons inside the Discussion tab in app as per [figma](https://www.figma.com/file/DrgCtdxwqwvYuQTLjTH9Fd/Icon-Replacements?node-id=70%3A85) file
> [chore] update discussion icons

- Source/edX-Info.plist
[LEARNER-8962](https://2u-internal.atlassian.net/browse/LEARNER-8962)
> [chore] Remove NSUserTrackingUsageDescription Key from Info.plist

- Source/CourseUpgradeAPI.swift
[LEARNER-8809](https://2u-internal.atlassian.net/browse/LEARNER-8809)
To transform the IAP error messages into JSON format for all the end points backend has updated the checkout endpoint from `/api/v2/checkout/` to `/api/iap/v1/checkout/`.
> [chore] Update E-commerce Checkout API

- Source/CourseDatesViewController.swift
- Source/FirebaseRemoteConfiguration.swift
- Source/OEXAppDelegate.m
[LEARNER-9011](https://2u-internal.atlassian.net/browse/LEARNER-9011)
This PR configures Calendar Sync toggle on first app launch, previously, on first app launch we were saving value from Firebase Remote Config and applying on second run of app.
> [chore] configure calendar sync on app launch

- Source/OEXVideoEncoding.h
- Source/OEXVideoEncoding.m
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
- Test/VideoBlockViewControllerTests.swift
- Test/YoutubeVideoPlayerTests.swift
[LEARNER-9014](https://2u-internal.atlassian.net/browse/LEARNER-9014)
This PR adds `stream_priority` to `course` api and when a video is played, video with highest `stream_priority` is played.
> [chore] add stream priority to videos

- Source/LearnContainerHeaderView.swift
[LEARNER-9036](https://2u-internal.atlassian.net/browse/LEARNER-9036)
This PR fixes the arrow animation on Learn Tab Header
> [chore] fix arrow animation on learn header

- Source/EnrolledCoursesViewController.swift
- Source/LearnContainerViewController.swift
- Source/WebView/ProgramsViewController.swift
[LEARNER-9033](https://2u-internal.atlassian.net/browse/LEARNER-9033)
This PR fixes back button title `Back` that appears on Programs and Course Dashboard while navigation back and forth on screens.
> [chore] fix back button title on programs and course dashboard

- Source/EnrolledCoursesViewController.swift
[LEARNER-9033](https://2u-internal.atlassian.net/browse/LEARNER-9033)
> [fix] fix back button title

- Source/CourseDatesViewController.swift
[LEARNER-9056](https://2u-internal.atlassian.net/browse/LEARNER-9056)
This PR fixes crash when firebase remote config notification is fired and UI is not being updated on main thread.
> [fix] fix crash on loading firebase remote config

- Source/OEXVideoSummary.m
- Source/VideoBlockViewController.swift
[LEARNER-9014](https://2u-internal.atlassian.net/browse/LEARNER-9014)
> [chore] Video stream priority handling  with downloaded videos

- Source/OEXAnalytics+CourseUpgrade.swift
- Source/OEXAnalytics+Swift.swift
- Source/ServerConfiguration.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9018](https://2u-internal.atlassian.net/browse/LEARNER-9018)
This PR adds IAP Analytics experiment analytics, more details can be found [here](https://2u-internal.atlassian.net/browse/LEARNER-9018).
> [chore] add value prop iap experiment analytics

- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/OEXAnalytics+CourseUpgrade.swift
- Source/UIAlertController+OEXBlockActions.swift
- Source/ar.lproj/CourseUpgrade.strings
- Source/de.lproj/CourseUpgrade.strings
- Source/en.lproj/CourseUpgrade.strings
- Source/es-419.lproj/CourseUpgrade.strings
- Source/fr.lproj/CourseUpgrade.strings
- Source/he.lproj/CourseUpgrade.strings
- Source/ja.lproj/CourseUpgrade.strings
- Source/pt-BR.lproj/CourseUpgrade.strings
- Source/tr.lproj/CourseUpgrade.strings
- Source/vi.lproj/CourseUpgrade.strings
- Source/zh-Hans.lproj/CourseUpgrade.strings
[LEARNER-9024](https://2u-internal.atlassian.net/browse/LEARNER-9024)
This PR adds message for SDN Prompt.
> [chore] add sdn title and message

- Source/CourseDatesViewController.swift
[LEARNER-9074](https://2u-internal.atlassian.net/browse/LEARNER-9074)
This PR fixes Course Dates Tab header alignment on landscape mode
> [fix] course dates header alignment on landscape

- Source/EnrolledTabBarViewController.swift
[LEARNER-9088](https://2u-internal.atlassian.net/browse/LEARNER-9088)
> fix: fix find courses button is not tappable

- Source/CourseDashboardViewController.swift
[LEARNER-9101](https://2u-internal.atlassian.net/browse/LEARNER-9101)
> chore: Add Course Dashboard Event

- Source/EnrolledTabBarViewController.swift
[LEARNER-9061](https://2u-internal.atlassian.net/browse/LEARNER-9061)
This PR adds indicator to tabbar, indicator is visible for the selected tab.
> [chore] add indicator on tab bar

- Source/CourseDatesHeaderView.swift
- Source/CourseDatesViewController.swift
[LEARNER-9108](https://2u-internal.atlassian.net/browse/LEARNER-9108)
This PR hides Banner on Course Dates tab in case of instructor paced courses for verified users.
> [fix] fix dates tab banner for instructor paced course

- Source/Icon.swift
[LEARNER-9076](https://2u-internal.atlassian.net/browse/LEARNER-9076)
This PR updates the Learn Tab icon.
> chore: update learn tab icon

- Source/CourseOutlineViewController.swift
- Source/CourseUnknownBlockViewController.swift
- Source/EnrolledCoursesViewController+CourseUpgrade.swift
- Source/OEXAnalytics+CourseUpgrade.swift
- Source/OEXAnalytics+Swift.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9131](https://2u-internal.atlassian.net/browse/LEARNER-9131)
> fix: improvements in some of IAP and value prop analytics

- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/EnrolledCoursesViewController+CourseUpgrade.swift
- Source/EnrolledCoursesViewController.swift
- Source/OEXAnalytics+CourseUpgrade.swift
- Source/OEXAnalytics+Swift.swift
- Source/ProfileOptionsViewController.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9151](https://2u-internal.atlassian.net/browse/LEARNER-9151)
> chore: IAP Analytics for Unfulfilled Case

- Source/CourseDashboardHeaderView.swift
- Source/CourseDashboardTabbarView.swift
- Source/NewCourseDashboardViewController.swift
- Source/NewDashboardContentCell.swift
- Source/ar.lproj/Localizable-2.strings
- Source/de.lproj/Localizable-2.strings
- Source/en.lproj/Localizable-2.strings
- Source/es-419.lproj/Localizable-2.strings
- Source/fr.lproj/Localizable-2.strings
- Source/he.lproj/Localizable-2.strings
- Source/ja.lproj/Localizable-2.strings
- Source/pt-BR.lproj/Localizable-2.strings
- Source/tr.lproj/Localizable-2.strings
- Source/vi.lproj/Localizable-2.strings
- Source/zh-Hans.lproj/Localizable-2.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-9069](https://2u-internal.atlassian.net/browse/LEARNER-9069)
This PR moves tabbar from bottom to top inside header view.
Use config PR for testing https://github.com/edx/edx-mobile-config/pull/134
> chore: course tab bar flow changes in course dashboard

- Source/UserProfileViewController.swift
[LEARNER-9162](https://2u-internal.atlassian.net/browse/LEARNER-9162)
> chore: set navigation back item in id on profile screen for automation

- Libraries/SwiftyJSON/Source/SwiftyJSON.swift
- Pods/Pods.xcodeproj/project.pbxproj
- Source/CourseDateViewCell.swift
- Source/OEXConfig+swift.swift
- Source/OEXDataParser.h
- Source/OEXInterface.h
- edX.xcodeproj/project.pbxproj
- edX.xcodeproj/xcshareddata/xcschemes/EndToEndTests.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edX-RTL.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edX.xcscheme
- edX.xcodeproj/xcshareddata/xcschemes/edXCore.framework.xcscheme
[LEARNER-9172](https://2u-internal.atlassian.net/browse/LEARNER-9172)
Xcode generating the following security warning but it seems because of xcode internal bug. More details can be found at [apple developer forum](https://developer.apple.com/forums/thread/712074)
`/Volumes/Data/Work/Saeed/edx-app-ios/Source/main.m:15 This method should not be called on the main thread as it may lead to UI unresponsiveness.`
> chore: add support of Xcode 14.1

- Source/AuthenticatedWebViewController.swift
- Source/HTMLBlockViewController.swift
- Source/NetworkManager+Authenticators.swift
- Source/OEXAuthentication.m
- Source/OEXCourseInfoViewController.m
- Source/ProgramsDiscoveryViewController.swift
[LEARNER-9174](https://2u-internal.atlassian.net/browse/LEARNER-9174)
> test: add test analytics to trace crash reason

- edX.xcodeproj/project.pbxproj
[LEARNER-9120](https://2u-internal.atlassian.net/browse/LEARNER-9120)
Merge PR for merging rc/3.2.0 to master
> chore: RC 3.2.0

- Source/CourseOutlineTableSource.swift
- Source/CoursesContainerViewController.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/UserCourseEnrollment.swift
[LEARNER-9163](https://2u-internal.atlassian.net/browse/LEARNER-9163)
This PR handles the Value Prop for the course that has future start date.
> chore: handle value prop for course with future start date

- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/OEXTextStyle.m
[LEARNER-9147](https://2u-internal.atlassian.net/browse/LEARNER-9147)
This PR renders the HTML if available in the thready rendered body.
This PR is only rendering the HTML and not the mathematics like mathjax library.
> chore: render HTML of thread on responses screen

- Source/AgreementURLsConfig.swift
- Source/BrowserViewController.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXRouter+Swift.swift
- Source/ProfileOptionsViewController.swift
- Source/ar.lproj/ProfileOptions.strings
- Source/de.lproj/ProfileOptions.strings
- Source/en.lproj/ProfileOptions.strings
- Source/es-419.lproj/ProfileOptions.strings
- Source/fr.lproj/ProfileOptions.strings
- Source/he.lproj/ProfileOptions.strings
- Source/ja.lproj/ProfileOptions.strings
- Source/pt-BR.lproj/ProfileOptions.strings
- Source/tr.lproj/ProfileOptions.strings
- Source/vi.lproj/ProfileOptions.strings
- Source/zh-Hans.lproj/ProfileOptions.strings
- Test/AgreementURLsConfigTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-9194](https://2u-internal.atlassian.net/browse/LEARNER-9194)
Added a new privacy section in the user profile screen above the help section. Tapping on each option in the privacy  section opens a webview for the corresponding option.
https://github.com/edx/edx-mobile-config/pull/137
> chore: add project one trust in profile options

- Source/CoursesContainerViewController.swift
- Source/EnrolledCoursesViewController.swift
- Source/GeneralErrorView.swift
- Source/NetworkManager+Authenticators.swift
- Source/ar.lproj/Localizable-2.strings
- Source/de.lproj/Localizable-2.strings
- Source/en.lproj/Localizable-2.strings
- Source/es-419.lproj/Localizable-2.strings
- Source/fr.lproj/Localizable-2.strings
- Source/he.lproj/Localizable-2.strings
- Source/ja.lproj/Localizable-2.strings
- Source/pt-BR.lproj/Localizable-2.strings
- Source/tr.lproj/Localizable-2.strings
- Source/vi.lproj/Localizable-2.strings
- Source/zh-Hans.lproj/Localizable-2.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-9167](https://2u-internal.atlassian.net/browse/LEARNER-9167)
This PR adds new error screen to dashboard
> chore: add error view on enrolled courses screen

- Source/CelebratoryModalViewController.swift
[LEARNER-9212](https://2u-internal.atlassian.net/browse/LEARNER-9212)
Constraints was not setting properly in the landscape mode. This PR fixes the setting of constraints in landscape and portrait modes.
> fix: fix celebratory modal UI in landscape

- Source/ProfileOptionsViewController.swift
- Source/ar.lproj/ProfileOptions.strings
- Source/de.lproj/ProfileOptions.strings
- Source/en.lproj/ProfileOptions.strings
- Source/es-419.lproj/ProfileOptions.strings
- Source/fr.lproj/ProfileOptions.strings
- Source/he.lproj/ProfileOptions.strings
- Source/ja.lproj/ProfileOptions.strings
- Source/pt-BR.lproj/ProfileOptions.strings
- Source/tr.lproj/ProfileOptions.strings
- Source/vi.lproj/ProfileOptions.strings
- Source/zh-Hans.lproj/ProfileOptions.strings
[LEARNER-9128](https://2u-internal.atlassian.net/browse/LEARNER-9128)
> chore: profile options screen improvements

- Source/CourseUnknownBlockViewController.swift
- Source/CourseUpgradeHelper.swift
- Source/EnrolledCoursesViewController+CourseUpgrade.swift
- Source/PaymentManager.swift
- Source/ProfileOptionsViewController.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9262](https://2u-internal.atlassian.net/browse/LEARNER-9262)
> refactor: IAP minor code improvements

- Source/ServerConfiguration.swift
[LEARNER-9265](https://2u-internal.atlassian.net/browse/LEARNER-9265)
The change can be tested on the [IAP sandbox](https://iap.sandbox.edx.org/)
> feat: add support to disabled IAP for specific versions

- Source/CourseCardViewModel.swift
- Source/ar.lproj/Localizable-2.strings
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable-2.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable-2.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable-2.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable-2.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable-2.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable-2.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable-2.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable-2.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable-2.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable-2.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-9246](https://2u-internal.atlassian.net/browse/LEARNER-9246)
> chore: course access messages updated

- .tx/config
- Updating tx config for new transifex client v3 . For further details, check the issue https://github.com/edx/edx-arch-experiments/issues/190#issuecomment-1442401691
- `arbi-bom` doesn't have write access to the repo so created PR from fork instead.
> fix: update tx config

- Source/CourseUnknownBlockViewController.swift
- Source/DiscoveryWebViewHelper.swift
- Source/HTMLBlockViewController.swift
[LEARNER-9077](https://2u-internal.atlassian.net/browse/LEARNER-9077)
> fix: Layout discrepancy on landscape mode

- Source/CourseOutlineHeaderCell.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseSectionTableViewCell.swift
- Source/Icon.swift
- Source/NewCourseDashboardViewController.swift
- Source/ResumeCourseHeaderView.swift
- Source/ar.lproj/Localizable-2.strings
- Source/de.lproj/Localizable-2.strings
- Source/en.lproj/Localizable-2.strings
- Source/es-419.lproj/Localizable-2.strings
- Source/fr.lproj/Localizable-2.strings
- Source/he.lproj/Localizable-2.strings
- Source/ja.lproj/Localizable-2.strings
- Source/pt-BR.lproj/Localizable-2.strings
- Source/tr.lproj/Localizable-2.strings
- Source/vi.lproj/Localizable-2.strings
- Source/zh-Hans.lproj/Localizable-2.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-9065](https://2u-internal.atlassian.net/browse/LEARNER-9065)
This PR adds new resume course button implementation for the new app nav work.
> chore: resume course button implementation for new design #1737

- Source/CourseOutlineTableSource.swift
[LEARNER-9263](https://2u-internal.atlassian.net/browse/LEARNER-9263)
> chore: hide dates banner in favor or value prop button 

- Source/ExternalAuthOptionsView.swift
- Source/ExternalProviderButtonView.swift
- Source/OEXExternalRegistrationOptionsView.m
- Source/OEXLoginViewController.m
[LEARNER-9179](https://2u-internal.atlassian.net/browse/LEARNER-9179)
> fix: Accessibility of third party auth buttons on login and register screen

- Source/OEXRegistrationViewController.m
[LEARNER-9146](https://2u-internal.atlassian.net/browse/LEARNER-9146)
> fix: alignment and color of ui activity indicator

- Source/DiscoveryWebViewHelper.swift
- Source/OEXRouter.m
- Source/StartupViewController.swift
[LEARNER-8938](https://2u-internal.atlassian.net/browse/LEARNER-8938)
> fix: fix auto enrollment of course from the pre login discovery on login

- Source/ContainerNavigationController.swift
- Source/CourseDashboardHeaderView.swift
- Source/CourseDashboardTabbarView.swift
- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/EnrolledTabBarViewController.swift
- Source/NewCourseDashboardViewController.swift
- Source/OEXConfig+AppFeatures.swift
- Source/OEXRouter+Swift.swift
[LEARNER-9274](https://2u-internal.atlassian.net/browse/LEARNER-9274)
This PR fixes deeplinks with the new course dashboard
> chore: fix deeplinks with new dashboard

- Source/CourseOutlineTableSource.swift
- Source/CourseVideosHeaderView.swift
- Source/OEXInterface.m
[LEARNER-9288](https://2u-internal.atlassian.net/browse/LEARNER-9288)
> fix: videos related fixes on course videos tab

- Source/ar.lproj/CourseUpgrade.strings
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/CourseUpgrade.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/CourseUpgrade.strings
- Source/es-419.lproj/CourseUpgrade.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/CourseUpgrade.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/CourseUpgrade.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/CourseUpgrade.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/CourseUpgrade.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/CourseUpgrade.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/CourseUpgrade.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/CourseUpgrade.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-9319](https://2u-internal.atlassian.net/browse/LEARNER-9319)
> chore: added the translations for IAP strings

- Source/DiscussionResponsesDataController.swift
- Source/DiscussionResponsesViewController.swift
[LEARNER-9287](https://2u-internal.atlassian.net/browse/LEARNER-9287)
> fix: fix discussion posts with images gets stuck while scrolling

- Source/CourseContentHeaderView.swift
- Source/CourseContentPageViewController.swift
- Source/CourseOutlineViewController.swift
- Source/DetailToolbarButton.swift
- Source/DiscussionBlockViewController.swift
- Source/HTMLBlockViewController.swift
- Source/Icon.swift
- Source/NewCourseContentController.swift
- Source/OEXConfig+AppFeatures.swift
- Source/OEXRouter+Swift.swift
- Source/PostsViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-9083](https://2u-internal.atlassian.net/browse/LEARNER-9083)
This PR adds new navigation to component screen and updated design for component screen
> chore: new component screen

- Source/ServerConfiguration.swift
[LEARNER-9327](https://2u-internal.atlassian.net/browse/LEARNER-9327)
> feat: add support to enable course upgrade for specific users

- Source/OEXCheckBoxView.m
- Source/OEXRegistrationFieldCheckBoxController.m
[LEARNER-9356](https://2u-internal.atlassian.net/browse/LEARNER-9356)
Note: I've also set the alignment of checkbox and agreement tax because the tax is being return from server is short.
> chore: use marketing opt-in message returned from server on registration screen

- Source/Deep Linking/DeepLinkManager.swift
- Source/OEXRouter+Swift.swift
[LEARNER-9322](https://2u-internal.atlassian.net/browse/LEARNER-9322)
I've created the following links for `course_id: course-v1:edX+Inf101+2022`
- [discussion_topics](https://edx.test-app.link/discussion_topics)
- [discussion_post](https://edx.test-app.link/discussion_post)
- [discussion_comment](https://edx.test-app.link/discussionComment)
The command can be used to activate deeplink from the command line, `xcrun simctl openurl booted {}deep_link`
> chore: discussions deep link and push notifications support for new course dashboard

- Source/NewCourseDashboardViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-9370](https://2u-internal.atlassian.net/browse/LEARNER-9370)
> chore: update status bar color to match course dashboard header color

- Source/CourseDashboardHeaderView.swift
- Source/NewCourseDashboardViewController.swift
- Source/UIViewController+CommonAdditions.swift
[LEARNER-9384](https://2u-internal.atlassian.net/browse/LEARNER-9384)
> fix: fix course share button on iPad

- Source/NewCourseDashboardViewController.swift
[LEARNER-9382](https://2u-internal.atlassian.net/browse/LEARNER-9382)
> fix: fix blank screen on fresh enrollment with app nav work

- Source/CourseOutlineTableSource.swift
[LEARNER-9389](https://2u-internal.atlassian.net/browse/LEARNER-9389)
This PR fixes view that is showing behind collapsible headers
> fix: view showing behind collapsible headers

- Source/AuthenticatedWebViewController.swift
- Source/CourseDatesViewController.swift
- Source/HTMLBlockViewController.swift
[LEARNER-9411](https://2u-internal.atlassian.net/browse/LEARNER-9411)
This PR fixes memory leak from HTMLBlockViewController which retains the instance of AuthenticatedWebViewController.
> chore: fix memory leak

- Source/DiscoveryWebViewHelper.swift
[LEARNER-9383](https://2u-internal.atlassian.net/browse/LEARNER-9383)
> fix: pull to refresh smoothness on discover screen

- Source/OEXRouter.m
[LEARNER-9406](https://2u-internal.atlassian.net/browse/LEARNER-9406)
> fix: fix for unexpected logout

- Source/CourseDashboardAccessErrorView.swift
- Source/NewCourseDashboardViewController.swift
[LEARNER-9430](https://2u-internal.atlassian.net/browse/LEARNER-9430)
> chore: incorporate changes of course price and currency code for execute api in app_nav

- Source/CelebratoryModalViewController.swift
- Source/CourseContentPageViewController.swift
[LEARNER-9428](https://2u-internal.atlassian.net/browse/LEARNER-9428)
> refactor: celebratory modal layout improvements

- Source/AccessibilityCLButton.swift
- Source/CourseContentPageViewController.swift
- Source/CourseDashboardHeaderView.swift
- Source/CutomePlayer/VideoPlayer.swift
- Source/NewCourseContentController.swift
- Source/NewCourseDashboardViewController.swift
- Source/OEXRouter+Swift.swift
- Source/UIViewController+CommonAdditions.swift
- Source/VideoBlockViewController.swift
[LEARNER-9410](https://2u-internal.atlassian.net/browse/LEARNER-9410)
This PR handles support for landscape mode for new dashboard and new component screen.
> chore: handle landscape for new dashboard and component navigation

- Source/CoursesContainerViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXRouter+Swift.swift
[LEARNER-9451](https://2u-internal.atlassian.net/browse/LEARNER-9451)
> chore: update find courses clicked analytics

- Source/CourseDashboardHeaderView.swift
- Source/CourseDashboardTabbarView.swift
- Source/DiscussionTopicsViewController.swift
- Source/DropDown/helpers/DPDUIView+Extension.swift
- Source/NewCourseContentController.swift
- Source/NewCourseDashboardViewController.swift
- Source/ProfileOptionsViewController.swift
- Source/UserProfileEditViewController.swift
[LEARNER-9438](https://2u-internal.atlassian.net/browse/LEARNER-9438)
This PR addresses feedback on App Nav work
- make hairline consistent on tabbar on Course Dashboard
- change navigation on tapping profile on Profile screen to edit profile
> [chore] address app nav feedback

- Source/CutomePlayer/OEXVideoPlayerSettings.swift
- Source/CutomePlayer/TranscriptManager.swift
- Source/CutomePlayer/VideoPlayer.swift
- Source/ar.lproj/Localizable-2.strings
- Source/de.lproj/Localizable-2.strings
- Source/en.lproj/Localizable-2.strings
- Source/es-419.lproj/Localizable-2.strings
- Source/fr.lproj/Localizable-2.strings
- Source/he.lproj/Localizable-2.strings
- Source/ja.lproj/Localizable-2.strings
- Source/pt-BR.lproj/Localizable-2.strings
- Source/tr.lproj/Localizable-2.strings
- Source/vi.lproj/Localizable-2.strings
- Source/zh-Hans.lproj/Localizable-2.strings
[LEARNER-9433](https://2u-internal.atlassian.net/browse/LEARNER-9433)
> feat: add None option in the caption list to deselect caption language

- Source/ValuePropCourseCardView.swift
[LEARNER-9439](https://2u-internal.atlassian.net/browse/LEARNER-9439)
This PR fixes title label constraint of course card.
> [fix] fix title label constraint on course card

- Source/ValuePropCourseCardView.swift
This reverts commit 263de97ed25959e28388499caf16e2237988006f.
[LEARNER-9394](https://2u-internal.atlassian.net/browse/LEARNER-9394)
> Revert "chore: fix title label constraint (#1775)"

- Source/CoursesContainerViewController.swift
- Source/EnrolledCoursesViewController.swift
[LEARNER-9390](https://2u-internal.atlassian.net/browse/LEARNER-9390)
> fix: fix unable to dismiss an error message from course list screen

- Source/ValuePropCourseCardView.swift
[LEARNER-9439](https://2u-internal.atlassian.net/browse/LEARNER-9439)
This PR fixes title label constraint on Course Dard
> chore: fix title label constraint

- Pods/Target Support Files/Pods-edX/Pods-edX-frameworks.sh
- Source/CourseOutlineTableSource.swift
[LEARNER-9394](https://2u-internal.atlassian.net/browse/LEARNER-9394)
Note: I've also made a change that is required to make archive's.
> fix: fix for section unwanted collapse

- Source/NewCourseDashboardViewController.swift
[LEARNER-9476](https://2u-internal.atlassian.net/browse/LEARNER-9476)
This PR fixes crash after new enrollment on new course dashboard screen.
> fix: fix crash on new enrollment on course dashboard

- Source/OEXRouter.m
[LEARNER-9478](https://2u-internal.atlassian.net/browse/LEARNER-9478)
> fix: fix sign out is not working properly

- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
[LEARNER-9477](https://2u-internal.atlassian.net/browse/LEARNER-9477)
This PR fixes a case where if a section is completed, then expand sthe next incomplete section.
> chore: expand next section after a section is marked as completed

- Source/UserProfileEditViewController.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-9507](https://2u-internal.atlassian.net/browse/LEARNER-9507)
> chore: update the edit screen title to Personal information

- Source/ProfileOptionsViewController.swift
[LEARNER-9488](https://2u-internal.atlassian.net/browse/LEARNER-9488)
> chore: show restore payments to only payment enabled users

- Source/CourseDashboardViewController.swift
- Source/CourseDateBannerView.swift
- Source/HTMLBlockViewController.swift
- Source/OEXRouter+Swift.swift
[LEARNER-9517](https://2u-internal.atlassian.net/browse/LEARNER-9517)
This PR updates the Course Dates Shift banner on the updated Component screen
> chore: update shift dates banner on component screen

- Source/DiscoveryViewController.swift
- Source/DiscoveryWebViewHelper.swift
- Source/NewCourseDashboardViewController.swift
- Source/OEXFindCoursesViewController.h
- Source/OEXFindCoursesViewController.m
- Source/OEXRouter+Swift.swift
[LEARNER-9490](https://2u-internal.atlassian.net/browse/LEARNER-9490)
> chore: improve scrolling experience on discover title bar

- Source/Deep Linking/DeepLinkManager.swift
[LEARNER-9012](https://2u-internal.atlassian.net/browse/LEARNER-9012)
This PR updates the deelplink of `settings` and `profile`
> chore: change settings and profile deep link

- Source/OEXFindCoursesViewController.m
- Source/WebView/DiscoveryHelper.swift
- Test/DiscoveryHelperTests.swift
- Test/OEXFindCoursesTests.m
[LEARNER-9526](https://2u-internal.atlassian.net/browse/LEARNER-9526)
> chore: remove code in the code base around discover hardcoded path

- Source/VideoBlockViewController.swift
- Source/VideoTranscript.swift
[LEARNER-9598](https://2u-internal.atlassian.net/browse/LEARNER-9598)
This PR handles expanding and collapsing of header view in video block
> chore: handle header view in video block

- Source/OEXAppDelegate.m
[LEARNER-9609](https://2u-internal.atlassian.net/browse/LEARNER-9609)
> chore: disable chrome cast for app nav release

- Source/UIDeviceExtension.swift
[LEARNER-9648](https://2u-internal.atlassian.net/browse/LEARNER-9648)
> chore: update devices names for GA's custom dimension after iPhone 15's release

- Source/CourseDashboardHeaderView.swift
- Source/NewCourseDashboardViewController.swift
[LEARNER-9650](https://2u-internal.atlassian.net/browse/LEARNER-9650)
> chore: update constraints on header view

- Source/VideoBlockViewController.swift
- Source/VideoTranscript.swift
[LEARNER-9652](https://2u-internal.atlassian.net/browse/LEARNER-9652)
> chore: clear transcript view after video controller is dismissed

- Source/CourseContentHeaderView.swift
- Source/NewCourseContentController.swift
[LEARNER-9641](https://2u-internal.atlassian.net/browse/LEARNER-9641)
This PR fixes the drop down items in component screen to show Units and update indicator to currently visible component block
> chore: show unit in dropdown, update indicator to current component block

- Source/CoursesContainerViewController.swift
- Source/EnrolledCoursesViewController.swift
[LEARNER-9616](https://2u-internal.atlassian.net/browse/LEARNER-9616)
> fix: blink of empty courses screens on enrolled courses list view

- Source/ChromeCastButtonDelegate.swift
- Source/ChromeCastManager.swift
- Source/ChromeCastMetaDataModel.swift
- Source/ContainerNavigationController.swift
- Source/CourseContentPageViewController.swift
- Source/CourseDashboardHeaderView.swift
- Source/CourseDashboardViewController.swift
- Source/CutomePlayer/ChromeCastMiniPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
- Source/EnrolledTabBarViewController.swift
- Source/NewCourseDashboardViewController.swift
- Source/OEXAppDelegate.m
- Source/VideoBlockViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-9688](https://2u-internal.atlassian.net/browse/LEARNER-9688)
This PR updates Chromecast for the App Nav. Chromecast button is shown on video screen, and if casting is being done for a video of same course, CourseDashboard shows cast button.
Playing video on chromecast
https://github.com/openedx/edx-app-ios/assets/960241/3e01b0bf-f25e-435b-819a-cfea7fc6de90
When chromecast is not available.
> chore: update chromecast for app nav

- Source/OEXAnalytics+Swift.swift
- Source/ProfileOptionsViewController.swift
- Source/ServerConfiguration.swift
[LEARNER-9833](https://2u-internal.atlassian.net/browse/LEARNER-9833)
> chore: learner feedback collection from the mobile app

- Source/OEXAnalytics+Swift.swift
- Source/ProfileOptionsViewController.swift
- Source/ServerConfiguration.swift
Reverts openedx/edx-app-ios#1819
> Revert "chore: learner feedback collection from the mobile app"

- Source/CourseDashboardAccessErrorView.swift
- Source/EnrolledCoursesViewController+CourseUpgrade.swift
- Source/NewCourseDashboardViewController.swift
- Source/PaymentManager.swift
- Source/ProfileOptionsViewController.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9843](https://2u-internal.atlassian.net/browse/LEARNER-9843)
> chore: handle when course sku details not available on app store

- Source/NSError+JSON.swift
[LEARNER-9844](https://2u-internal.atlassian.net/browse/LEARNER-9844)
> chore: logout user on receiving mismatch email error from server

- Source/CourseUpgradeHelper.swift
[LEARNER-9879](https://2u-internal.atlassian.net/browse/LEARNER-9879)
> chore: don't send error analytics in combination

- Source/CourseUpgradeAPI.swift
- Source/CourseUpgradeHandler.swift
[LEARNER-9930](https://2u-internal.atlassian.net/browse/LEARNER-9930)
> chore: refactor in-app purchase execute API

- Source/CourseUpgradeHelper.swift
- Source/NewCourseDashboardViewController.swift
- Source/ValuePropUnlockViewContainer.swift
[LEARNER-9961](https://2u-internal.atlassian.net/browse/LEARNER-9961)
> fix: improve showing of IAP unlock controller
