openedx/edx-app-ios

- edXVideoLocker/CutomePlayer/CLPortraitOptionsView.m
- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
App was getting crash because in code at some places new classnames were not reflected. So I have replaced ClosedCaptionTableViewCell with OEXClosedCaptionTableViewCell to fix crash in code 
to fix crash.
JIRA:https://openedx.atlassian.net/browse/MOB-1373
@aleffert  @nasthagiri  Please review .
> Replace ClosedCaptionTableViewCell with OEXClosedCaptionTableViewCell to fix crash

- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/edXVideoLocker-Info.plist
Overriding an existing method through a category isn't guaranteed to work plus iPad support will need to us to do something else anyway.
@rohan-dhamal-clarice @jotiram please take a look
cc @nasthagiri
> Use less hacky method to force app into portrait

- edXVideoLocker/NSArray+OEXSafeAccess.h
- edXVideoLocker/NSArray+OEXSafeAccess.m
- edXVideoLocker/OEXVideoSummary.m
We're expecting some courses to have overly short paths. This was
causing a crash on some courses when doing a DEBUG build. Release builds
were fine.
@nasthagiri
> Remove assertion if part of the path is missing.

- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
The frame of closed caption label on video player has been fixed so that the vertical appearance does not occur.
> Fix vertical appearance of Closed Caption

- edXVideoLocker/CutomePlayer/CLPortraitOptionsView.m
- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
App was getting crash if selected language in not available for playing video . I reset selected Closed Caption language to fix crash if it is not available for playing video.
JIRA : https://openedx.atlassian.net/browse/MOB-1347
@aleffert  @nasthagiri  Please review.
> Reset selected Closed Caption language to fix crash if it is not available for playing video.

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
- edXVideoLocker/OEXAnalytics.h
- edXVideoLocker/OEXAnalytics.m
- edXVideoLocker/OEXAnalyticsTracker.h
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXDownloadManager.m
- edXVideoLocker/OEXEnvironment.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXOpenInBrowserViewController.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/OEXSegmentAnalyticsTracker.h
- edXVideoLocker/OEXSegmentAnalyticsTracker.m
This also makes it easier to plug in different analytics providers, for
example, a test analytics provider that creates examinable records.
> Prevent crash when no segment io key is found.

- edXVideoLocker/OEXLoginViewController.m
Change default keyboard type for reset password textfield to UIKeyboardTypeEmailAddress .
JIRA: https://openedx.atlassian.net/browse/MOB-1209
cc @aleffert
> Change default keyboard type for reset password textfield

- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXDownloadManager.m
App was crashing because app was not calling completion handler when download completes in background.
Now  added call for completion handler after updating database for downloaded video.
JIRA :  https://openedx.atlassian.net/browse/MOB-1160
cc @aleffert
> Crash fix on recent video screen

- edXVideoLocker/OEXInterface.m
Method 'startedDownloadForURL'  was inserting duplicate records for same videoId.
I removed this method . 
cc @aleffert
> Remove duplicate code for insert video data

- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
App was getting crash because  observer were getting called on deallocated player object .
I have added method to reset player. This method remove all player observer and reset player.
JIRA: https://openedx.atlassian.net/browse/MOB-1429
cc @aleffert
> App crash on my videos screen

- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.h
- edXVideoLocker/CutomePlayer/CLVideoPlayerControls.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.h
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXFrontCourseViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXVideoPlayerInterface.h
- edXVideoLocker/OEXVideoPlayerInterface.m
- edXVideoLockerTests/OEXInterFaceTests.m
In particular, the selectedCourseOnFront and selectedVideoUsedForAnalytics properties were used in a number of places. This patch encapsulates the relevant information into the places where it's used, removing intertwined state from that class, moving us toward a more testable interface local reasoning and write tests.
cc @jotiram @rahul-clarice @rohan-dhamal-clarice please review. thanks.
> Remove some global state from OEXInterface

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker.xcodeproj/xcshareddata/xcschemes/edXVideoLocker.xcscheme
- edXVideoLocker/OEXAppDelegate.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXDBManager.m
- edXVideoLocker/OEXDownloadManager.h
- edXVideoLocker/OEXDownloadManager.m
- edXVideoLocker/OEXFileUtility.h
- edXVideoLocker/OEXFileUtility.m
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXStorageInterface.h
- edXVideoLocker/OEXVideoPlayerInterface.m
- edXVideoLocker/VideoData.h
- edXVideoLockerTests/OEXDBTests.m
- edXVideoLockerTests/OEXFileUtilityTests.m
This significantly cleans up the file path code, removing a bunch of
stuff that is unnecessary or does not appear to be used. Additionally,
paths now funnel through central methods instead of duplicating code.
JIRA: https://openedx.atlassian.net/browse/MOB-1245
> Prevent data from being backed up EVER

- edXVideoLocker/OEXMyVideosViewController.m
We needed to load the video player before loading transcripts since they
go directly to the video player via a notification
JIRA: https://openedx.atlassian.net/browse/MA-358
> Fix issue with missing transcripts in recent videos

- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
We were resetting the video player before stopping the video, where
stopping the video is the thing that saves its location. There was
already a reset call after stop, so this just removes the seemingly
otherwise unnecessary one right before it.
> Fix issue saving video location when pressing Back

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/NSString+OEXFormatting.h
- edXVideoLocker/NSString+OEXFormatting.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXCustomTabBarViewViewController.m
- edXVideoLocker/OEXFindCourseInterstitialViewController.m
- edXVideoLocker/OEXGenericCourseTableViewController.m
- edXVideoLocker/OEXMyVideosSubSectionViewController.m
- edXVideoLocker/OEXMyVideosViewController.m
- edXVideoLocker/OEXRegistrationFieldSelectController.m
- edXVideoLocker/OEXRegistrationFieldValidator.m
- edXVideoLocker/en.lproj/Localizable.strings
- edXVideoLockerTests/NSString+OEXFormattingTests.m
This will make it easier for translators to understand what the
arguments mean and prevent them from having to deal with weird format
specifiers.
@sarina is this a better way to deal with the strings?
@hanningni please review. We'll also need to do this on Android.
> Switch format strings to use named parameters.

- edXVideoLocker/OEXAuthentication.h
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXLoginViewController.m
We don't need CSRF protection for the reset password token. It doesn't
make sense since you don't even have a session when you're doing reset
password.
> Remove unneeded fetch of CSRF token

- edXVideoLocker/OEXDBManager.m
- edXVideoLocker/OEXFileUtility.m
- edXVideoLockerTests/OEXFileUtilityTests.m
We need to recursively create the user directory in case Application
Support doesn't exist yet.
JIRA: https://openedx.atlassian.net/browse/MA-379
> Fix crash/odd behavior when first opening app

- edXVideoLocker/Main.storyboard
- edXVideoLocker/OEXAuthentication.h
- edXVideoLocker/OEXAuthentication.m
- edXVideoLocker/OEXCourseVideoDownloadTableViewController.m
- edXVideoLocker/OEXDownloadManager.m
- edXVideoLocker/OEXInterface.h
- edXVideoLocker/OEXInterface.m
- edXVideoLocker/OEXLoginViewController.m
- edXVideoLocker/OEXNetworkInterface.m
- edXVideoLocker/OEXRearTableViewController.m
- edXVideoLocker/OEXSession.h
- edXVideoLocker/OEXSession.m
- edXVideoLockerTests/OEXSessionTests.m
We didn't need those static passthrough methods on OEXAuthentication. They were redundant and it was confusing having them in two places. Eventually we'll replace it entirely with a thing that just generates requests.
> Remove unnecessary methods on OEXAuthentication. Misc cleanup

- edXVideoLocker/OEXGoogleAuthProvider.m
- edXVideoLocker/OEXGoogleSocial.h
- edXVideoLocker/OEXGoogleSocial.m
There's a case where the google profile info isn't coming through. I
can't reproduce it, but it seemed like we should at least be able to get
an email address as part of the google authenitcation, so this tries to
use that email first. It's more likely to be the primary email address
anyway.
JIRA: https://openedx.atlassian.net/browse/MA-390
> Prioritize google profile email address

- edXVideoLocker/OEXGoogleSocial.m
The block wasn't being copied so it was getting messed up when it went
out of scope.
JIRA: https://openedx.atlassian.net/browse/MOB-1689
> Fix crash when cancelling google auth

- edXVideoLocker/OEXFBSocial.m
- edXVideoLocker/OEXFacebookAuthProvider.m
- edXVideoLocker/OEXGoogleAuthProvider.m
- edXVideoLocker/OEXGoogleSocial.h
- edXVideoLocker/OEXGoogleSocial.m
- edXVideoLocker/OEXLoginViewController.m
In particular:
- We called "disconnect" in OEXGoogleSocial. This actually requires the
user to re-agree to use your app, which is never what we want.
- Need to better clear the completion handler in the auth provider code.
- Were clearing the entire session in several cases we really just
wanted to clear the handler.
> Improve interactions with google and facebook libraries.

- edXVideoLocker.xcodeproj/project.pbxproj
- edXVideoLocker/NSNotificationCenter+OEXSafeAccess.h
- edXVideoLocker/NSNotificationCenter+OEXSafeAccess.m
- edXVideoLocker/NSObject+OEXDeallocAction.h
- edXVideoLocker/NSObject+OEXDeallocAction.m
- edXVideoLocker/OEXRemovable.h
- edXVideoLockerTests/NSNotificationCenter+OEXSafeAccessTests.m
- edXVideoLockerTests/NSObject+OEXDeallocActionTests.m
This wraps up NSNotificationCenter so that observers can be removed
automatically, which is much less error prone.
> Add safe notification center utility.

- Source/OEXFBSocial.h
- Source/OEXFBSocial.m
- Source/OEXFacebookAuthProvider.m
- Source/OEXLoginViewController.m
- `OEXFBSocial` is no* longer a singleton.
- `completionHandler` isn't a property of `OEXFBSocial` anymore, it's only passed on `login`
- `isLogin()` is changed to a class method for convenient access.
- `OEXFacebookAuthProvider` code has been refactored accordingly.
> Discussed modifications to OEXFBSocial

- Source/CourseOutlineItemView.swift
The label should now truncate before the icon.
> Title label truncation before the icon

- Source/OEXAuthentication.m
- Source/OEXConfig.h
- Source/OEXConfig.m
@hanningni please review. We were sending a client secret but with the password grant type this isn't necessary.
cc @nasthagiri
> Remove client secret, which isn't actually necessary

- Source/CourseAnnouncementsViewController.swift
- Source/CourseDashboardCourseInfoCell.swift
- Source/OEXConfig.h
This will make it more obvious that the config might be empty and
prevent crashes when there's an invalid config.
> Add nullability annotations to OEXConfig

- Source/OEXPersistentCredentialStorage.h
- Source/OEXPersistentCredentialStorage.m
- Source/OEXSession.m
- Test/OEXMockCredentialStorage.h
- Test/OEXMockCredentialStorage.m
- Test/OEXPushNotificationManagerTests.m
- Test/OEXRouterTests.m
- Test/OEXSession+AuthorizationTests.swift
- Test/OEXSessionTests.m
- Test/edXTests-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
We needed to clear the cookie jar and any HTTP credentials on log out.
Rename OEXKeychainAccess to OEXCredentialStorage to reflect this broader
role.
> Ensure we clear the HTTP store on log out.

- Source/OEXFindCoursesViewController.m
This occurs if you don't have find courses set up (so there's just that
interstitial message) and you tap the "Close" button.
We were triggering a segue that was removed. Better to do it in type
checked code than use segues.
> Fix crash due to no longer existant segue

- edXVideoLocker/OEXSession.m
- edXVideoLocker/edXVideoLocker-Info.plist
The server created an infinite permanent redirect loop. We need to flush
the URL cache once to account for this.
https://openedx.atlassian.net/browse/MA-791
> MA-791 Find courses not displaying.

- Source/CourseDashboardViewController.swift
- Source/CourseOutlineViewController.swift
- Source/OEXFrontCourseViewController.m
- Source/OEXStyles+Swift.swift
This is still kind of hacky, but the solution of just offseting the text away resulted in funny behavior for long back strings.
> Better solution to hide back button text.

- Source/AuthenticatedWebViewController.swift
- Source/GradedSectionMessageView.swift
We appear to have run into an OS bug with text embedded inside a
webview's scrollview. This takes a slightly more complicated approach
that fixes the issue.
> Fix Graded header label on RTL.

- Source/OEXStyles+Swift.swift
- Source/UIDevice+OSVersion.swift
- edX.xcodeproj/project.pbxproj
iOS 7 doesn't support treating translucent as a UIAppearance property.
> Fix crash caused on iOS 7 only

- Source/OEXDateFormatting.m
- Test/OEXDateFormattingTests.swift
- edX.xcodeproj/project.pbxproj
Adapted the code to the format mentioned at [edx Docs](http://edx.readthedocs.org/projects/edx-platform-api/en/latest/enrollment/enrollment.html?highlight=date) 
` 2014-11-19T04:06:55Z`
Please let me know if that is consistent across the board
> OEXDateFormatting Tests

- Source/CourseContentPageViewController.swift
- Source/CourseOutlineModeController.swift
- Source/CourseOutlineQuerier.swift
- Source/CourseOutlineViewController.swift
- Source/CourseStructureAPI.swift
- Source/CourseUnknownBlockViewController.swift
- Source/DetachedStreamOperation.swift
- Source/HTMLBlockViewController.swift
- Source/NetworkManager.swift
- Source/OEXInterface+Swift.swift
- Source/OpenOnWebController.swift
- Source/Operation.swift
- Source/Result.swift
- Source/Stream.swift
- Source/VideoBlockViewController.swift
- Source/ViewTopMessageController.swift
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/MockNetworkManager.swift
- Test/StreamTests.swift
- edX.xcodeproj/project.pbxproj
This adopts a stream abstraction so it is easy for screens to update as
we load new server content.
Adapts the initial streams implementation to actually be usuable by real
code. This mainly involved giving it a better ownership story where a
stream explicitly owns its dependencies.
JIRA: https://openedx.atlassian.net/browse/MA-795
> Switch screens to use new streams library.

- Source/CourseOutlineHeaderView.swift
- Source/UIControl+OEXBlockActions.h
- Source/UIControl+OEXBlockActions.m
- Source/UserAPI.swift
- Source/ViewTopMessageController.swift
Added oex_removeActions to cater for setting unique actions. If you need to test this manually, you'll have to merge #244's changes first.
Alternatively, we could make a method in `UIControl+OEXBlockAdditions` named `oex_addUniqueAction`
@aleffert Thoughts?
> Bug Fix: Multiple VCs pushed due to multiple actions being set.

- Source/CourseContentPageViewController.swift
- Source/CourseOutline.swift
- Source/CourseOutlineQuerier.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CourseStructureAPI.swift
- Source/ListCursor.swift
- Source/NSObject+OEXDeallocAction.m
- Source/Stream.swift
- Test/CourseOutlineQuerierTests.swift
- Test/CourseOutlineTestDataFactory.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/ListCursorTests.swift
- Test/MockNetworkManager.swift
- Test/NetworkManagerTests.swift
- edX.xcodeproj/project.pbxproj
- Add tests for CourseOutlineQuerier.
- Modify CourseOutlineQuerier to group the block itself with its fully loaded
children and update users as appropriate. This will simplify traversing
between groups (like sections and subsections).
- Add cursor type for imperatively walking a list. If this ends up
having performance problems, the abstraction will easily let us
replace it with a memoized generator.
- Add utilities to CourseOutlineQuerier for horizontally walking the
tree at a given depth. This will be used iterate between units.
TODO: Update the UI to walk across the tree so we can go between units.
JIRA: https://openedx.atlassian.net/browse/MA-839
> Prepare data for scrolling between units.

- Source/BlockViewControllerCacheManager.swift
- Source/CourseContentPageViewController.swift
- edX.xcodeproj/project.pbxproj
Right now when we scroll between different pieces of course content, we reload the entire page each time. We should:
- Cache pages we've already visited.
- Optimistically load the following (and previous?) page.
We should flush this cache on memory warnings.
Note that preloading the surrounding pages might have funny behavior for videos where they start playing right away. If so, let's not worry about the optimistic loading stuff.
> Cache course content screens while scrolling between them

- Source/OEXMyVideosViewController.m
Bug Fixed. 
This shifting was done to cater for the overlapping in the case of RTL layout.
> iOS - Assessment - My videos - Recent videos - Pressing edit button the video titles weirdly shift over

- Source/OEXDownloadViewController.m
> iOS - Assessment - Download Video - Back arrow is missing in video downloading screen

- Source/CourseDataManager.swift
- Source/DataManager.swift
- Source/OEXRemovable.h
- Source/OEXRemovable.m
- Source/Stream.swift
- Test/CourseDataManagerTests.swift
- Test/CourseOutlineQuerierTests.swift
- Test/CourseOutlineTestDataFactory.swift
- Test/MockNetworkManager.swift
- Test/NetworkManagerTests.swift
- Test/OEXMockUserDefaults.h
- Test/OEXMockUserDefaults.m
- Test/OEXParsePushProviderTests.m
- Test/OEXSessionTests.m
- Test/edXTests-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
We weren't clearing the CourseDataManager on log out, so it was
returning stale queriers.
> Fix issue with stale data when logging out/in as a different user

- Source/CourseOutlineItemView.swift
> iOS - Assessment - Pressing download arrow next to video opened up the video component, instead of downloading

- Source/CourseLastAccessedController.swift
- Source/CourseOutlineModeController.swift
- Source/CourseOutlineQuerier.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CouseLastAccessed.swift
- Source/LastAccessedProvider.swift
- Source/OEXInterface+Swift.swift
- Source/OEXInterface.h
- Source/OEXInterface.m
- Test/CourseLastAccessedControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/MockLastAccessedProvider.swift
- edX.xcodeproj/project.pbxproj
- Separated last accessed from CourseOutlineViewController
- Specification implemented
What would be the correct way to implement unit tests for this? I tried subclassing `OEXInterface` to make a `MockInterface` but i can't because `getLastAccessedSectionForCourseID` an extension method in `OEXInterface+Swift`. Is it worth switching back to `Objc` for this method?
Other than that, the part that is unit testable is the `loading/setting` of the `LastAccessedVC` on Root and Leaf nodes. It is directly governed by `canShowLastAccessed` and `canUpdateLastAccessed`
Am i missing something here?
> Hide Last Accessed if block isn't visible in current context

- Source/CourseOutlineQuerier.swift
- Source/NetworkManager.swift
- Source/Stream.swift
- Test/CourseOutlineQuerierTests.swift
- Test/MockNetworkManager.swift
- Test/NetworkManagerTests.swift
- Test/StreamTests.swift
This makes it easier to check if the data can be refreshed or if it
already has a refresh in the pipeline.
For example, a network request will stop being active after the request
is over.
> Add a way to check whether a stream is live.

- Source/CourseAnnouncementsViewController.swift
- Source/en.lproj/Localizable.strings
Below are the observations/discrepancies in announcement screen:
1- In iOS top header there is no label. However, in android it is showing 'edX'. We should show "Announcements"
2- In iOS course card, Course name and course run is missing. However in android these information appearing. Currently behaves correctly
3- 'Announcement' text under course card is missing in iOS. Currently behaves correctly
4- The text infront of toggle button is 'Notification Enabled' in iOS. However, android is showing only 'Notifications'. We should show "Allow Notifications"
> iOS - Assessment - Discrepancies in announcement screens

- Source/CourseHandoutsViewController.swift
- In handouts section when user tap on link 'Example handout' nothing happens.
> iOS - Assessment - Handouts - On taping link nothing happens

- Source/Icon.swift
- Source/VideoBlockViewController.swift
- Source/en.lproj/Localizable.strings
In the portrait video mode, we currently fill the whitespace with a "This video's transcript is not available yet." image and text.
Until we have a chance to implement the rolling subtitle, I'd suggest we change this to some graphic along with text "Rotate your device to view this video in full screen".
> Replace "This video's transcript is not..." placeholder in portrait video player

- Source/CourseAnnouncementsViewController.swift
A redirect is now done, just like `CourseHandoutsViewController`
> iOS - Assessment - "courseware page" link in announcement section navigates user to unknown page

- Source/OEXRearTableViewController.m
Fixed. 
Forcing the MailComposeViewController to pick up TintColor
> Bug Fix : iOS - Assessment - Submit Feedback - Color issue with 'Cancel' and 'Send' buttons

- Source/DiscussionTopicsViewController.swift
Right now we're always showing a cancel button. This changes it to only
show if there is something to cancel and matches usage elsewhere in iOS.
> Only show discussion topic search cancel button when appropriate

- Source/Array+Functional.swift
- Source/CourseDashboardViewController.swift
- Source/CourseDataManager.swift
- Source/CourseOutlineModeController.swift
- Source/DiscussionAPI.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionTopic.swift
- Source/DiscussionTopicsCell.swift
- Source/DiscussionTopicsManager.swift
- Source/DiscussionTopicsViewController.swift
- Source/MenuOptionsViewController.swift
- Source/OEXRouter+Swift.swift
- Source/OEXRouter.h
- Source/OEXRouter.m
- Source/PSTAlertController+Selection.swift
- Source/PostsViewController.swift
- Test/Array+FunctionalTests.swift
- Test/CourseDashboardViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
- Makes the router methods only take the data needed to construct a new
controller, rather than read it from public state of the previous
controller in hte flow.
This allows us to significantly reduce local state
This prepares us to construct controllers within tests.
- Adds a discussion topics manager. This way we no longer need to
propagate the possible topics through screens that don't care about
them. This seemed better than changing the code to follow the strategy
of loading them from the net whenever we need them.
- Use the stream API for topics so we can better cache them. Since
topics change rarely this seems like a good exception for strategy of
not caching forums data.
- Move ``DiscussionPostsSort`` and ``DiscussionPostsFilter`` inside the API
abstraction barrier so clients …
> Refactor discussion topics and posts to follow best practices

- Source/CourseDashboardViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/CourseInfoAPI.swift
- Source/CourseOutlineQuerier.swift
- Source/LoadStateViewController.swift
- Source/NSError+OEXKnownErrors.h
- Source/NSError+OEXKnownErrors.m
- Source/NetworkManager.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXCourseInfoTabViewController.m
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXFrontCourseViewController.m
- Source/OEXInterface+Swift.swift
- Source/OEXRouter+Swift.swift
- Source/en.lproj/Localizable.strings
- Groups course start date info separate from course for easier passing
around.
- Introduces mechanism for automatically displaying styled errors.
- Checks course info before making request so we don't have to make
requests we know are going to fail.
TODO: Precheck in announcements and discussions
JIRA: https://openedx.atlassian.net/browse/MA-841
JIRA: https://openedx.atlassian.net/browse/MA-698
> Check access info in enrollments before showing course content

- Source/PostTitleByTableViewCell.swift
Before:
After:
Tried it with longer content too
> Fix issue with longer post counts getting truncated

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/NSAttributedString+Combination.swift
- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
- Test/DiscussionNewCommentViewControllerTests.swift
1a) Flagged would not show up on this screen 
1b) Pinned first then following 
1c) If you are following a pinned post show both
2) Let me clarify that we shouldn't be showing author information on this screen. I believe you're referring to pinning. If a post is pinned it can only be pinned by a staff or TA and that's the label we're sharing. Who pinned the post not the author. So there shouldn't be a case that a label appears without an icon.
> iOS - Update how posts show

- Source/OEXGoogleConfig.m
like all good 3p login libraries, our g+ crashes if no key is provided. This fix just keeps the g+ login disabled while no key is provided.
> hide G+ login on screen if no api key is provided MA-1154

- Source/DiscussionResponsesViewController.swift
@mikekatz @aleffert pl review...
Also, there is this weird use case where the post's `author` and `pin`-er can both be the same and result in a repetition... I'll discuss it with Mirza
> Showing pinned icon on pinned post inside responses

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/Icon.swift
- Source/OEXRouter+Swift.swift
- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
- Test/DiscussionNewCommentViewControllerTests.swift
Closed functionality is implemented, however ACCESS CONTROL (cases where a previllaged role can override the closed status) is pending.
> iOS - Discussions - Closed post functionality do not work

- Source/PostTitleByTableViewCell.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
Alright, here's the implementation we'll go with:
For the labels, we should show them as follows, in the marked orders:
1st (if present): "Pinned" should just show the "Pinned" icon (no text label).
2nd (if present): "Following" should show the star icon (no text label). (This is different than currently implemented – right now there is a text label.)
3rd (if present): Author label ("By Staff", "By Community TA", "By Admin") with no icon. Note that I've added the word "By" to further clarify that this label indicates authorship.
> Posts screen Cell details now match spec

- Source/Logger+OEXObjC.h
- Source/Logger+OEXObjC.m
- Source/Logger.swift
- Source/LoggingAnalyticsTracker.swift
- Source/OEXAnalyticsTracker.h
- Source/OEXEnvironment.h
- Source/OEXEnvironment.m
- Source/edX-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
- Introduces a standard logger with control over levels and which areas
(domains) of logs you're interested in.
To use: Just call ``Logger.log("SOME DOMAIN", "Some message")``
Note that all domains are filtered out by default. To read one just
pause Xcode and type ``call Logger.addDomain("SOME DOMAIN")`` into the
debug console.
This way we can have leave in logs, but not have them clutter up the
console unless you're interested in some particular area. For random
debug printing, you can feel free to keep using println or use
``Logger.logDebug("SOME DOMAIN", "SOME MESSAGE")``
- Takes advantage of the new logger to print out analytics messages when
the ANALYTICS domain is enabled.
> Add standard logging class. Use with analytics.

- Source/PostsViewController.swift
Bug caused due to an inconsistent state between the array count and the tableView rows
> iOS - Discussions - App crashes when user tap on any question from result of searching posts

- Source/CourseHandoutsViewController.swift
- Source/VideoBlockViewController.swift
In handouts we were only setting the listener to listenOnce which means
it will only send the cached version.
In the video block code we were adding a listener each time we reloaded
the stream. In practice we were only loading the stream once so it
didn't matter, but if we wanted to add a refresh feature this could lead
to a bug.
> Fix issues with setting up listeners in video block and handouts.

- Source/DiscussionCommentsViewController.swift
- Source/en.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
- script/Localizations.swift
Instead of going through horribly error prone strings tables directly, you can now just
do Strings.whatever. If the string has parameters, then it generates a
function. This should be way safer than passing format dictionaries
around.
All you need to do is update Localizable.strings and rebuild. Strings
will be generated automatically. The generation script will not run if
that file hasn't changed so it shouldn't significantly affect build
times.
It also does basic linting and found a string that had a non plural
version and a plural version. Fortunately, we weren't using the non
plural one so I removed it.
> Turn localizable.strings into a statically checkable file

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewCommentViewController.xib
- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/OEXStyles+Swift.swift
- Source/en.lproj/Localizable.strings
- Test/DateFormattingTests.swift
Since this affects multiple tickets, will update them tomorrow...
The functionality for the endorsed comments is now complete. Earlier comments would disappear when they were marked as answer.
Assorted changes were also made where they seemed necessary... In a separate PR, i will move all these cells to AutoResizingCells
> Endorsed responses UI + Business logic

- Source/CutomePlayer/OEXVideoPlayerSettings.swift
Settings class owns "settings" property which have closures that retain self.
> Fix retain cycle in video settings.

- Source/OEXStyles+Swift.swift
- Source/OEXVideoPlayerInterface.m
- Source/UIDevice+OSVersion.swift
There was a crash if you started watching a video and then hit the back
button. It appears to be caused by an iOS 8 only OS bug.
Also cleans up usage of isOSVersionAtLeast8 so we only check for the
one version back.
> Fix crash pushing back after watching video.

- Source/CourseOutlineHeaderCell.swift
- Source/CourseOutlineHeaderView.swift
- Source/CourseOutlineItemView.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DiscussionTopicCell.swift
- Source/DiscussionTopicsViewController.swift
- Source/GradedSectionMessageView.swift
- Source/GrowingTextViewController.swift
- Source/MenuOptionsViewController.swift
- Source/OEXStyles+Swift.swift
- Source/OfflineModeView.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Source/SeparatorInsetable.swift
- Source/UIAppearance+Swift.h
- Source/UIAppearance+Swift.m
- Source/edX-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
- Discussion Topics screen now matches spec + Auto Resizing for Topics with longer titles
- `UISearchBar` matches spec when on iOS9
- Match Add Comment and Add Response as navigation titles
- Pin the Search Bar to the top and add a separator
- Replace a "" String with a user-friendly string
This wasn't done because there's no graceful way to know if the user is following any posts for the endpoint : `/api/discussion/v1/course-v1:TestX+TestCourse+TestRun`
> Assorted changes to Discussion Screens

- Source/Icon.swift
- Source/IconMessageView.swift
- Source/VideoBlockViewController.swift
We were rotating a view 90 degrees to get its icon to be rotated 90
degress which screwed up autolayout. This switches to actually rendering
the icon rotated. Since this was a thing we were already doing in a one
off way, this generalizes the concept and creates a rotated icon
renderer. It also factors the icon renderer list to better catch
exhaustivity when not using FontAwesome.
JIRA: https://openedx.atlassian.net/browse/MA-1440
> Fix issue with bunched text.

- Source/OEXAppDelegate.h
- Source/OEXFrontCourseViewController.m
- Source/OEXLoginViewController.m
- Source/OEXRevealOptionsViewController+Protected.h
- Source/OEXRouter.m
- Source/UserProfileViewController.swift
- Source/edX-Bridging-Header.h
Note that this does not affect legacy controllers that have their own
fake navigation bars and will continue to add it manually.
> Have router be responsible for adding the side navigation button.

- Source/OEXInterface.m
- Source/OEXNetworkInterface.h
- Source/OEXNetworkInterface.m
- Source/OEXNetworkManager.h
- Source/OEXNetworkManager.m
I was seeing us call reloadData from inside a network callback on
OEXFrontCourseViewController, which of course made UIKit super unhappy.
Looking deeper, I found that the old network manager never dispatched
off the URL session's callback thread, so we were doing things like
updating UI on background threads.
This just shoves all the callbacks onto the main thread.
I'm sure there are still threading issues in that thing, but this
seeemed like the easiest way to resolve most of them.
Also gets rid of some faliures I discovered along the way.
> Fix issue with table updates happening in background when request fails.

- Source/DiscussionResponsesViewController.swift
- Source/en.lproj/Localizable.strings
The options should be: 
Discussion
Unanswered Question
Answered Question
We shouldn't differentiate between closed and not closed here.
> Navigation title now matches spec

- Source/CourseOutlineViewController.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/DownloadsAccessoryView.swift
- Source/NSAttributedString+Formatting.swift
- Source/NSAttributedString+OEXFormatting.h
- Source/NSAttributedString+OEXFormatting.m
- Source/NSError+OEXKnownErrors.m
- Source/OEXConfig.h
- Source/OEXConfig.m
- Source/OEXCourse.m
- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXCustomTabBarViewViewController.m
- Source/OEXDownloadViewController.m
- Source/OEXFrontCourseViewController.m
- Source/OEXGenericCourseTableViewController.m
- Source/OEXLocalizedString.h
- Source/OEXLocalizedString.m
- Source/OEXLoginViewController.m
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXRegistrationViewController.m
- Source/OEXUsingExternalAuthHeadingView.m
- Source/ProgressController.swift
- Source/UserProfileViewController.swift
- Source/en.lproj/Localizable.strings
- Test/NSAttributedString+FormattingTests.swift
- edX.xcodeproj/project.pbxproj
- script/Localizations.swift
Improve handling of parameterized strings to use ints instead of floats as the way it decides what case it's in (singular vs plural) and then pass an optional formatted string for more interesting cases like percent.
@mikekatz This should really have been in response to your comment on the other PR, but I got all crossed up on branches)
> Parameterize platform name

- Source/CutomePlayer/CLVideoPlayer.m
- Source/OEXCourseVideoDownloadTableViewController.m
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosViewController.m
- Source/OEXVideoPlayerInterface.h
- Source/OEXVideoPlayerInterface.m
These were getting covered up because we were adding the controller
directly to the front window. This change has us move to the front of
the root view controller. This is still not a great fix since the alerts
come in sideways, but it's an improvement over not showing them at all.
Unfortunately, the correct fix for this is either to:
1. Restore our more custom controls and add them as a subview of the
video player.
2. Significantly refactor the video player and its assorted containers
to handle landscape in a more disciplined way (migrate to
AVPlayerViewController and have the container be responsible for
fullscreen support + showing/hiding status bar, toolbar, and navigation
bar.
Also includes minor cleanup:
- Use system notification symbol instead of quoted string
- Remove unused …
> Show video speed/caption controls in landscape.

- Source/OEXMyVideosViewController.m
This was only on device, since the simulator wasn't sending any
orientation changed messages without prompting.
One more reason to avoid selectors - the method had been removed but it
was still triggered by a notification.
JIRA: https://openedx.atlassian.net/browse/MA-1417
> Fix crash on My Videos

- Source/PostsViewController.swift
We don't want the `newPostButton` to be part of the loadController contentView. This is because even if we have `0` results, the user can still create new posts.
On the contrary, the sort and filter buttons don't have the same desired behaviour. If there is an error/no posts, the buttons don't have any function... So we can keep them beneath the loadController contentView.
> iOS - Discussions - Refine posts filter and create new post button is missing in some topics

- Source/SegmentAnalyticsTracker.swift
The whole point of this was that ``screen`` events don't track any of
their properties so we need to actually do that. This fixes a bug where
we weren't actually passing them through.
> Fix missing properties for trackEvent with screen

- Source/DiscussionNewCommentViewController.swift
Something that came up while i was going through the code with the new guy. The item `enum` is either `.Post` or `.Response`. So, it made sense to rename it.
> DiscussionNewCommentViewController change

- Source/OEXCourse+Swift.swift
- Test/CourseDashboardViewControllerTests.swift
We have this horrible code that converts ``null`` responses to the
empty string, so this check was seeing "" because the endpoint was
returning "null". This fixes that check.
JIRA: https://openedx.atlassian.net/browse/MA-1352
> Fix issue hiding discussions tab

- Source/OEXLoginViewController.storyboard
It's hard to see because nibs are terrible, but the "scrollEnabled" flag was set to false
> Reenable scrolling on the login screen

- Source/Main.storyboard
There's a bunch of space on the right of this for the overlap with the
overlaying content. This shrinks the name and email to fit within that
area.
It also tweaks the bottom constraint for the email address so it
provides more even vertical spacing on extra long email addresses.
> Prevent long email addresses + names from getting hidden

- Source/AuthenticatedWebViewController.swift
Missed this when we were changed it from scrolling to a permaheader.
> Fix issue with scrollbar covered by graded content header

- Source/CourseOutlineItemView.swift
- Source/DownloadsAccessoryView.swift
The download view was getting squashed.
Before:
After:
> Fix issue with long titles in course outline

- Source/CourseOutlineViewController.swift
- Only hide pull refresh UI when stream goes inactive (i.e. the network
request is done).
- Factor to use ``transform`` instead of a sequence of backedstreams - less
imperative.
> Improve behavior of outline pull refresh

- Source/CutomePlayer/CLVideoPlayerControls.m
Issue was because of TapGesturesRecognizer was not ignoring gesture in case of options tableView (Closed Caption, Video Speed).
https://openedx.atlassian.net/browse/MA-1666
> Closed captions' and 'Video Speed' do not work

- Source/CourseContentPageViewController.swift
- Source/CourseOutlineTableSource.swift
- Source/CutomePlayer/CLVideoPlayer.m
- Source/OEXVideoPlayerInterface.m
As best I can tell, MPMoviePlayer is a piece of junk. Even if you
deallocate it and call -stop. It can still finish loading your video and
play audio. Setting the contentURL to ``nil`` in dealloc seems to fix
that.
Additionally, disable caching for videos since having multiple videos
running concurrently and offline seems to cause bad interactions that
prevent videos from playing properly.
I'm hoping that things should improve if we switch to
AVPlayerViewController.
> Aggressively stop videos.

- Source/CutomePlayer/CLVideoPlayer.m
set contentUrl nil if it has some value otherwise it will cause crash because controls are nil after reseting player 
https://openedx.atlassian.net/browse/MA-1727
> Crash fixed on All Videos

- Test/CourseContentPageViewControllerTests.swift
We had a listener which was never getting removed. It should really just
be automatically getting removed once it gets dealloced. So this probably
indicates a memory cycle in the tests somewhere. I took a pass at the
actual app and that leak doesn't seem to be there, so I don't think it's
a serious problem - though we should fix it.
But in the mean time this fixes the tests.
> Fix unit tests

- script/Localizations.swift
We were doing things like ``Strings.courseabout.foo``. Now we are doing ``Strings.CourseAbout.foo``
> Properly capitalize nested scopes for static string generator

- Source/CourseCardView.swift
- Source/OEXMyVideosViewController.m
When we added the optional tap action on the course card, it overrode the table
view's tap gesture, causing the my videos tap on a course to break.
This fixes it in two ways:
1. The card gesture will only activate if the card view has a tapAction
2. Switch the my videos table to use the card's tapAction property.
This makes the code more direct and simpler.
JIRA: https://openedx.atlassian.net/browse/MA-1792
> Fix broken tap on course card in my videos.

- Source/DetachedStreamOperation.swift
- Source/Operation.swift
- Source/UserAgentOverrideOverrideOperation.swift
I'm hoping that having an explicit done block makes it harder to forget
to finalize the operation.
> Change interface for ``Operation`` to make it easier to end one

- Source/DetachedStreamOperation.swift
- Source/Stream.swift
- Test/StreamTests.swift
- Test/XCTestCase+Async.swift
These are needed for pagination + testing pagination, respectively.
Accumulate combines a stream of arrays into one big array.
Delay delays the output of a stream over time. Easy way to make
something async.
> Add stream combinators 'accumulate' & 'delay'

- Source/DiscussionAPI.swift
- Source/NetworkManager.swift
- Source/NetworkPaginator.swift
- Source/PaginatedFeed.swift
- Source/PaginationInfo.swift
- Source/Paginator.swift
- Test/PaginationInfoTests.swift
- Test/PaginatorTests.swift
- edX.xcodeproj/project.pbxproj
The goal here is to get rid of NetworkPaginator and replace it with the new
PaginationController which is more general, testable, and has a simpler
interface
Next steps are:
1. Adopt PaginationController in CourseCatalogViewController.
2. Replace NetworkPaginator where it is currently used in the
discussions code.
At that point we'll have one system where the differences in payload
content (whether there's a "pagination" package or not) are abstracted
into the specific Paginator implementation used.
> Introduce pagination primitives

- Source/CourseCardView.swift
- Source/CourseCardViewModel.swift
- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogViewController.swift
- Source/CourseDashboardViewController.swift
- Source/CoursesTableViewController.swift
- Source/OEXFrontCourseViewController.m
- Source/OEXMyVideosViewController.m
- Source/RemoteImage.swift
- Source/UserProfile.swift
We don't want the course catalog to persist all the course images.
Factor CourseCardViewModel to better break apart the different cases.
This also makes the environment part of the model setup instead of the view,
which seems like a more natural separation of concerns and should make
it harder to forget, which we've had a couple bugs about.
> Add non persistence support to remote image.

- Source/NetworkManager.swift
- Source/Result+JSON.swift
- Source/Result.swift
- Source/Stream.swift
- Test/Result+Assertions.swift
Pretty sure the necessity of this was removed with Swift 2.
> Remove unnecessary Box wrapper for Result.

- QLearnSDK/DiscussionObjectModel.swift
- Source/DiscussionAPI.swift
- Source/DiscussionCommentsViewController.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionNewPostViewController.swift
- Source/DiscussionResponsesViewController.swift
- Source/OEXRouter+Swift.swift
- Source/PostTableViewCell.swift
- Source/PostsViewController.swift
- Test/DiscussionNewCommentViewControllerTests.swift
We had four types:
DiscussionThread, DiscussionComment, DiscussionResponse, DiscussionPost
Plus an enum DiscussionPostItem which was DiscussionPost +
DiscussionResponse.
Further, these types weirdly conflated fields from both threads and
comments.
Based on the types we actually get back, what we actually needed was just:
DiscussionThread and DiscussionComment.
This rips out those unneeded types and removes the redundant information
from the thread being shoved into a response.
There is more renaming that really wants to happen here, but this was
already getting long.
> Factor forums models to remove redundancy

- Source/CourseCatalogDetailViewController.swift
- Source/CourseOutlineViewController.swift
- Source/LoadStateViewController.swift
- Source/OEXCourseInfoViewController.m
- Source/OEXRegistrationViewController.m
- Source/OEXStatusMessageViewController.h
- Source/OEXStatusMessageViewController.m
- Source/UIViewController+Overlay.swift
- Source/VideoBlockViewController.swift
- Test/CourseCatalogDetailViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
Provide standard way to show an overlay message on a view controller.
Does *not* update all messages to be in that style or use that API. In
particular, some of the Objective-C based screens still use the weird
custom nav bar stuff and so depend on the extra stuff
OEXStatusMessageViewController is doing. And the error in the profile
editor was sufficiently different in style and behavior that I didn't
want to mess with it at at this moment.
This new implementation doesn't rely on a singleton, supports custom
views displayed in a standard way, and is desgined around autolayout.
This is really just going to be used to make it easier to show the
large offline info message when we modernize the course list.
> Start deprecation of OEXStatusMessageViewController.

- Source/CoursesAPI.swift
- Source/EnrollmentManager.swift
- Source/Feed.swift
- Source/NSNotificationCenter+SafeSwift.swift
- Source/Stream.swift
- Source/UserCourseEnrollment.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/EnrollmentManagerTests.swift
- Test/FeedTests.swift
- Test/MockEnrollmentManager.swift
- edX.xcodeproj/project.pbxproj
This introduces a new class ``EnrollmentManager`` which is responsible
for keeping track of the user's current enrollments. It will replace
uses of OEXInterface for the same purpose as part of removing uses of
that class.
Currently the app depends on the main course list screen to actually load the
enrollments. This way we can load enrollments without involving any UI
classes.
> Introduce enrollment manager

- Source/ContentInsetsController.swift
- Source/CourseOutlineViewController.swift
- Source/OfflineModeController.swift
This way if you run the tests while offline you won't display an offline
header unless you deliberately mean to.
> Get reachability for offline header from environment

- Source/CourseDashboardViewController.swift
- Source/CourseDataManager.swift
- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/OEXFrontCourseViewController.m
- Source/OEXRouter+Swift.swift
- Test/CourseDashboardViewControllerTests.swift
This way we can show a course without having to have previously loaded
it in the enrollments list. This will enable us to jump directly to a
course after enrolling in it and should generally make working with
things like hyperlinks a little simpler.
> Swap course dashboard to take an id instead of a course

- Test/EnrollmentManagerTests.swift
This only fails on travis, so I don't think the underlying code needs to
be fixed and I'd like other people to get green builds for unrelated
changes.
> Temporarily disable failing test until we can figure out what's wrong with it

- Source/CourseOutline.swift
- Source/CourseOutlineQuerier.swift
- Test/CourseOutlineQuerierTests.swift
If there's bad data coming in from the server, we might end up in a case
where we get asked for a child that doesn't exist. Instead of giving up
in that case, we should just filter it out.
JIRA: https://openedx.atlassian.net/browse/MA-1972
> Filter out missing children instead of failing

- Source/OEXRegistrationViewController.h
- Source/OEXRegistrationViewController.m
- Test/OEXRegistrationViewControllerTests.swift
- edX.xcodeproj/project.pbxproj
We were never setting the environment in init.
Another tragic only possible in objc bug.
This adds a test to ensure that analytics fire when we register, which
will also only work if the env is setup.
> Fix issues in registration due to missing environment

- Source/UserProfileViewController.swift
We'll naturally get no avatar URL if the profile is limited and a user
should always be able to see their own avatar.
JIRA: https://openedx.atlassian.net/browse/MA-2048
> Always use avatar if available

- Source/NSObject+SafeKVO.swift
- Test/NSObject+SafeKVOTests.swift
KVO has a stupid system where you have to remove an observer before the
observed object gets deallocated. We were being too clever about weak
references and so the observed object could get deallocated before the
observer. Ideally, we'd just nuke the listener in that case, but we
can't trigger an event *just before* the observed object gets
deallocated (at least without swizzling, which seems excessive).
So instead, we update the pattern to explicitly retain the observer.
This is typically how lifetimes work anyway, so it shouldn't be an
issue.
Also uses a new way to get a unique id for the association with better guarantees about addresses not changing.
Unfortunately, I couldn't actually reproduce the related crash, but it's
clear from the stack trace that this is the underlying issue. …
> Fix crash with KVO lifecycle

- Source/edX-Info.plist
This is a new thing in iTunesConnect that lets you bypass those
repetitive are you using crypto screens. Since we don't use any
non-exempt crypto, this seemed like an easy thing to do.
> Set uses non-exempt encryption key to false

- Source/OEXVideoEncoding.h
- Source/OEXVideoEncoding.m
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
When we added the youtube redirect profile, we prioritized that ahead of
the fallback video (unprocessed video of unknown size). This seemed kind
of reasonable since some of those videos are quite large and don't work
well on mobile. But we're getting user complaints about offline videos
vanishing and obviously the youtube videos obviously don't work offline,
so swap this back around. This is also more consistent with what Android
is doing.
JIRA: https://openedx.atlassian.net/browse/MA-2256
> Prefer fallback video to youtube

- Source/Core/Code/PersistentResponseCache.swift
- Source/Core/Test/Code/OEXMetaClassHelpers.h
- Source/Core/Test/Code/OEXMetaClassHelpers.m
- Source/Core/Test/Code/PersistentResponseCacheTests.swift
- Source/Core/Test/SupportingFiles/edXCoreTests-Bridging-Header.h
- edX.xcodeproj/project.pbxproj
This is pretty unfortunate. When we moved the PersistentResponseCache
from the "edX" module to the edXCore module, it broke unarchiving cache
entries - since NSCoding looks things up by class name and being in a
different module secretly gives you a different class name - even though
that's not visible to the user.
This change adds some rerouting logic for the unarchiver to better
handle missing classes and route the cache entries to a class that
actually exists.
> Fix crash reading cache entries.

- Source/LoggingAnalyticsTracker.swift
- Source/OEXAnalyticsTracker.h
- Source/OEXAuthentication.m
- Source/OEXSession.m
- Source/SegmentAnalyticsTracker.swift
- Test/MockAnalyticsTracker.swift
We can't reproduce but there's a suspicion that the keychain isn't
saving properly for some users. This unfortunately doesn't fix that
problem, but it should hopefully allow them to log in for a session +
prevent the app from crashing.
> Work around login crash

- Source/Core/Code/NetworkManager.swift
- Source/Core/Test/Code/NetworkManagerTests.swift
- Source/NetworkManager+Authenticators.swift
- Test/NetworkManager+AuthenticatorTests.swift
The Oauth refresh work made it so that all requests with an
empty response will log the user out. Instead, we let the
request proceed and post a debug message.
@mikekatz Please review
> Do not always logout for empty response

- Source/Core/Code/OEXDateFormatting.m
- Source/DataManager.swift
- Source/EnrolledCoursesViewController.swift
- Source/OEXEnvironment.m
- Source/UserPreference.swift
- Source/UserPreferenceAPI.swift
- Source/UserPreferenceManager.swift
- Test/CourseCardViewModelTests.swift
- Test/TestRouterEnvironment.swift
- Test/UserPreferenceManagerTests.swift
- edX.xcodeproj/project.pbxproj
[TNL-5106](https://openedx.atlassian.net/browse/TNL-5106)
Previously, app used phone's local time zone for all dates. Now, it uses the user's time zone set on the web platform, or UTC if unset.
You can use Kevin's Test Course on mobile-dev sandbox to test dates.
The course end date is 09/01/2016 0:00 UTC. 
Depending on the User's time zone preference (set on the sandbox) it should be reflected in the course card. 
> Add Time Zone to iOS

- Source/CertificateViewController.swift
- Source/JSONFormBuilder.swift
- Source/JSONFormBuilderTextEditor.swift
- Source/OEXRegistrationFormField.m
- Source/en.lproj/Localizable.strings
Removing edX from localizable strings.
Replacing edX with platform name if it is being used from json files like registration.json and profiles.json when view is populating 
Jira: https://openedx.atlassian.net/browse/MA-2472
> Remove "edX" string from localizable.strings

- openedx.yaml
This fixes the owner of the repo to be a group that actually exists on github.
No testing needed.
> Use the right name for the repo owner

- Source/OEXLoginViewController.m
- Source/UIAlertController+OEXBlockActions.swift
- Test/UIAlertController+OEXBlockActionsTests.swift
- edX.xcodeproj/project.pbxproj
[MA-2345](https://openedx.atlassian.net/browse/MA-2345)
A `UIAlertController` extension created for error messages to be used for a11y. Native error messages implemented on the Sign In screen.
1. Navigate to the Sign In screen
2. Enter wrong credentials or disconnect from the internet
3. Click the Sign In button
4. Error message should be displayed in `UIAlertController`
> Native error messages used for Sign In

- Source/OEXColors.swift
- Source/OEXColorsDataFactory.swift
- edX.xcodeproj/project.pbxproj
[MA-2877](https://openedx.atlassian.net/browse/MA-2877)
Fallback data factory and colors have been added to all respective methods in the OEXColors.swift instead of assertions as assertions do not work on distribution builds.
Following the merge of this PR, if the main color scheme is changed for a project it is also recommended to update OEXColorsDataFactory.swift (contains fallback colors) with the same values to have a more reliable fallback color scheme.
1. Try removing colors.json to see if the app picks up the fallback colors
2. Try corrupting the data in colors.json to see if the app picks up the fallback colors
3. Try giving a random color key to see if the app returns the proper fallback color
If you've been tagged for review, please check your corresponding box once you've given …
> Add fallbacks to OEXColors

- Source/OEXRegistrationFormField.m
Follow up from https://github.com/edx/edx-app-ios/pull/812
Oddly, this was never used. I don't think any of the labels we used ever had edX hardcoded in it.
I also checked for `stringByReplacingOccurrencesOfString:@"edX"` but didn't find anymore so I hope this is the last one.
> Removed hardcoded edx string swap

- Source/OEXMyVideosSubSectionViewController.h
- Source/OEXMyVideosSubSectionViewController.m
- Source/OEXMyVideosSubSectionViewController.storyboard
- Source/OEXMyVideosViewController.h
- Source/OEXMyVideosViewController.m
- Source/OEXMyVideosViewController.storyboard
- Source/OEXRouter.m
- Source/en.lproj/Localizable.strings
[MA-2807](https://openedx.atlassian.net/browse/MA-2807)
Mock navigation has been removed from My Videos, and native navigation bar is not used instead. All navigation elements have also been assigned accessibility labels as needed.
N/A
- Turn on VO
- Navigate to My Videos
- Items in navigation bar should be pronounced in consistency with other screens.
> Remove MockNav from My Videos

- Source/OEXLoginSplashViewController.xib
[MA-](https://openedx.atlassian.net/browse/MA-)
When the application is launched, we see the LoginSplashViewController. Unfortunately, the hierarchy of that xib was accidentally reordered in PR #811. The image if LoginSplashViewController was moved to the front, hiding all buttons. This PR moves that image back to the background of the xib, where it should be.
I tested this on the latest version of master as of 2pm PST on 17 October, 2016.
If you've been tagged for review, please "Start a review" with the Github GUI.
> Bugfix: login buttons were hidden on launch

- .travis.yml
This PR fixes an intermittent build error.
([example build](https://travis-ci.org/appsembler/edx-app-ios/jobs/169224426)):
```
xcodebuild[1626:6385] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fcb44bb8320>
```
This is resolved by adding more time between tests. We add a `sleep 5` to after_success in .travis.yml on the recommendation of this [discussion](https://github.com/travis-ci/travis-ci/issues/4725). This seems to resolve the issue.
Here's an ([example build](https://travis-ci.org/appsembler/edx-app-ios/jobs/169224426)) where this error was triggered.
If you've been tagged for review, please "Start a review" with the Github GUI.
> Travis builds should not fail due to 'peer refused channel request' error

- .travis.yml
This PR fixes most intermittent build errors by asking Travis to run tests up to 3 times if they fail.
The majority of failures contain this error:
`2016-10-21 00:38:44.199 xcodebuild[3012:7482] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/edX-exjjepupggxqgdchtzhsvbkvnvpy/Logs/Test/4180ADF2-994D-4B06-8D23-8AA979D8AD6C/Session-edXTests-2016-10-21_003215-f0eCyl.log" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/edX-exjjepu …
> Travis builds should automatically retry up to 3 times if they fail

- .travis.yml
At the end of all travis builds, we will no longer see "shell_session_update warning".
This fix is discussed in detail here: https://github.com/travis-ci/travis-ci/issues/6307
`/Users/travis/build.sh: line 109: shell_session_update: command not found`
This is resolved by loading rvm if we don't have it on the server. We add a get rvm head || true to before_script in .travis.yml on the recommendation of this discussion. This seems to resolve the issue.
Open any travis build of edx-app-ios and you will see "shell_session_update warning" at the end of the build printout. With this fix, you no longer see this warning.
If you've been tagged for review, please "Start a review" with the Github GUI.
> Travis should not show shell update warning

- Source/OEXVideoSummary.m
[MA-2965](https://openedx.atlassian.net/browse/MA-2965)
Adding fallback as default encoding to view videos in My Videos, if server didn't return any encoding for a video. In courseware it will be considered as unsupported video but if user has any downloaded video in db without encoding then user can view it.
> Adding fallback as default encoding to view a video in my videos.

- Source/OEXLoginSplashViewController.h
- Source/OEXLoginSplashViewController.m
- Source/OEXLoginSplashViewController.xib
- Source/OEXRouter+Swift.swift
[OSPR-1549](https://openedx.atlassian.net/browse/OSPR-1549 )
Make the sign up button in LoginSplash the same as Login and Registration by removing the background image in OEXLoginSplashViewController.xib and using the method ```applyButtonStyle: withTitle:``` in OEXLoginSplashViewController.m
> Remove background image from sign up button

- Source/DiscussionNewCommentViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2964](https://openedx.atlassian.net/browse/MA-2964)
Add Response screen has been made a11y compliant by adding VO descriptions to all components.
- Code review: @saeedbashir, @BenjiLee
> Accessibility labels for Add Response Screen

- Source/RevealViewController.swift
[MA-2972](https://openedx.atlassian.net/browse/MA-2972)
This PR aims to fix a bug that was causing VO to read elements from the side menu whenever a modalViewController was dismissed.
1. Login to edX app. 
2. Tap on user profile section. 
3. Tap on edit button. 
4. Switch on 'VoiceOver'. 
5. Tap on 'Change' button to change photo. 
6. Tap on 'Take photo/Choose a photo'.
7. Dismissing the VC should shift the focus to the on screen elements.
- Code review: @saeedbashir @BenjiLee
> VO fix for modalViewControllers

- Source/DiscussionCommentsViewController.swift
- Source/DiscussionHelper.swift
- Source/DiscussionNewCommentViewController.swift
- Source/DiscussionResponses.storyboard
- Source/DiscussionResponsesViewController.swift
- Source/PostsViewController.swift
- Source/en.lproj/Localizable.strings
[MA-2963](https://openedx.atlassian.net/browse/MA-2963)
This PR aims to make Responses and Comments screens a11y friendly by integrating VO descriptions and hints to all respective elements of the screens.
- Code review: @BenjiLee, @saeedbashir
> a11y optimizations for Responses & Comments

- Source/CutomePlayer/CLVideoPlayerControls.h
- Source/CutomePlayer/CLVideoPlayerControls.m
- Source/OEXVideoPlayerInterface.m
[MA-2405](https://openedx.atlassian.net/browse/MA-2405)
This PR aims to fix an issue with the video player for courseware, where the audio starts playing even if the user moves to the next non-video unit.
1) Open a video block in courseware
2) Navigate to next block a little before the video starts playing
3) The audio should not start to play after navigation (Earlier the audio kept playing after navigation to the next block)
- Code review: @BenjiLee, @saeedbashir
> Stop audio from playing after switching screens

- Source/SegmentAnalyticsTracker.swift
It looks like we are double sending events when we don't want to be.
https://github.com/edx/edx-app-ios/blob/master/Source/SegmentAnalyticsTracker.swift#L83
https://github.com/edx/edx-app-ios/blob/master/Source/SegmentAnalyticsTracker.swift#L65
> Remove screen event for Firebase

- Source/CourseAnnouncementsViewController.swift
[MA-](https://openedx.atlassian.net/browse/MA-)
When the heading or content is non-empty, we don't want it to display as, for example: Optional("name")
All announcement headings have Optional in them. Merge this and that goes away.
> On announcements, display heading & content as non-optional strings

- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[MA-3157](https://openedx.atlassian.net/browse/MA-3157)
We are encouraging to upload all videos by edX video pipeline so that's why we are dropping support fallback encoding. Users can still view their downloaded fallback videos in my videos section.
> Dropping Fallback video encoding

- Source/CourseCatalogDetailView.swift
- Source/CourseCatalogDetailViewController.swift
- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/en.lproj/Localizable.strings
[OSPR-1781](https://openedx.atlassian.net/browse/OSPR-1781)
This PR disables the enroll button in a course if it is invite only and changes the text.
For this PR to work it depends on this other [PR](https://github.com/edx/edx-platform/pull/15223)
- Have a course invite only.
- Find the course in the app.
- Click on it, should see button disabled.
cc @marcotuts @gsong
> Add invitation only button to course detail view

- Source/Dictionary+SafeAccess.swift
OEXLogError is a Objective-C variant of of Logger.logError that was being used in swift code.
> Replacing OEXLogError with Logger.logError

- Source/CourseDashboardViewController.swift
- Source/OEXConfig+AppFeatures.swift
- Test/CourseDashboardViewControllerTests.swift
[OSPR-1827](https://openedx.atlassian.net/browse/OSPR-1827)
This PR shows or hide the announcements tab in ```CourseDashboardViewController.swift``` depending on the flag ```ANNOUNCEMENTS_ENABLED``` added in ```ios.yml```.
This flag is for the whole app and not course specific.
Add the flag to ```ios.yml``` and change the values of  ```ANNOUNCEMENTS_ENABLED```
```
API_HOST_URL: ''
OAUTH_CLIENT_ID: ''
ENVIRONMENT_DISPLAY_NAME: ''
PLATFORM_NAME: ''
PLATFORM_DESTINATION_NAME: ''
FEEDBACK_EMAIL_ADDRESS: ''
DEBUG: false
ORGANIZATION_CODE: ''
PUSH_NOTIFICATIONS: false
MY_VIDEOS_ENABLED: true
ANNOUNCEMENTS_ENABLED: false
COURSE_ENROLLMENT:
ENABLED: true
TYPE: 'native'
COURSE_SHARING_ENABLED: false
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
USER_PROFILES_ENABLED: true
BADGES_ENABLED: …
```
> Add flag ANNOUNCEMENTS_ENABLED

- Source/OEXConfig+AppFeatures.swift
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[OSPR-1850](https://openedx.atlassian.net/browse/OSPR-1850)
This PR uses the ```fallback_video``` when not using video pipeline by setting the variable ```USING_VIDEO_PIPELINE``` added in ```ios.yml```.
Add the flag to ```ios.yml``` and change the values of  ```USING_VIDEO_PIPELINE```
```
API_HOST_URL: ''
OAUTH_CLIENT_ID: ''
ENVIRONMENT_DISPLAY_NAME: ''
PLATFORM_NAME: ''
PLATFORM_DESTINATION_NAME: ''
FEEDBACK_EMAIL_ADDRESS: ''
DEBUG: false
ORGANIZATION_CODE: ''
PUSH_NOTIFICATIONS: false
MY_VIDEOS_ENABLED: true
COURSE_ENROLLMENT:
ENABLED: true
TYPE: 'native'
COURSE_SHARING_ENABLED: false
DISCUSSIONS_ENABLED: true
CERTIFICATES_ENABLED: true
USER_PROFILES_ENABLED: true
BADGES_ENABLED: true
REGISTRATION_ENABLED: true
SEGMENT_IO:
SEGMENT_IO_WRITE_KEY: ''
ENABLED: false
USING_VIDEO_PIPELINE: …
```
> Add flag USING_VIDEO_PIPELINE to support fallback video

- .tx/config
[LEARNER-2509](https://openedx.atlassian.net/browse/LEARNER-2509)
Renaming json files of profile for transifex script. Now on, Android and iOS will be uploading profile json files under the same name so that only one copy of files will be on transifex for translations.
> Rename profile localizable files to make it same for both platforms

- Source/OEXLoginSplashViewController.m
[OSPR-1879](https://openedx.atlassian.net/browse/OSPR-1879)
This PR sets the correct font use in ```fonts.json``` for the ```signInButton```  in ```OEXLoginSplashViewController.m```
Run the app and see that is using the correct font
cc @marcotuts @gsong
> Use correct font for signInButton in OEXLoginSplashViewController.m

- Source/CoursesTableViewController.swift
[LEARNER-2907](https://openedx.atlassian.net/browse/LEARNER-2907)
Course cards do not announce the right course when using Voiceover on iOS
> Course cards do not announce the right course when using Voiceover on iOS

- Source/RevealViewController.swift
[OSPR-1967](https://openedx.atlassian.net/browse/OSPR-1967)
Currently, if you use ```rearViewController.view.subviews``` on Arabic lang it returns nil and the app bombs.
By changing it to ```drawerViewController.view.subviews``` the app will work again in Arabic.
Run the app in Arabic and see that it doesn't bomb.
cc @marcotuts
> Check if RTL to use correct view controller when using the drawer

- Source/CourseOutlineQuerier.swift
- Source/CourseVideoTableViewCell.swift
- Source/OEXDownloadViewController.m
- Source/OEXInterface.m
- Source/OEXNetworkConstants.h
- Source/OEXVideoSummary.h
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
Allows HLS videos to be streamed.
And because HLS videos cannot be downloaded using our current video download library, then fallback video URLs are used for downloading.  
The following sources are used to locate a valid download URL:
* available encodings, when the Video Pipeline is enabled.
* HTML5 sources, when the Video Pipeline is disabled.
**JIRA**
[OSPR-2019](https://openedx.atlassian.net/browse/OSPR-2019)
Functionality depends on API changes in https://github.com/edx/edx-platform/pull/16590, but the app continues to work even if this change is not deployed yet.
Builds on https://github.com/edx/edx-app-ios/pull/1014, which differentiates between streamable and downloadable video URLs.
We'd like to get this merged before the next edx-app-ios release.
Ensure that the changes from …
> Allow HLS video streaming, and use fallback video sources as download URL

- Source/OEXRouter+Swift.swift
[OSPR-2163](https://openedx.atlassian.net/browse/OSPR-2163)
If the flag ```TAB_LAYOUTS_ENABLED``` is set to ```True``` the navigation stack gets messed up when trying to view a course through the ```Find Courses``` tab. When you access a course and go back it doesn't display the ```EnrolledTabBarViewController``` but instead ```EnrolledCoursesViewController```. The tabs ```Courses``` and ```Find Courses``` disappear. The ```Account``` and ```Profile``` buttons also disappear so it is impossible to logout from the app. The only way to make appear again the correct layout is to close the app completely and open it again.
Set the flag ```TAB_LAYOUTS_ENABLED``` to ```True```. Run the and check that when going to a course through the ```Find Courses``` tab when you go back it actually shows …
> Fix tab layout navigation

- Source/CourseContentPageViewController.swift
[OSPR-2185](https://openedx.atlassian.net/browse/OSPR-2185)
This PR fixes the color of the status bar when seeing a component.
Before
After
cc @nedbat
> Fix status bar color

- Source/AuthenticatedWebViewController.swift
[LEARNER-4372](https://openedx.atlassian.net/browse/LEARNER-4372)
The issue was introduced because Apple had made some changes in WebKit in their latest iOS SDK (Xcode 9.x & iOS 11) and didn't inform developers about this change. A number of people have reported this issue. Version 2.13.2 was the first version which was built by latest Xcode and in our case App is crashing if mobile_dates_fragment or any xBlock returns an error code of 500 error codes family
> Crash fix if course_dates_fragment or xBlock end points returns 500

- Source/edX-Info.plist
[LEARNER-4407](https://openedx.atlassian.net/browse/LEARNER-4407)
Although edX is not interacting with *Contacts* directly, but a user can save or create a new contact from comments screen by using force touch functionality because `dataDetectorTypes` is enabled for `UITextView`. From the force touch menu, a new contact can be created with the phone number, or the phone number can be added to an existing contact. Once the user taps on *Add To Contact*, the application will try to request access to the address book. If `info.plist` don't have NSContactsUsageDescription, the app will crash.
> Adding NSContactsUsageDescription privacy value

- Source/OEXStyles+Swift.swift
[OSPR-2318](https://openedx.atlassian.net/browse/OSPR-2318)
This PR sets the correct tint color for the `UIToolbar`. Currently, it is using `navigationBarColor()` and it should be using `navigationItemTintColor()`
Before
After
cc @marcotuts
> Use correct tint color for UIToolbar

- Source/StartupViewController.swift
Accessibility identifier got missed during the implementation of new landing screen. It is required for the implementation of [LEARNER-4692](https://openedx.atlassian.net/browse/LEARNER-4692) by *Automation Team*.
> Accessibility identifier for message label on Startup Screen

- Source/CourseContentPageViewController.swift
[LEARNER-3208](https://openedx.atlassian.net/browse/LEARNER-3208)
The crash is irreproducible so I'm not sure either this patch will fix it completely. I have applied the solutions which were mentioned by so other developers on StackOver flow. The first solution which I have applied can be found at [link](https://stackoverflow.com/questions/20004310/invalid-parameter-exception-thrown-by-uiqueuingscrollview) and the second solution which I have applied can be found at [link](https://stackoverflow.com/questions/24000712/pageviewcontroller-setviewcontrollers-crashes-with-invalid-parameter-not-satisf/24749239#24749239).
> Patch for UIPageViewController crash

- Source/AgreementTextView.swift
- Source/AgreementURLsConfig.swift
- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
- Source/OEXUserLicenseAgreementViewController.m
- Test/AgreementURLsConfigTests.swift
- edX.xcodeproj/project.pbxproj
This PR adds the ability for the application to read the URLs for EULA, TOS and the Privacy Policy from the configuration. This is useful for WhiteLabel apps which need to override these texts for their app.
Files locations:
AgreementURLsConfig.swift in App/Source/Configuration
AgreementTextView.swift in App/Source/Helper Views
AgreementURLsConfigTests in App/Tests/Unit Tests
In the default_config.yaml file, add this dictionary:
AGREEMENT_URLS: {
EULA_URL: 'https://www.cloudera.com/legal/commercial-terms-and-conditions/cloudera-training-terms/cloudera-ta-v6-2017-05-25.html'
}
The EULA on the registration page will link to the URL above. Default values will be used for the other two URLs.
Screenshots:
Other URLs can be overridden by using:
AGREEMENT_URLS: {
EULA_URL: …
> Adds configurable URLs for EULA, TOS etc.

- Source/OEXInterface.m
- Source/OEXNetworkConstants.h
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/OEXDBTests.m
[LEARNER-5244](https://openedx.atlassian.net/browse/LEARNER-5244)
Remove legacy course API from code.
> iOS - Stop using legacy course API for video data

- Source/UserProfileEditViewController.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6800](https://openedx.atlassian.net/browse/LEARNER-6800)
This PR handles `AccessibilityHint` for user-editable fields on Edit Profile Screen. VoiceOver by default is not handling false value of `isUserInteractionEnabled` for the disabled fields. So I have added likewise feature by implementing  `AccessibilityHint` for editable fields.
- Go to user profile screen from the main screen by clicking user avatar.
- Go to edit profile screen by clicking the edit button.
- Select `limited profile` option from the toggle control.
- Turn on voice over
- Voice over should say `dimmed` at the end for disabled fields.
> AccessibilityHint for disabled user fields on edit profile screen

- .travis.yml
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-6798](https://openedx.atlassian.net/browse/LEARNER-6798)
I have removed the pushing of source files to Transifex from the Travis script. And also I have removed changes those were made to tackle https://github.com/travis-ci/travis-ci/issues/4725 because the issue has been closed.
I have enabled auto pull to the following resources:
- [ios-app-localizable-strings](https://www.transifex.com/open-edx/edx-mobile-apps/ios-app-localizable-strings/)
- [ios-app-info-strings](https://www.transifex.com/open-edx/edx-mobile-apps/ios-app-info-strings/)
Following files are common between both platforms(Android and iOS) so at the moment pulling sources for these files are from the [android repository](https://github.com/edx/edx-app-android). 
- …
> Remove travis job of pushing of transifex resources

- Source/AuthenticatedWebViewController.swift
[LEARNER-6732](https://openedx.atlassian.net/browse/LEARNER-6732)
This PR handles dynamic text change of iOS App Settings for the authenticated web content. `AuthenticatedWebViewController` is now listing to `UIContentSizeCategoryDidChangeNotification` and `reload` itself whenever value of dynamic text changes in iOS App Settings.
- Access any authenticated web content like course dates, user enrolled programs or xBlocks in edX app.
- Open iOS App Settings
- Navigate to General -> Accessibility -> Large Text
- Change the value of the slider
- Reopen/comeback to the edX app
- Opened authenticated web content should reload itself and shows the content according to newly selected dynamic text size value.
> Handle Dynamic Type Text Change For Authenticated Web Content

- Source/OEXRouter+Swift.swift
[LEARNER-7006](https://openedx.atlassian.net/browse/LEARNER-7006)
Login Bottom Bar is not appearing for Program Discovery Detail Page
- Go to Startup Screen
- Tap on search courses, discovery view will open.
- The bottom bar should show
- Tap on program tab and go in program detail screen, the bottom bar should show. Press back button the main discovery screen should show with bottom bar.
> iOS - Login Bottom Bar is not appearing for Program Discovery Detail Page

- Source/Deep Linking/DeepLinkManager.swift
- Source/DegreesViewController.swift
- Source/DiscoveryConfig.swift
- Source/DiscoveryViewController.swift
- Source/DiscoveryWebViewHelper.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAppDelegate.m
- Source/OEXRouter+Swift.swift
- Source/ProgramsDiscoveryViewController.swift
- Source/SegmentItem.swift
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-6918](https://openedx.atlassian.net/browse/LEARNER-6918)
In this PR i added the third tab name "degree" in discovery view.
Add the following configurations under the "DISCOVERY" object to enable degree
```
DEGREE:
TYPE: 'webview'
WEBVIEW:
BASE_URL: 'https://webview.edx.org/course?type=Masters'
DETAIL_TEMPLATE: 'https://webview.edx.org/{path_id}'
SEARCH_ENABLED: true
```
- If you are not logged in, tap on the search courses, the third tab degree should be there.
- If you are logged in, switch the discovery tab view, there should be third tab degree there.
> iOS - Add a third tab to the discovery view named 'degrees'

- openedx.yaml
This will let us tag the mobile apps along with the rest of the Open edX releases.
> Add openedx-release to openedx.yaml

- Source/DiscoveryConfig.swift
[LEARNER-7049](https://openedx.atlassian.net/browse/LEARNER-7049)
Currently, the degrees have the URI prefix edxapp://program_info, which is what we use for Program Discovery and resolve in-app using the DETAIL_TEMPLATE key in the Program Discovery map config.
If the Program Discovery isn't present in the config and Degree Discovery is enabled, the app starts to crash whenever a Degree item is opened in-app.
In this PR we are making the degree tab dependent on programs discovery.
> Make degree tab dependent on program

- Libraries/Alamofire/Alamofire.swift
[LEARNER-6925](https://openedx.atlassian.net/browse/LEARNER-6925)
Mobile was using `CFURLCreateStringByAddingPercentEscapes` to escape legal URL characters. The CFURLCreateStringByAddingPercentEscapes was deprecated in iOS 9.0. The current version of iOS is 12.1.4, so iOS 9.0 is pretty much older iOS version and Xcode is giving the warning to update it.
I have created a CharacterSet from RFC 3986 allowed characters to handle query parameters in API requests. 
Run the app and access all the areas of the app. App should behave exactly the same as it was behaving before the update.
> Update Escaping Mechanism for Query Parameters in API Requests

- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
[LEARNER-7196](https://openedx.atlassian.net/browse/LEARNER-7196)
In this PR, i implemented the deep linking for course dates screen, now by clicking on the quick link the app will open up the course dates tab on course dashboard screen.
Notes
Add following links in notes, tap on the url will open the app and navigate to course dates screen.
Program Detail Screen: https://edx.app.link/course_dates
> Implement deep linking for course dates screen

- Source/BlockViewControllerCacheManager.swift
- Source/CourseContentPageViewController.swift
- Source/HTMLBlockViewController.swift
- Test/CourseContentPageViewControllerTests.swift
[LEARNER-7181](https://openedx.atlassian.net/browse/LEARNER-7181)
Implement preloading of next & previous xblocks and caching seven blocks. This will increase the user experience significantly. For the cache, I have used NSCashe because NSCashe is purgeable cache and we don't have to worry about memory size.
It's not sure that, seven xblocks will always be in cache because of purgeable cache. Cache items will totally depend on device memory.
> Cache xBlocks and Preloading xBlocks

- Source/CourseDashboardViewController.swift
- Source/CourseHandoutsViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
[LEARNER-7197](https://openedx.atlassian.net/browse/LEARNER-7197)
In this PR, i implemented the deep linking for course handout screen, now by clicking on the quick link the app will open up the course handout screen on course dashboard screen.
Notes
Add following links in notes, tap on the url will open the app and navigate to course handout screen.
Course Handout Screen: https://edx.app.link/course_handout
> iOS - Implement deep linking for course handouts

- Source/DetailToolbarButton.swift
- Source/OEXFonts.swift
- Source/OEXStyles.h
- Source/OEXStyles.m
- Source/OEXTextStyle.h
- Source/OEXTextStyle.m
[LEARNER-7192](https://openedx.atlassian.net/browse/LEARNER-7192)
Every element was adopting `Dynamic Text Support` even if there wasn't enough space to grow for larger text size and in the result, UI broke. In this PR I have added support in OEXTextStyle to disable `Dynamic Text Support` for an element or even developer can disable `Dynamic Text Support` for the whole app by changing just one variable `dynamicTypeSupported`. In the other way, a developer can only enable `Dynamic Text Support` for certain elements.
> Added support to OEXTextStyle for disabling dynamic type

- Source/CutomePlayer/OEXVideoPlayerSettings.swift
[LEARNER-6495](https://openedx.atlassian.net/browse/LEARNER-6495)
The iOS app was producing the crash on video player setting. This PR fixed that crash.
Fabric: https://fabric.io/edx-inc/ios/apps/org.edx.mobile/issues/5afc992e11e9fa0aa5c7fc8e?time=last-ninety-days
> iOS - OEXVideoPlayerSettings Crash fix 

- Source/CourseAnnouncementsViewController.swift
- Source/CourseDashboardViewController.swift
- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/OEXRouter+Swift.swift
[LEARNER-7198](https://openedx.atlassian.net/browse/LEARNER-7198)
In this PR, i implemented the deep linking for course announcement screen, now by clicking on the quick link the app will open up the course announcement screen on course dashboard screen.
Notes
Add following links in notes, tap on the url will open the app and navigate to course announcement screen.
Course announcement Screen: https://edx.app.link/course_announcement
> iOS - Implement deep linking for course announcement screen

- Source/Deep Linking/DeepLink.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscoveryViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter+Swift.swift
- Source/ProgramsDiscoveryViewController.swift
- Source/WebView/DiscoveryHelper.swift
[LEARNER-7220](https://openedx.atlassian.net/browse/LEARNER-7220)
In this PR i implemented the deep linking for degree tab and degree details on discovery screen, now by clicking on the quick link the app will open up the degree tab or degree details on course discovery screen depending on provided pathID. 
Add following links in notes, tap on the url will open the app and navigate to degree tab on discovery screen.
Degrees Screen: https://edx.app.link/degree_discovery
Add following links in notes, tap on the url will open the app and navigate to degree detail page.
Degree Detail Screen: https://edx.app.link/degree_discovery_detail
> iOS - Implement deep linking for Degree or Degree Detail Screen

- Source/OEXExternalAuthOptionsView.h
- Source/OEXExternalAuthOptionsView.m
- Source/OEXExternalRegistrationOptionsView.m
- Source/OEXLoginViewController.m
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
[LEARNER-5862](https://openedx.atlassian.net/browse/LEARNER-5862)
On sign in screen when user tap on 'Google' or 'Facebook' buttons, app was saying register with google and register with Facebook button now i fixed this issue and the accessibility label are saying 
sign-in with google and sign-in with Facebook.
> iOS - a11y- Fix Sign-in screen social login button accessibility issue

- Source/OEXCourse.h
- Source/OEXCourse.m
- Source/OEXDBManager.m
- Source/OEXDownloadManager.m
- Source/OEXInterface+Swift.swift
- Source/OEXInterface.h
- Source/OEXInterface.m
- Test/CourseContentPageViewControllerTests.swift
- Test/CourseDashboardViewControllerTests.swift
- Test/CourseOutlineHeaderViewTests.swift
- Test/CourseOutlineViewControllerTests.swift
- Test/CourseSectionTableViewCellTests.swift
- Test/OEXCourse+TestData.swift
- Test/VideoPlayerTests.swift
[LEARNER-7311](https://openedx.atlassian.net/browse/LEARNER-7311)
In OEXInterface courseVideos indexing was based on course_outline but a TODO was there to update the courseVideos indexing on course_id.
If a course video was downloading and user kills the app then on restarting the app, downloading on the underlying video restarted but downloading struck on 1-5% and never completed.
This PR address the video restart issue as well.
> Course Video Indexing on the CourseID

- Source/CourseOutline.swift
- Source/CutomePlayer/VideoPlayer.swift
- Source/OEXAppDelegate.m
- Source/OEXVideoSummary.h
- Source/OEXVideoSummary.m
- Test/OEXVideoSummaryTests.m
[LEARNER-7304](https://openedx.atlassian.net/browse/LEARNER-7304)
Video player analytics(Speed change, Seek) was not working, In PR i have fixed the analytics now its working.
- Run Video
- Open Speed Change setting menu and change speed/ Seek the video by moving progress slider forward or backward.
> iOS - Video player analytics are not working

- Source/ProfileAPI.swift
- Source/UserProfileManager.swift
[LEARNER-7269](https://openedx.atlassian.net/browse/LEARNER-7269)
Sometimes the app was crashing while updating the profile. Although the crash is not reproducible, there was a place where username for unwrapped forcefully. It might be the reason for the crash.
As the crash is not reproducible so I can't say the underline change will fix the crash. We have to wait for v2.20 to see either the crash got fixed or not.
> Fix Update Profile Crash

- Source/FirebaseConfig.swift
- Source/OEXAppDelegate.m
- Source/OEXEnvironment.m
- Test/FirebaseConfigTests.swift
[LEARNER-7325](https://openedx.atlassian.net/browse/LEARNER-7325)
This PR simplifies the logic of Firebase Analytics either it will be fired from Firebase or Segment.
> Implement feature flag parity for Segment-Firebase implementation

- Source/VideoTranscriptTableViewCell.swift
When playing a video which has a transcript that contains certain formatting tags in the attached SRT files, the tags are displayed verbatim in the app without the proper styling being applied (unlike the web site which displays them correctly). 
These tags are just basic style tags borrowed from HTML, see: https://en.wikipedia.org/wiki/SubRip#Formatting.
**Note:** this is a work-in-progress prototype to get the discussion out there. Please pardon any formatting errors or failed CI builds, I won't have a Mac handy until tomorrow...
[OSPR-3397](https://openedx.atlassian.net/browse/OSPR-3397)
Utilize the convenience that UIKit's `NSAttributedString` provides by initializing it with raw data, specifying a `DocumentType` of `.html`, and **get the basic bold / italic / etc styling for free**. …
> Properly render html-like markup contained in video transcripts

- Source/SubjectsDiscovery/Subjects JSON/pt-BR.lproj/subjects.json
- Source/pt-BR.lproj/InfoPlist.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/pt-BR.lproj/MobileAppEula.htm
- Source/pt-BR.lproj/PrivacyPolicy.htm
- Source/pt-BR.lproj/TermsOfServices.htm
- Source/pt-BR.lproj/languages.json
- Source/pt-BR.lproj/profiles.json
- Source/pt-BR.lproj/whats_new.json
- edX.xcodeproj/project.pbxproj
[LEARNER-7351](https://openedx.atlassian.net/browse/LEARNER-7351)
This PR adds the Portuguese language support in iOS App. I have downloaded the Portuguese translated resources from [transifex](https://www.transifex.com/open-edx/edx-mobile-apps/content/). If the Portuguese translation of a resource or for a string is missing, then the English version of that resource/string will be used.
In this PR maximum allowed birth year is also updated to 2019 in the user settings.
1. Portuguese translation of some resources/strings is missing like Subjects filter in course discovery.
2. Web views content will be in English because webviews are no entertaining the selected language of the iOS device yet.
Change the iOS device language to Turkish. To change the language follow the following path: …
> Add Portuguese (Brazil) language support

- Source/CourseContentPageViewController.swift
- Source/VideoBlockViewController.swift
[LEARNER-7377](https://openedx.atlassian.net/browse/LEARNER-7377)
When we move next and previous on course content screen the app got crash, We faced this crash a lot of times before and tried to fix in different ways but it still reproduce. I tried to test this crash by disabling the back and forward animation and switch views without animation, the app do not crash. In this PR i disable the animation and tried to fix the crash.
> iOS - Fix the crash of pageview controller

- Source/SubjectsDiscovery/Subjects JSON/ja.lproj/subjects.json
- Source/ja.lproj/InfoPlist.strings
- Source/ja.lproj/Localizable.strings
- Source/ja.lproj/MobileAppEula.htm
- Source/ja.lproj/PrivacyPolicy.htm
- Source/ja.lproj/TermsOfServices.htm
- Source/ja.lproj/languages.json
- Source/ja.lproj/profiles.json
- Source/ja.lproj/whats_new.json
- edX.xcodeproj/project.pbxproj
[LEARNER-7356](https://openedx.atlassian.net/browse/LEARNER-7356)
Japanese language support has added. All Resources are downloaded from [Transifex](https://www.transifex.com/open-edx/edx-mobile-apps/content/).  
If Japanese translation of any string is missing then the english version of string will be display.  
Change the iOS device language to Japanese. To change the language follow the following path:
Settings -> General -> Language & Region -> iPhone Language
> iOS - Add Japanese language support.

- Source/edX-Info.plist
This fixes the following error, that is generated, when a new build is uploaded to itunes.
```
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that 
access sensitive user data. The app's Info.plist file should contain a 
NSBluetoothAlwaysUsageDescription key with a user-facing purpose string explaining clearly and 
completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store 
that access user data are required to include a purpose string. If you're using external libraries or 
SDKs, they may reference APIs that require a purpose string. While your app might not use these
APIs, a purpose string is still required. You can contact the developer of the library or SDK and 
request they release a version of …
```
> Add NSBluetoothAlwaysUsageDescription key to edX-Info.plist file

- Source/FCMListner.swift
- Source/OEXEnvironment.m
- Source/PushLink.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-7506](https://openedx.atlassian.net/browse/LEARNER-7506)
`FCMListner` was not working because the parameter `environment` which was passed to the `FCMListner` was `nil`. `FCMDataModel` was just creating `PushLink`, I have removed it.
> Fix: Push Notification Framework Navigation Issue

- Source/OEXRouter+Swift.swift
[LEARNER-7485](https://openedx.atlassian.net/browse/LEARNER-7485)
In this PR I fixed the issue of app navigation on discussion thread with a deep link or push notification. I also verified the background push notification action for the thread update.
> iOS -  Fix the issue in navigation to discussion thread with background push notification.

- Source/Deep Linking/DeepLinkManager.swift
[LEARNER-7508](https://openedx.atlassian.net/browse/LEARNER-7508)
When the app is in the foreground and a push notification is received, show a native dialogue with the following specifications.
The dialog will have the title and description along with 2 buttons:
Dismiss: for dismissing the dialog without any action.OK or View: for navigating the learner to the relevant screen according to the received push.
The app should show a native dialogue on receiving a push notification while the app is in the foreground state.
> Show native alert dialog on FCM push message

- Source/Deep Linking/DeepLinkManager.swift
- Source/OEXRouter.h
- Source/OEXRouter.m
[LEARNER-7510](https://openedx.atlassian.net/browse/LEARNER-7510)
Opening the app through a deep link that requires an authenticated user, if the leaner was not logged in the app was redirecting the leaner to the login screen. On successful, the app was just showing the enrolled courses screen and was not following the opened deep link.
This PR addresses the mentioned problem and now redirecting the leaner to the relevant screen on a successful login.
> Handle logged out case for Deep link

- Source/CutomePlayer/PlayerView.swift
- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
[LEARNER-7575](https://openedx.atlassian.net/browse/LEARNER-7575)
On iOS 13, the video is not playing properly in the fullscreen mode. The experience is totally broken when the learner goes to fullscreen mode by clicking the fullscreen button. The video is also not covering the whole screen properly when the learner goes to fullscreen by rotating the device to landscape. 
There is some issue with iOS version < 12, where the video player does not get back to the original frame after getting back from the landscape view.
Play some video on iOS 13, set it to fullscreen, video player should be in full-screen view with landscape orientation.
> Fix video landscape issue on iOS 13

- Source/DiscoveryWebViewHelper.swift
[LEARNER-5729](https://openedx.atlassian.net/browse/LEARNER-5729)
This PR is to fix the loading indicator during applying the subject filter on the course discovery screen.
I also added a loading indicator on the search results.
- Login into the app.
- Switch to discovery tap
- Tap on any subject
Expected Result:
Loading Indicator should show on screen during applying the subject filter.
> LEARNER-5729, Show loading indicator during applying subject filter

- Source/JSONFormBuilderTextEditor.swift
- Source/UserProfileEditViewController.swift
[LEARNER-7624](https://openedx.atlassian.net/browse/LEARNER-7624)
Roughly a year ago server has set a limit of `300 characters` for user `bio` text. Mobile apps weren't aware of this change and were letting the user input bio text as much he wants but the server wasn't accepting it and was returning an error.
This PR now limits the user to add bio text to a maximum of 300 characters. If the user pasted the text more than of the limit, the system should automatically trim the text to 300 characters.
> User profile improvements 

- Source/EnrolledTabBarViewController.swift
- Source/OEXRouter+Swift.swift
- Source/WebView/DiscoveryHelper.swift
[LEARNER-7587](https://openedx.atlassian.net/browse/LEARNER-7587)
On ‘My Programs' screen 'Explore New Programs' button was showing error due to the backend’s change of altering the previous URL on the button to mobile-specific URI i.e. `edxapp://course?programs. This PR fixed this issue.
- Run the app
- Switch programs tab
- scroll down the view and press the explore program button, the app should navigate to programs discovery view.
> iOS - Explore new programs

- Source/DiscoveryWebViewHelper.swift
[LEARNER-6938](https://openedx.atlassian.net/browse/LEARNER-6938)
This PR disables the webview zoom in Discovery.
> Disable Webview zoom in Discovery

- Source/NSError+JSON.swift
- Source/NetworkManager+Authenticators.swift
[LEARNER-7694](https://openedx.atlassian.net/browse/LEARNER-7694)
After the [oauthlib](https://github.com/oauthlib/oauthlib) library upgrades in [BOM-1277](https://openedx.atlassian.net/browse/BOM-1277), our mobile learners are facing the issue of `content isn't loading`.
This issue occurs when the mobile app failed to get access_token against the refresh_token.
Before the oauthlib library upgrade server was returning error `{ "error" : "invalid_grant" }` with status_code 401 when it failed to return an access_token for the provided refresh_token. But after the oauthlib library upgrade server is returning error `{ "error": "invalid_grant" }` with status_code 400. This PR handles `{ "error" : "invalid_grant" }` with `status_code 4xx`.
API_HOST_URL: …
> Logout when failed to get new access_token against refresh_token

- Source/CutomePlayer/VideoPlayerControls.swift
[LEARNER-7711](https://openedx.atlassian.net/browse/LEARNER-7711)
The video player has many components like the play/pause button, navigate to next block button, previous block buttons, bottom bar with duration slider, settings button, full screen buttons. These components aren't passing controls to the toggle controls button even when hidden which results in a very limited place to toggle controls button. And also it's a bit tricky for learners where to click to show the controls.
This PR improves the video player controls toggling.
>  Improve Video Player Controls Toggling

- Source/OEXRouter.m
[LEARNER-LEARNER-7689](https://openedx.atlassian.net/browse/LEARNER-LEARNER-7689)
When the app failed to auto-refresh access_token the NetworkManager+Authenticators.swift logout the learner. Sometimes the logout call happens more than and the sign-in screen shows more than once in the stack.
> iOS - Fix Issue with Login Screen for Auto Logout

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Source/OEXAnalytics.h
- Source/OEXAnalytics.m
- Source/OEXConstants.h
- Source/OEXInterface.m
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
- Test/VideoPlayerTests.swift
[LEARNER-7688](https://openedx.atlassian.net/browse/LEARNER-7688)
The video player should have video rewind and forward button options. Rewind button would be 10 seconds reverse and the forward button would be 15 seconds skip for video.
> iOS - Add option in the video player for going backward & forward

- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController+Swift.swift
- Source/OEXRegistrationViewController.m
- Source/OEXSession.h
- Source/OEXSession.m
[LEARNER-7653](https://openedx.atlassian.net/browse/LEARNER-7653)
This PR adds option to Registration flow to check if user is already in registration flow, then continue the registration flow.
**Case 1**
**Case 2**
It seems the third-party auth also has a link with the login screen.
And the other scenario is:
> Register Screen - User can register without password after logging through google

- Source/AgreementTextView.swift
- Source/AgreementURLsConfig.swift
- Source/OEXUserLicenseAgreementViewController.m
- Test/AgreementURLsConfigTests.swift
[LEARNER-7761](https://openedx.atlassian.net/browse/LEARNER-7761)
This PR allows all the agreement URLs to be configured independently.
If the `AGREEMENT_URLS` dictionary present in the config and any agreement URL is missing or having an empty value then that agreement value should not be clickable.
```
AGREEMENT_URLS:
EULA_URL: 'https://www.example.com'
TOS_URL: 'https://www.example.com'
PRIVACY_POLICY_URL: 'https://www.example.com'
```
1. Add and change values in the config
2. Open Login or Register screen to see the changes in action.
> Configure TOS, EULA and Privacy Policy Independently

- Source/OEXLoginViewController.m
[LEARNER-7753](https://openedx.atlassian.net/browse/LEARNER-7753)
Proper error showing in case of login failure.
1. Open login screen
> Error Showing on login failure

- Source/NetworkManager+Authenticators.swift
- Test/NetworkManager+AuthenticatorTests.swift
[LEARNER-7776](https://openedx.atlassian.net/browse/LEARNER-7776)
In case when asynchronous calls are made and are attempting to refresh the access_token where one call succeeds but the other fails. Reserver responds with `token_nonexistent` access token.
```
{
"error_code" : "token_nonexistent",
"developer_message": "The provided access token does not match any valid tokens."
}
```
On iOS, we were logging out learners whenever the server responds with token_nonexistent, but in this PR I'm refreshing access_token instead of logging out learner.
1. Login to https://debugtoken.sandbox.edx.org/admin using credentials `admin/Hamilton`
2. Login to the mobile app using credentials `staff/edx`
3. Expires `staff` user access token.
4. Navigate to the app or use pull to refresh to hit new API's
> Refresh Access Token in case of Non Existent token

- Source/Registration Field Views/RegistrationFormFieldView.swift
[LEARNER-7767](https://openedx.atlassian.net/browse/LEARNER-7767)
This PR improves learner experience with the validation error messages. We were showing an error message to leaner while the learner wasn't finished the input. This PR improve behavior, now first time leaner will see an error message if any on tap out and the then while editing.
Open Registration form and starting typing in any field like email.
> Registration Form Errors messages showing improvements

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Source/VideoBlockViewController.swift
[LEARNER-7813](https://openedx.atlassian.net/browse/LEARNER-7813)
This PR adds support of Offline Snackbar to the Video Block View.
We won't be able to achieve the exact same behavior of Android because the players' callbacks are different. And there isn't any indication in the callbacks that there isn't any network connection.
> Offline Support for Video Block

- Source/OEXRouter+Swift.swift
- Source/OEXRouter.m
- Source/UIViewController+CommonAdditions.swift
[LEARNER-7840](https://openedx.atlassian.net/browse/LEARNER-7840)
In this PR I fixed the issue that the login screen was not opening. This issue was particularly producible in iOS-12.x devices.
- Start the application, tap on the login button the login screen should show up.
- Login in the application and go into account screen, tap on the logout button the login screen should show up.
> LEARNER-7840, login screen is not opening

- Source/Core/Code/RegistrationFormAPI.swift
- Source/OEXNetworkConstants.h
- Source/OEXRegistrationViewController+Swift.swift
- Source/OEXRegistrationViewController.m
- Source/Registration Field Views/RegistrationFormFieldView.swift
- Source/RegistrationFormValidation.swift
- Source/RegistrationSelectOptionView.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-7834](https://openedx.atlassian.net/browse/LEARNER-7834)
- Validate the registration form using the API: `POST /api/user/v1/validation/registration`
- The validation API should be hit before the actual registration API
- The validation API should be initiated upon the click of Register button
- If the validation API doesn't return any error in its response, the app should automatically call the registration API and register the learner
- If the validation API returns an error in its response, the app should not call the registration API and show the error inline with each field that had invalid data
> Registration Form Validations

- Source/CourseCatalogViewController.swift
- Source/DiscoveryViewController.swift
- Source/OEXRouter+Swift.swift
[LEARNER-7588](https://openedx.atlassian.net/browse/LEARNER-7588)
> Fix Discovery Screen Title

- edX.entitlements
[LEARNER-7849](https://openedx.atlassian.net/browse/LEARNER-7849)
This PR adds `com.microsoft.adalcache` in keychain sharing, thus it allows edX app to open `Authenticator` app if installed, to allow user to login from there or revert to local webview to allow signin.
> Microsoft login - Keychain sharing

- Source/AppleAuthProvider.swift
- Source/AppleSocial.swift
- Source/OEXRegistrationViewController.m
- edX.entitlements
- edX.xcodeproj/project.pbxproj
[LEARNER-7697](https://openedx.atlassian.net/browse/LEARNER-7697)
This PR adds support of social auth with `Apple`. Learners will be able to use their Apple credentials to login/register with our server.
You will be able to register and sign in using the Apple credentials on the prod environment from mobile. `Sign in With Apple` is not available on the prod web and it will be enabled when we will push the solution on mobile. To test a integration between mobile and web please use the stage environment.
> Social Auth Sign In With Apple Support

- Source/CutomePlayer/VideoPlayerControls.swift
[LEARNER-7906](https://openedx.atlassian.net/browse/LEARNER-7906)
> VideoPlayer: Video remaining time display improvements

- Source/DiscoveryWebViewHelper.swift
[LEARNER-7927](https://openedx.atlassian.net/browse/LEARNER-7927)
On iOS, we were using `document.getElementsByClassName('course-card')` in e2e tests to make sure discovery page is loaded successfully or not. While transitioning from Drupal based discovery to prospectus based discovery the class named changes from `course-card` to `discovery-card` and it started through the error `JS Error: undefined is not an object`. 
In this PR I've addressed the issue and updated the class name.
> JS Error: undefined is not an object

- Source/VersionUpgradeInfoController.swift
[LEARNER-7940](https://openedx.atlassian.net/browse/LEARNER-7940)
Due to some unknown reasons server started responding with the case in-sensitive headers. On iOS, we were expecting case sensitive headers. This breaks the version upgrade functionality. This PR makes the extraction of version upgrade info case insensitive.
Change the `build` number to see the version upgrade info snack bar and fullscreen update messages.
> Case in Sensitive Dictionary Keys Comparison

- Source/EmailTemplates.swift
- Source/NSError+JSON.swift
- Source/NetworkManager+Authenticators.swift
- Source/OEXLoginViewController.m
- Source/OEXRegistrationViewController.m
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-7898](https://openedx.atlassian.net/browse/LEARNER-7898)
Disabled account handling on mobile.
```
API_HOST_URL: 'https://socialauthn.sandbox.edx.org'
OAUTH_CLIENT_ID: '76hs3musgAMq4QiMqRZFQ6MxgiUEW27Fd7KlHExy'
```
Learner active status can be managed by following this URL https://socialauthn.sandbox.edx.org/support/manage_user
Note: You can use your prod or stage configuration of Google auth to test the PR.
> Disabled Account Handling

- DateFormatting.swift
[LEARNER-8087](https://openedx.atlassian.net/browse/LEARNER-8087)
The app was crashing on hitting rewind buttons while the video is loading. This PR fixed the crash.
Go to a video component and hit the rewind forward or rewind back button while the video is loading. The app should not crash.
> Fix time formatting crash

- Source/CourseCardView.swift
[LEARNER-8088](https://openedx.atlassian.net/browse/LEARNER-8088)
In the case of large course titles, the complete course title is not displaying on the course dashboard screen. This PR fixed the said issue.
Open any course with a large title, the complete course title should appear on the course dashboard screen.
> Fix: Large Course Title is Cutting on Course Dashboard Screen

- Source/edX-Info.plist
[LEARNER-8136](https://openedx.atlassian.net/browse/LEARNER-8136)
To prepare the app for the iOS 14 before Apple enforces IDFA enforcement in 2021. Add NSUserTrackingUsageDescription key into `info.plist` so the app won't break when apple enforces the IDFA changes.
Info Message:
`The data will be used to track your activity to address app functionality and gather data analytics for multiple purposes.`
> Add NSUserTrackingUsageDescription Key and info Message

- Source/CourseCatalogViewController.swift
- Source/CourseGenericBlockTableViewCell.swift
- Source/CourseUnknownBlockViewController.swift
- Source/CoursesContainerViewController.swift
- Source/EnrolledCoursesViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/FirebaseRemoteConfiguration.swift
- Source/OEXConfig+AppFeatures.swift
[LEARNER-8109](https://openedx.atlassian.net/browse/LEARNER-8109)
In this PR I have added the value prop feature behind the remote config feature flag and remove its dependency on local config.
We are updating the value prop feature flag from remote config passively. On the first launch when the remote config call is in progress the app has set all the environment variables so in that case if we set the feature flag after getting a response the app user experience disturbs so we just store the remote config values in the user defaults and when the app relaunch again we read the remote config values from the user default and use them to show the value prop. 
In short the remote config value will actually work in app relaunch.
We have updated the flag from this place …
> iOS - Add value prop behind remote config feature flag

- Source/CourseOutlineViewController.swift
- Source/NetworkManager+Authenticators.swift
- Test/NetworkManager+AuthenticatorTests.swift
[LEARNER-8223](https://openedx.atlassian.net/browse/LEARNER-8223)
The app was logout learner forcefully on receiving the `invalid_grant` from the server. And it was happening almost every time the app tried to refresh `access_token`  with a `refresh_token`.
In case of async requests, a number of requests were being made to refresh the `access_token`, and after the first successful request server was returning `invalid_grant` for subsequent requests.
This PR address only a fraction of the problem and not forcefully logout on receiving the `invalid_grant`.
Invalid_grant will be gracefully handled under [LEARNER-8224](https://openedx.atlassian.net/browse/LEARNER-8224).
###Sandbox
API_HOST_URL: https://invalidgrant.sandbox.edx.org
OAUTH_CLIENT_ID: 'LCAi11sUG233NYD5JoX3NmnsjEeD7ecQAhbN52jo' …
> Don't Force Logout for invalid_grant

- Source/OEXAuthentication.m
- Source/OEXPersistentCredentialStorage.h
[LEARNER-8235](https://openedx.atlassian.net/browse/LEARNER-8235)
Mobile iOS users were seeing the error, ["Account Disabled"](https://openedx.atlassian.net/wiki/spaces/ENG/pages/2428796953/RCA+CR-3090+-+Mobile+iOS+users+seeing+error+Account+Disabled) and it was happening because in an unknown scenario somehow app was sending `prod-edx-sessionid` cookie in the `auth2/exchange_access_token` request.
This PR addresses the issue and deletes the cookies if not deleted on logout before the `auth2/exchange_access_token` request. Before deleting the cookies it also logs a non-fatal error on the `Firebase/Crashlytics` for investigation purposes.
There isn't any straightforward way to test this PR but it can be tested by creating a special dev environment. To create the dev environment add …
> Log non fatal crash and delete cookies before exchange_access_token

- Source/CutomePlayer/VideoPlayer.swift
Remove the previous method of observing when the player changed state and setting the rate afterward.
There is an issue in `resume(at:)` that resulted in `player.play()` being called, but a play status change either not happening or not being observed.  This meant that the rate was sometimes not set after play began with the default 1.0 rate.
[LEARNER-8163](https://openedx.atlassian.net/browse/LEARNER-8163)
I was able to reproduce the original issue by pressing Back while watching a video on 2.0 speed, then navigating to a different video I had not yet played.  I couldn't get this to reliably reproduce, but managed to make it happen fairly often.
> Always play AVPlayer by setting the rate directly.

- Source/CutomePlayer/VideoPlayer.swift
- Source/CutomePlayer/VideoPlayerControls.swift
- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Test/VideoPlayerTests.swift
https://openedx.atlassian.net/browse/LEARNER-8256
The default implementation of `seek` is async.  Add in completion blocks so the tests can wait for the seek to finish before continuing.
Make seekVideo accept a completion block as well.
*Note this is note tracked in JIRA*
Video seeking unit tests should now work when building on Travis!
But please check for any potential issues in the code.
> Fix video seeking tests

- Source/ValuePropDetailViewController.swift
[LEARNER-8244](https://openedx.atlassian.net/browse/LEARNER-8244)
The fix for the text in the value prop modal should not be tappable.
- Start the app.
- Tap on the learn more button the value prop detail view will open.
- The points should not be tappable.
> iOS - Text in the value prop modal should not be tappable

- Source/CourseVideoTableViewCell.swift
[LEARNER-8332](https://openedx.atlassian.net/browse/LEARNER-8332)
Fix Video Download Spinner on navigation between screens
> Video Download Spinner Isn't Working

- Source/UIImage+OEXHelpers.swift
Fix the `image(with color)` extension method so it does not scale the image incorrectly.  The new implementation uses an imageView to render the new image.
No JIRA ticket
This also fixes the specific issue fixed in #1487, but this is a more general fix.
Several icons throughout the app are affected.  Notably:
* "Closed"/lock icon on the Dates tab and value prop message
* Checkmarks and component type icons in course outlines
* "Create new post" icon on the Discussions tab
> fix: sharpen blurry icons across the app

- Source/CourseOutlineItemView.swift
`image(with)` is currently buggy and returns an image with the wrong scale (causing it to be blurry).  Remove this call, it is actually unnecessary because `tintColor` does the same thing.
(No JIRA ticket)
Look at the completion checkmark in a course outline.
> fix: sharpen blurry checkmark icon

- Source/HTMLBlockViewController.swift
- Source/Icon.swift
- Source/OpenInExternalBrowserView.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-8360](https://openedx.atlassian.net/browse/LEARNER-8360)
Allow the learner to open a rendered HTML-based xblocks in the external browser. Open in external browser option will be available all the rendered xblocks other than HTML(.Base), video, and discussion xblocks.
Open any component like the problem, draganddrop or cloudr-word and open in external option will be available at the bottom of view.
> [feat] Open rendered xBlock in Mobile Browser

- Source/CutomePlayer/YoutubeVideoPlayer.swift
- Test/YoutubeVideoPlayerTests.swift
[LEARNER-8411](https://openedx.atlassian.net/browse/LEARNER-8411)
Youtube video player controls are not visible to take action like stop/pause, seek on the iPad in the landscape mode. 
On the iPhone, in landscape mode, the video is playing in fullscreen mode because we are passing `inline:0` to the SDK but in the case of the iPad the behavior isn't consistent and I didn't find anything in the documentation related to it.  But the controls are functional in portrait and landscape mode.
> Video Player Controls are not visible for Youtube videos on iPad

- Source/CalendarManager.swift
- Source/CourseDatesViewController.swift
- Source/CourseOutlineViewController.swift
- Source/HTMLBlockViewController.swift
- Source/OEXAnalytics+Swift.swift
- Source/SnackbarViews.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8412](https://openedx.atlassian.net/browse/LEARNER-8412)
> [feat] shift course calendar events after shift due date

- Source/AuthenticatedWebViewController.swift
- Source/CourseOutline.swift
- Source/CourseOutlineTableSource.swift
- Source/OEXRouter+Swift.swift
[LEARNER-8410](https://openedx.atlassian.net/browse/LEARNER-8410)
This PR adds support of `lti_consumer` xbloxks. Previously `lti_consumer` xblocks were not rendered within the apps and considered as unsupported xblocks. Now the learner will be able to see the `lti_consumer` xblocks in the app.
We won’t be able to add the full support of lti_consumer xblocks that requires cookies support like zoom lti_consumer xblock as the cookies are not supported by safari.
Go to any lti_consumer xblock and it will be rendered within the app.
> [feat] Add support of lti_consumer xblocks

- edX.xcodeproj/project.pbxproj
CoreBluetooth.framework is not used in the app, so we do not need to link to this framework.  Simply linking to it causes Apple to warn that we do not have a NSBluetoothAlwaysUsageDescription in our info.plist when we upload new binaries to App Store Connect, so this will also prevent that warning.
* Remove CoreBluetooth.framework from linked binaries in the project file.
* Delete CoreBluetooth.framework from the Frameworks folder
> build: Remove CoreBluetooth.framework as a dependency

- Source/CalendarManager.swift
- Source/CourseDatesViewController.swift
[LEARNER-8430](https://openedx.atlassian.net/browse/LEARNER-8430)
When app is uninstalled, course calendar is not removed and user reinstalls the app, goes to dates screen, turns on the calendar, goes to previous screen and navigates back to course dates screen, calendar switch is turned off, it should be in on state as user turned on the calendar for this course.
> [fix] handle calendar after app is reinstalled

- Source/CourseUnknownBlockViewController.swift
[LEARNER-8444](https://openedx.atlassian.net/browse/LEARNER-8444)
This PR fixes the bug, the gated content component detail screen wasn't rendering.
> [Fix] Gated content component screen rendering

- Source/CourseContentPageViewController.swift
- Source/DetailToolbarButton.swift
[LEARNER-8417](https://openedx.atlassian.net/browse/LEARNER-8417)
[ ] Subtext of `Next` shouldn't take more than half of the screen.
[ ] Subtext of `Previous` shouldn't take more than half of the screen.
[ ] On changing the device orientation subtext should repopulate it to use the available space.
> [fix] adjust the navigation bottom bar button width

- Source/CalendarManager.swift
- Source/CourseDatesHeaderView.swift
- Source/CourseDatesViewController.swift
[LEARNER-8304](https://openedx.atlassian.net/browse/LEARNER-8304)
As a user, I want my device calendar to update if course dates are changed outside the mobile app
```
Title: Your course calendar is out of date
Description: Your course dates have been shifted and your course calendar is no longer up to date with your new schedule.
Buttons: Update now | Remove course calendar
```
> [chore] shift course calendar events if course dates were shifted outside app

- Source/CourseCardView.swift
- Source/CoursesContainerViewController.swift
- Source/ValuePropCourseCardView.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8423](https://openedx.atlassian.net/browse/LEARNER-8423)
In this PR new design of the value prop on the enrolled courses screen has been changed. This PR also fixes the voiceover of the enrolled course card.
> [chore] Redesigned value prop on the enrolled courses screen

- Source/CoursesContainerViewController.swift
[LEARNER-8246](https://openedx.atlassian.net/browse/LEARNER-8246)
This PR hides the value prop from the course cards on the courses enrollments screen from the ended/archived courses.
> [chore] Hide value prop for ended/archived courses

- Source/CourseOutlineTableSource.swift
- Source/CourseOutlineViewController.swift
- Source/CourseVideosHeaderView.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXRouter+Swift.swift
- Source/OEXVideoEncoding.h
- Source/OEXVideoEncoding.m
- Source/OEXVideoSummary.h
- Source/OEXVideoSummary.m
- Source/ProfileOptionsViewController.swift
- Source/VideoDownloadQuality.swift
- Source/VideoDownloadQualityViewController.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
- edX.xcodeproj/project.pbxproj
[LEARNER-8503](https://openedx.atlassian.net/browse/LEARNER-8503)
Give learners the choice to download whichever video quality they want to download.
-  Add the video download quality selection option on the Settings screen
- 4 options to select the download quality are available when the user taps into the video download quality selection option
- mobile_low_360p, mobile_high _540p, desktop_mp4 (720p):  all the mappings
- A new section will be added to the video downloads page where the user can see the currently selected download quality option
- Tapping on this section will deeplink to the quality selector (1.b.)
- The download size will be calculated based on the selected download quality option
- The default selection will be ‘Auto’
- Current ‘Auto' behavior is mobile_low → …
> [feature] add video download qualities options

- Source/BrowserViewController.swift
- Source/HTMLBlockViewController.swift
- Source/OEXRouter+Swift.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8498](https://openedx.atlassian.net/browse/LEARNER-8498)
This PR adds the functionality of opening the URL inside the app web browser. Previously, we were redirecting the learner to the external web browser where the learner has to log in again.  But with this PR, the learner will be automatically logged in to the fullscreen browser and the Unit URL of the component will be opped for a better learning experience.
> [feature] Open Unit URL in a In-App Webview' from the Open in Browser Banner

- Source/CourseVideosHeaderView.swift
- Source/ProfileOptionsViewController.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8530](https://openedx.atlassian.net/browse/LEARNER-8530)
Remove chevron button from the videos tab – Video download quality header
Rename section title from WIFI to “VIDEO SETTINGS” – Profile screen
> chore: remove chevron button, change title to Video Settings

- Source/OEXLoginViewController.m
- Source/StartupViewController.swift
[LEARNER-8525](https://openedx.atlassian.net/browse/LEARNER-8525)
Fix `User Login` analytic tracking. The app was tracking `User Login` analytic on the login button click on the startup screen and on the successful login as well but only in case of username/password login. The event was not tracking in the case of third-party logins.
> [fix] fix user login event tracking

- Source/ValuePropMessagesView.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8561](https://openedx.atlassian.net/browse/LEARNER-8561)
The last bullet point is removed from the value prop modal that appears in both the course dashboard and course content pages.
> [chore] remove value prop info message

- Source/EnrolledCoursesViewController+Banner.swift
- Source/OEXAppDelegate.h
- Source/OEXAppDelegate.m
[LEARNER-8600](https://openedx.atlassian.net/browse/LEARNER-8600)
We have implemented a 10 sec delay for fetching the `/notices/api/v1/unacknowledged?mobile=true` API when the app is opened/resumed from the deep link for a better user experience. We have to implement the same logic (10 sec delay) when the app opened/resumed from a push notification because the navigation flow is shared between deep link and push notification.
> [chore] Add 10 second delay to notices api for push notifications

- Source/ProfileOptionsViewController.swift
[LEARNER-8614](https://openedx.atlassian.net/browse/LEARNER-8614)
Fix the wifi-only download functionality that got inverted while porting the feature to the new profile screen. Although, the functionality was working fine but the alert was showing while turning on the wi-fi only switch instead of turning off.
> [fix] Fix the wifi-only Download Functionality

- Libraries/Alamofire/Alamofire.swift
[LEARNER-8638](https://openedx.atlassian.net/browse/LEARNER-8638)
After the update of the version handling the soft and the force app upgrade messages are not working. 
To test the PR change the version number in the settings 
- To see a soft upgrade message update the version number to 2.26.2 
- To see a force upgrade message update the version to 2.20.0
> [fix] app update messages are not working

- Source/CourseContentPageViewController.swift
[LEARNER-8616](https://openedx.atlassian.net/browse/LEARNER-8616)
In `VideoBlockViewController`, `viewWillTransition` is not being called, as `super` is not being called inside `CourseContentPageViewController`, thus iPad native videos have issue with rotation as it is not being rotated properly.
This PR solves this issue.
> [fix] iPad native videos are not working properly

- Source/CourseDatesViewController.swift
- Source/CoursePurchaseIDManager.swift
- Source/CourseUnknownBlockViewController.swift
- Source/CourseUpgradeCompletion.swift
- Source/CourseUpgradeHandler.swift
- Source/CoursesContainerViewController.swift
- Source/EnrolledCoursesViewController.swift
- Source/HTMLBlockViewController.swift
- Source/PaymentManager.swift
- Source/UpgradeSKUManager.swift
- Source/UserCourseEnrollment.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8668](https://openedx.atlassian.net/browse/LEARNER-8668)
After successfully purchasing a course, when the modal dismisses, the VP banner or button is no longer visible because the user should have a verified seat in the course
The trigger for this is a successful purchase (not tied to the "Continue" button of the Success alert)
> [feat] hide upgrade after course purchase success

- Source/AuthenticatedWebViewController.swift
- Source/BannerViewController.swift
- Source/BrowserViewController.swift
- Source/EnrolledCoursesViewController+Banner.swift
- Source/OEXRouter+Swift.swift
- Source/ProfileOptionsViewController.swift
- Source/WebviewCookiesManager.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8700](https://openedx.atlassian.net/browse/LEARNER-8700)
Create a webview cookies manager to manage sessions and other relevant cookies for the `AuthenticatedWebViewController`. The new cookies manager will be responsible for making the oauth2/login API call to get the session and other relevant cookies and save the cookies to load the authenticated webview. 
At the moment, there isn’t any cookies manager to manage the cookies, what we are doing is we are loading the URL in the webview and if the server responds with a special error 404 then the webview first does the /oauth2/login request to load session cookies and then reload the initial request again.
The problem with this approach is that if multiple instances of `AuthenticatedWebViewController` are created then there might …
> feat: create WebviewCookiesManager to manage webview cookies

- Source/CourseOutline.swift
[LEARNER-8708](https://openedx.atlassian.net/browse/LEARNER-8708)
This PR hides special exam block components from the course components screen
> [fix] hide special exam block components

- Source/ar.lproj/Localizable.strings
- Source/ar.lproj/ProfileOptions.strings
- Source/de.lproj/Localizable.strings
- Source/de.lproj/ProfileOptions.strings
- Source/en.lproj/Localizable.strings
- Source/en.lproj/ProfileOptions.strings
- Source/fr.lproj/Localizable.strings
- Source/fr.lproj/ProfileOptions.strings
- Source/he.lproj/Localizable.strings
- Source/he.lproj/ProfileOptions.strings
- Source/ja.lproj/Localizable.strings
- Source/ja.lproj/ProfileOptions.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/pt-BR.lproj/ProfileOptions.strings
- Source/tr.lproj/Localizable.strings
- Source/tr.lproj/ProfileOptions.strings
- Source/vi.lproj/Localizable.strings
- Source/vi.lproj/ProfileOptions.strings
- Source/zh-Hans.lproj/Localizable.strings
- Source/zh-Hans.lproj/ProfileOptions.strings
[LEARNER-8516](https://openedx.atlassian.net/browse/LEARNER-8516)
Pulled the latest translations that broke down on the android platform into multiple files according to the features and updated the strings of the iOS app.
I've pulled the following files from the transifex and updated the relevant sprints on the iOS side.
- [course_dates_strings](https://www.transifex.com/open-edx/edx-mobile-apps/android-app-course_dates_strings/) 
- [course_banners_strings](https://www.transifex.com/open-edx/edx-mobile-apps/android-app-course_banners_strings/)
- [course_modal_strings](https://www.transifex.com/open-edx/edx-mobile-apps/android-app-course_modal_strings/)
- [iap_strings](https://www.transifex.com/open-edx/edx-mobile-apps/android-app-iap_strings/)
- …
> feat: added translations for all languages after 2U release

- Source/CalendarManager.swift
[LEARNER-8739](https://openedx.atlassian.net/browse/LEARNER-8739)
App is crashing while tapping deeplink from Calendar as it was opening malfunction deeplink when user does not have access to course component
> [fix] Add deeplink to calendar event only if block link is available

- buildSrc/build.gradle
[LEARNER-8736](https://openedx.atlassian.net/browse/LEARNER-8736)
upgrade edx-app-gradle-plugin to latest commit hash [link](https://github.com/openedx/edx-app-gradle-plugin/commit/c77472e57075f1c3eb3480a3fbe19f4c00551713) which replaces `compile` to `implementation` 
[link](https://github.com/openedx/edx-app-gradle-plugin/blob/c77472e57075f1c3eb3480a3fbe19f4c00551713/build.gradle) to file
> [chore] upgrade edx-app-gradle-plugin to latest commit hash

- Source/CourseUpgradeCompletion.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8728](https://openedx.atlassian.net/browse/LEARNER-8728)
Send an email to the support team when the user clicks on the Get Support button on the error dialogue.
> [feat] handle Get Support upon error during IAP

- Source/CourseOutlineTableSource.swift
[LEARNER-8738](https://openedx.atlassian.net/browse/LEARNER-8738)
The value prop button was hidden for release 3.1.0 under the ticket [LEARNER-8737:  iOS - Hide Value Prop Button from DashboardMERGED](https://openedx.atlassian.net/browse/LEARNER-8737) because analytics were not implemented and was made dependent on an additional flag IAP_Enabled as a temporary fix.
This PR removes the dependency of the value prop button on the course dashboard from IAP-Enabled and implement the analytics for the value prop button.
> [feat] Show Value Prop Button on Course Dashboard

- .github/workflows/commitlint.yml
[LEARNER-8803](https://openedx.atlassian.net/browse/LEARNER-8803)
After the migration of GitHub repositories from edX org to OpenEdX org, all custom GitHub actions in workflows should also point to the OpenEdx instance instead of edX.
> [build] Point commitlint GitHub action workflow from edx to openEdX

- Source/CourseOutlineViewController.swift
- Source/CourseUnknownBlockViewController.swift
- Source/CourseUpgradeAPI.swift
- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/OEXAuthentication.m
- Source/PaymentManager.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
- Source/ValuePropUnlockViewContainer.swift
- Source/ar.lproj/Localizable.strings
- Source/de.lproj/Localizable.strings
- Source/en.lproj/Localizable.strings
- Source/es-419.lproj/Localizable.strings
- Source/fr.lproj/Localizable.strings
- Source/he.lproj/Localizable.strings
- Source/ja.lproj/Localizable.strings
- Source/pt-BR.lproj/Localizable.strings
- Source/tr.lproj/Localizable.strings
- Source/vi.lproj/Localizable.strings
- Source/zh-Hans.lproj/Localizable.strings
[LEARNER-8798](https://openedx.atlassian.net/browse/LEARNER-8798)
1. Give an option of Retry to the learner as per the [figma](https://www.figma.com/file/SFpqDv2FVf2RRV56ATEakH/Payments?node-id=3061%3A4177) to update the content if the failure occurs after the payment. Add a new button  Refresh to retry in the failure alert that will appear in case of an error after the successful payment. This can happen in the following cases:
- executeAPI failed to verify the payment and update the course mode to verified.
- execute API successfully verified the payment and updated the course mode to verified but:
- enrollment API fails to get the updated enrollments from the server.
- blocks API fails to get the updated data course data from the server.
2. Give an option of Retry to fetch the price …
> [feat] Give A Retry Option to Learner in Failed IAP After The Payment

- Source/CourseOutlineViewController.swift
- Source/CourseUpgradeHelper.swift
- Source/EnrolledCoursesViewController.swift
[LEARNER-8835](https://openedx.atlassian.net/browse/LEARNER-8835)
Fix for:
- “Unlocking full access to your course” screen never resolved loading state post-purchase
- Never got through a successful upgrade
- We have to close the app to get the “Unlocking full access to your course” screen disappear
> [fix] Post IAP Flow is Blocked by Fullscreen Loader

- Source/CourseUnknownBlockViewController.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-8855](https://openedx.atlassian.net/browse/LEARNER-8855)
Leave the button loader animation in the background while the OS takes over the UI to complete payment.
> [feat] keep loader while waiting for my payment success notification

- Source/CourseDatesHeaderView.swift
[LEARNER-8617](https://2u-internal.atlassian.net/browse/LEARNER-8617)
The Calendar toggle overlaps with the title text for RTL languages
> [fix] calendar sync toggle overlapping with text fix

- Source/CoursesContainerViewController.swift
- Source/Deep Linking/DeepLinkManager.swift
- Source/DiscoveryConfig.swift
- Source/DiscoveryViewController.swift
- Source/DiscoveryWebViewHelper.swift
- Source/EnrolledCoursesViewController.swift
- Source/EnrolledTabBarViewController.swift
- Source/OEXCourseInfoViewController.m
- Source/OEXFindCoursesViewController.m
- Source/OEXRouter+Swift.swift
- Source/ProgramsDiscoveryViewController.swift
- Source/StartupViewController.swift
- Test/DiscoveryConfigTests.swift
- Test/EndToEnd/Code/FindCoursesInteractor.swift
- Test/EnrolledCoursesViewControllerTests.swift
[LEARNER-8830](https://2u-internal.atlassian.net/browse/LEARNER-8833)
Replace the existing config of Discovery with the following config:
```
DISCOVERY:
TYPE: 'webview'
WEBVIEW:
BASE_URL: 'https://www.edx.org/webview/v2/search'
COURSE_DETAIL_TEMPLATE: 'https://www.edx.org/webview/course/{path_id}'
PROGRAM_DETAIL_TEMPLATE: 'https://www.edx.org/webview/{path_id}'
```
> [feat] Implement The Latest Version of Discover Experience

- Pods/Pods.xcodeproj/project.pbxproj
[LEARNER-8929](https://2u-internal.atlassian.net/browse/LEARNER-8929)
The app was not archiving with Xcode after recent CocoaPods updates and was giving duplicate file errors for multiple files of Firebase pods.
> [fix] Fix CocoaPods Configurations for Xcode Archives

- Source/AppleSocial.swift
- Source/OEXRegistrationViewController.m
[LEARNER-8951](https://2u-internal.atlassian.net/browse/LEARNER-8951)
Currently, subsequent logins to the app using Sign In with Apple with the same account do not share any user info and will only return a user identifier in the ASAuthorizationAppleIDCredential. Due to this we are getting no response in the Full Name field which is failing the App Review on App Store Connect.
It is recommended that we securely cache the initial ASAuthorizationAppleIDCredential containing the user info until we can validate that an account has successfully been created on your server.
> [chore] Sign Up With Apple Improvements

- Source/DiscoveryWebViewHelper.swift
[LEARNER-8972](https://2u-internal.atlassian.net/browse/LEARNER-8972)
After the release of our new discovery experience, the WebKit crash is occurring at high velocity in certain scenarios. More details on the crash can be found in the link below:
The crash is reproducible only in dev environment. To reproducible the crash `return`  without taking any decision from the delegate method `func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void)`
> [fix] Fix webkit crash in course discovery

- Source/CourseUnknownBlockViewController.swift
- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/OEXAnalytics+CourseUpgrade.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAuthentication.m
- Source/PaymentManager.swift
- Source/ValuePropDetailViewController.swift
- Source/ar.lproj/CourseUpgrade.strings
- Source/de.lproj/CourseUpgrade.strings
- Source/en.lproj/CourseUpgrade.strings
- Source/es-419.lproj/CourseUpgrade.strings
- Source/fr.lproj/CourseUpgrade.strings
- Source/he.lproj/CourseUpgrade.strings
- Source/ja.lproj/CourseUpgrade.strings
- Source/pt-BR.lproj/CourseUpgrade.strings
- Source/tr.lproj/CourseUpgrade.strings
- Source/vi.lproj/CourseUpgrade.strings
- Source/zh-Hans.lproj/CourseUpgrade.strings
[LEARNER-8994](https://2u-internal.atlassian.net/browse/LEARNER-8994)
**Pre-Purchase**
Add a prompt after the user taps the ‘Upgrade’ button that informs the user of their personal data being used to verify SDN. Prompt copy TBD. 
- If the user opts-in, continue to the normal check-out flow.
- If the user does not opt-in, cancel the checkout and direct the user to the previous screen.
Add Analytics for SDN `accept` or `cancel`
Title and message of SDN prompt is not finalised yet.
> [chore] add SDN prompt for user before payment process

- Source/Core/Code/NetworkManager.swift
- Source/Core/Code/RegistrationFormAPI.swift
- Source/Core/Test/Code/NetworkManagerTests.swift
- Source/NetworkManager+Authenticators.swift
- Source/NetworkManager+QueuedTask.swift
- Source/NetworkManager+WaitingTask.swift
- Source/OEXAuthentication.m
- Source/OEXEnvironment.m
- Source/OEXRouter+Swift.swift
- Source/OEXSession+SessionData.swift
- Source/OEXSession.h
- Source/OEXSession.m
- Source/RemoteImage.swift
- Test/CourseOutlineQuerierTests.swift
- Test/EndToEnd/Code/TestCredentials.swift
- Test/MockNetworkManager.swift
- Test/MockRouter.swift
- Test/NetworkManager+AuthenticatorTests.swift
- Test/NetworkManager+InterceptionTests.swift
- Test/OEXFindCoursesTests.m
- Test/RemoteImageTests.swift
- Test/TestRouterEnvironment.swift
- Test/UserProfileManagerTests.swift
- edX.xcodeproj/project.pbxproj
[LEARNER-8988](https://2u-internal.atlassian.net/browse/LEARNER-8988)
This PR contains improvements for handling the expired token and making multiple requests for refreshing access token. Now application will attempt only one refresh token call and will queue the errored response request, along with queuing subsequent requests.
> [chore] refresh token improvements

- Source/VideoDownloadQualityViewController.swift
[LEARNER-9013](https://2u-internal.atlassian.net/browse/LEARNER-9013)
Hide Cross button in the video download quality selection screen when accessed from the profile screen
> [fix] Hide cross button in the video download quality selection screen

- Source/Core/Code/NetworkManager.swift
- Source/Core/Test/Code/NetworkManagerTests.swift
- Source/NetworkManager+Authenticators.swift
- Source/NetworkManager+QueuedTask.swift
- Source/OEXAccessToken.h
- Source/OEXAccessToken.m
- Source/OEXEnvironment.m
- Source/OEXRouter+Swift.swift
- Source/OEXSession+SessionData.swift
- Source/OEXSession.h
- Source/OEXSession.m
- Test/OEXMockCredentialStorage.m
- Test/OEXSessionTests.m
- Test/RemoteImageTests.swift
[LEARNER-8968](https://2u-internal.atlassian.net/browse/LEARNER-8968)
This PR applies token expiry to the network requests before a network call is made. The expiry duration is saved and it is applied before a network request is queued.
> [chore] add token expiry to network layer

- Source/CourseUpgradeHandler.swift
- Source/CourseUpgradeHelper.swift
- Source/PaymentManager.swift
[LEARNER-9007](https://2u-internal.atlassian.net/browse/LEARNER-9007)
This PR stops stop an edX user logged in the app from restoring purchases of another edX user logged in the AppStore on the same device.
* Sign in with edX app user A, make a payment for a course e.g Demo Course and logout
* Sign in with another edX app user B who enrolled in the same course Demo Course on the same device
* Try to upgrade the course, App store will return information for the old transaction.
* App Should give an error like course has been paid by another user on the same device.
> [chore] Handle Duplicate Transactions ID Gracefully

- Source/NSError+JSON.swift
- Test/NetworkManager+AuthenticatorTests.swift
[LEARNER-8967](https://2u-internal.atlassian.net/browse/LEARNER-8967)
Logout disabled user on receiving the response following response in response of `oauth2/login/`
```
URL: https://courses.edx.org/oauth2/login/
status_code: 401
{
"error_code": "account_disabled",
"developer_message": "User account is disabled."
}
```
- Sign in with a valid user
- Disabled the user from the support tool
- rerun the app and see the response of `/oauth2/login/`
> [feat] logout disabled user

- Source/CoursesAPI.swift
- Source/ServerConfiguration.swift
[LEARNER-9071](https://2u-internal.atlassian.net/browse/LEARNER-9071)
Changes are made to the enrollments API to return the value_prop and the IAP  configs. 
###Config PR
https://github.com/edx/edx-mobile-config/pull/130
> chore: incorporate enrollments v2 changes

- Source/CourseUpgradeButtonView.swift
- Source/OEXAnalytics+CourseUpgrade.swift
- Source/OEXAnalytics+Swift.swift
- Source/OEXAppDelegate.m
- Source/OEXConfig+AppFeatures.swift
- Source/ProfileOptionsViewController.swift
- Source/ServerConfiguration.swift
- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9031](https://2u-internal.atlassian.net/browse/LEARNER-9031)
The config changes are available on the [iapduplicate sandbox](https://iapduplicate.sandbox.edx.org). 
`saeed/Fedx1234` and `saeed1/Fedx1234` users can be used to test the PR.
if IAP enabled flag & IAP experiment enabled flag are enabled:
if IAP enabled flag is enabled & IAP experiment enabled flag is disabled:
> [chore] IAP and IAP Experiment flags for handling of treatment and  control for IAP experiment

- Source/NetworkManager+Authenticators.swift
[LEARNER-9112](https://2u-internal.atlassian.net/browse/LEARNER-9112)
Fixed the crash happening randomly for few learners after the release 3.1.3. The possible reason for the crash is, the static func memory got free after the closure return and the caller wasn't finished its job.
Gave execution to another static func with the main thread so after closure the pending calls should its own memory stack.
The crash is not reproducible. We will see after the next release either the crash is fixed or not.
> fix: fix possible network layer crash

- Source/CourseUpgradeHandler.swift
- Source/EnrolledCoursesViewController+CourseUpgrade.swift
[LEARNER-9135](https://2u-internal.atlassian.net/browse/LEARNER-9135)
Fixed the case where the `Unlocking full access to the course` banner was not removing after upgrading the course from dashboard or course component screen.
I've also fixed the case where the error message for request time out was not being sent in the email.
> fix: fix removing of unlocking full access banner on course upgrade

- Source/ValuePropComponentView.swift
- Source/ValuePropDetailViewController.swift
[LEARNER-9132](https://2u-internal.atlassian.net/browse/LEARNER-9132)
Don't send price load analytics when the payment is disabled for the control group.
> fix: disable price load event for control group

- Source/AuthenticatedWebViewController.swift
- Source/HTMLBlockViewController.swift
- Source/NetworkManager+Authenticators.swift
- Source/OEXCourseInfoViewController.m
- Source/ProgramsDiscoveryViewController.swift
- Source/UIApplication+UIViewController.swift
[LEARNER-9143](https://2u-internal.atlassian.net/browse/LEARNER-9143)
Xcode was giving warnings, and was also crashing with non fatals while accessing Application window and interface orientation on background thread. This PR added the capability to access the window and interface orientation on main thread.
This PR also removed the test logs added to figure out the  possible reason on crash. The logs were not helpful much, so removing the test logs.
> Fix: Access Window object on Main Thread

- Source/DiscoveryWebViewHelper.swift
[LEARNER-9245](https://2u-internal.atlassian.net/browse/LEARNER-9245)
The external_link parameter is added on the cards of Simmons University under the Bachelors. But it requires a location of USA. A VPN can be used to simulate the location of USA.
> feat: Add support for external_link parameter in discover webview

- Source/OEXPushNotificationManager.m
[LEARNER-9324](https://2u-internal.atlassian.net/browse/LEARNER-9324)
The push notification was delivered silently because of [provisional](https://developer.apple.com/documentation/usernotifications/unauthorizationoptions/2993019-provisional) value of  [UNAuthorizationOptions](https://developer.apple.com/documentation/usernotifications/unauthorizationoptions). I've removed `provisional` from the push notifications settings. Now the push is being received with alert and sound.
> fix: send push notification with sound and alert

- Source/CourseContentPageViewController.swift
[LEARNER-9409](https://2u-internal.atlassian.net/browse/LEARNER-9409)
This Pr fixes bug inside `CourseContentPageViewController` when user swipes quickly between controllers.
> chore: handle user interaction when user swipes quickly inside page view controller

- Source/CalendarManager.swift
- Source/edX-Info.plist
[LEARNER-9807](https://2u-internal.atlassian.net/browse/LEARNER-9807)
Prior to this update, individuals using iPhones with iOS 17 or later were unable to synchronize courses with the calendar on their devices. The problem stemmed from the utilization of a deprecated function for accessing calendar events permissions.
**Deprecated Function of `EKEventStore`:**
```
requestAccess(to:completion:)
For iOS 17 and subsequent versions, utilizing this method does not trigger an access prompt; instead, it promptly invokes the completion block with an error.
```
Within this pull request, we have incorporated a new method for the `EKEventStore` that is compatible with iOS 17 and later versions.
```
requestFullAccessToEvents(completion:)
```
Additionally, included the …
> fix: Learners can't sync courses to calendar on iPhone

- Source/CourseDates.swift
[LEARNER-9936](https://2u-internal.atlassian.net/browse/LEARNER-9936)
Implemented support for hours, minutes, and seconds in dates to prevent calendar synchronization update alerts when replacing the production application with the new codebase.
Prior to merging this PR, all calendar events were being added to the mobile native calendar at the timestamp of **04:00AM to 05:00AM** because we were previously disregarding hours, minutes, and seconds. Therefore, we are now taking them into account, ensuring that calendar events are added at the exact time received from the backend.
| Before | After |
|----------|----------|
| ![Simulator Screenshot - iPhone 15 - 2024-04-19 at 18 00 31](https://github.com/openedx/edx-app-ios/assets/11990137/e9bded42-e79d-4d82-8791-d80b2a1b2e0d) | ![Simulator …
> fix: Add Support For Hours, Minutes and Seconds in Dates
